"""Stable SDK surface for CodeIntel target packs."""

from __future__ import annotations

from codeintel.sdk.annotations import schema_output, tag, tag_output
from codeintel.sdk.columns import pipe_input, pipe_output, with_columns_lazy
from codeintel.sdk.io import dataloader, datasaver, load_from, save_to
from codeintel.sdk.save_to import (
    ArtifactSaveOptions,
    RelationTableSaveOptions,
    TableSaveOptions,
    save_to_artifact,
    save_to_relation_table,
    save_to_table,
)
from codeintel.sdk.tags import (
    NODE_TYPE_ARTIFACT,
    NODE_TYPE_COMPUTE,
    NODE_TYPE_DATASET,
    NODE_TYPE_HELPER,
    NODE_TYPE_LOADER_QUERY,
    NODE_TYPE_MATERIALIZE,
    NODE_TYPE_TOOL,
    OUTPUT_KIND_SEMANTIC_VIEW,
    OUTPUT_KIND_TABLE,
    OUTPUT_KIND_VIEW,
    TAG_ARTIFACT,
    TAG_ARTIFACT_PATH_TEMPLATE,
    TAG_DEFAULT_LIMIT,
    TAG_DEFAULT_ORDER,
    TAG_DOMAIN,
    TAG_ENTITY,
    TAG_GRAIN,
    TAG_MCP_VISIBLE,
    TAG_NODE_TYPE,
    TAG_OUTPUT_KIND,
    TAG_SEMANTIC_COLS,
    TAG_SEMANTIC_DESC,
    TAG_SEMANTIC_ENTITY,
    TAG_SEMANTIC_GRAIN,
    TAG_SEMANTIC_ID,
    TAG_SEMANTIC_JOINS,
    TAG_SEMANTIC_KIND,
    TAG_SEMANTIC_PK,
    TAG_SENSITIVITY,
    TAG_TABLE_KEY,
    TAG_TARGET,
    TAG_TARGET_ESTIMATED_DURATION_MS,
    TAG_TARGET_EXECUTION,
    TAG_TARGET_PARAMETERS,
    TAG_TARGET_RESOURCES,
    TAG_TARGET_SPEC_VERSION,
    TAG_TOOLS,
)
from codeintel.sdk.target import (
    BuildEnv,
    DagCatalog,
    MaterializationBundle,
    MaterializationResult,
    TargetRunRecord,
    TargetSpecDescriptor,
    finalize_materializations,
    target_anchor,
)
from codeintel.sdk.validation import check_output_fail, check_output_warn

__all__ = [
    "NODE_TYPE_ARTIFACT",
    "NODE_TYPE_COMPUTE",
    "NODE_TYPE_DATASET",
    "NODE_TYPE_HELPER",
    "NODE_TYPE_LOADER_QUERY",
    "NODE_TYPE_MATERIALIZE",
    "NODE_TYPE_TOOL",
    "OUTPUT_KIND_SEMANTIC_VIEW",
    "OUTPUT_KIND_TABLE",
    "OUTPUT_KIND_VIEW",
    "TAG_ARTIFACT",
    "TAG_ARTIFACT_PATH_TEMPLATE",
    "TAG_DEFAULT_LIMIT",
    "TAG_DEFAULT_ORDER",
    "TAG_DOMAIN",
    "TAG_ENTITY",
    "TAG_GRAIN",
    "TAG_MCP_VISIBLE",
    "TAG_NODE_TYPE",
    "TAG_OUTPUT_KIND",
    "TAG_SEMANTIC_COLS",
    "TAG_SEMANTIC_DESC",
    "TAG_SEMANTIC_ENTITY",
    "TAG_SEMANTIC_GRAIN",
    "TAG_SEMANTIC_ID",
    "TAG_SEMANTIC_JOINS",
    "TAG_SEMANTIC_KIND",
    "TAG_SEMANTIC_PK",
    "TAG_SENSITIVITY",
    "TAG_TABLE_KEY",
    "TAG_TARGET",
    "TAG_TARGET_ESTIMATED_DURATION_MS",
    "TAG_TARGET_EXECUTION",
    "TAG_TARGET_PARAMETERS",
    "TAG_TARGET_RESOURCES",
    "TAG_TARGET_SPEC_VERSION",
    "TAG_TOOLS",
    "ArtifactSaveOptions",
    "BuildEnv",
    "DagCatalog",
    "MaterializationBundle",
    "MaterializationResult",
    "RelationTableSaveOptions",
    "TableSaveOptions",
    "TargetRunRecord",
    "TargetSpecDescriptor",
    "check_output_fail",
    "check_output_warn",
    "dataloader",
    "datasaver",
    "finalize_materializations",
    "load_from",
    "pipe_input",
    "pipe_output",
    "save_to",
    "save_to_artifact",
    "save_to_relation_table",
    "save_to_table",
    "schema_output",
    "tag",
    "tag_output",
    "target_anchor",
    "with_columns_lazy",
]
