"""Column definitions for CFG/DFG analytics tables.

This module provides the column schema definitions used by the Hamilton native
module ``codeintel.build.hamilton.native.analytics.cfg_dfg``.

The pure compute functions are available in ``codeintel.analytics.cfg_dfg.compute``:
- ``compute_cfg_metrics_pure`` returns ``CfgMetricsResult``
- ``compute_dfg_metrics_pure`` returns ``DfgMetricsResult``
"""

from __future__ import annotations

CFG_FUNCTION_METRICS_COLS = [
    "function_goid_h128",
    "repo",
    "commit",
    "rel_path",
    "module",
    "qualname",
    "cfg_block_count",
    "cfg_edge_count",
    "cfg_has_cycles",
    "cfg_scc_count",
    "cfg_longest_path_len",
    "cfg_avg_shortest_path_len",
    "cfg_branching_factor_mean",
    "cfg_branching_factor_max",
    "cfg_linear_block_fraction",
    "cfg_dom_tree_height",
    "cfg_dominance_frontier_size_mean",
    "cfg_dominance_frontier_size_max",
    "cfg_loop_count",
    "cfg_loop_nesting_depth_max",
    "cfg_bc_betweenness_max",
    "cfg_bc_betweenness_mean",
    "cfg_bc_closeness_mean",
    "cfg_bc_eigenvector_max",
    "created_at",
    "metrics_version",
]
CFG_BLOCK_METRICS_COLS = [
    "function_goid_h128",
    "repo",
    "commit",
    "block_idx",
    "is_entry",
    "is_exit",
    "is_branch",
    "is_join",
    "dom_depth",
    "dominates_exit",
    "bc_betweenness",
    "bc_closeness",
    "bc_eigenvector",
    "in_loop_scc",
    "loop_header",
    "loop_nesting_depth",
    "created_at",
    "metrics_version",
]
CFG_FUNCTION_METRICS_EXT_COLS = [
    "function_goid_h128",
    "repo",
    "commit",
    "unreachable_block_count",
    "loop_header_count",
    "true_edge_count",
    "false_edge_count",
    "back_edge_count",
    "exception_edge_count",
    "fallthrough_edge_count",
    "loop_edge_count",
    "entry_exit_simple_paths",
    "created_at",
    "metrics_version",
]


DFG_FUNCTION_METRICS_COLS = [
    "function_goid_h128",
    "repo",
    "commit",
    "rel_path",
    "module",
    "qualname",
    "dfg_block_count",
    "dfg_edge_count",
    "dfg_phi_edge_count",
    "dfg_symbol_count",
    "dfg_component_count",
    "dfg_scc_count",
    "dfg_has_cycles",
    "dfg_longest_chain_len",
    "dfg_avg_shortest_path_len",
    "dfg_avg_in_degree",
    "dfg_avg_out_degree",
    "dfg_max_in_degree",
    "dfg_max_out_degree",
    "dfg_branchy_block_fraction",
    "dfg_bc_betweenness_max",
    "dfg_bc_betweenness_mean",
    "dfg_bc_eigenvector_max",
    "created_at",
    "metrics_version",
]
DFG_BLOCK_METRICS_COLS = [
    "function_goid_h128",
    "repo",
    "commit",
    "block_idx",
    "dfg_in_degree",
    "dfg_out_degree",
    "dfg_phi_in_degree",
    "dfg_phi_out_degree",
    "dfg_bc_betweenness",
    "dfg_bc_closeness",
    "dfg_bc_eigenvector",
    "dfg_in_scc",
    "dfg_in_chain",
    "created_at",
    "metrics_version",
]
DFG_FUNCTION_METRICS_EXT_COLS = [
    "function_goid_h128",
    "repo",
    "commit",
    "data_flow_edge_count",
    "intra_block_edge_count",
    "use_kind_phi_count",
    "use_kind_data_flow_count",
    "use_kind_intra_block_count",
    "use_kind_other_count",
    "phi_edge_ratio",
    "entry_exit_simple_paths",
    "created_at",
    "metrics_version",
]
