"""SQLGlot toolkit for DuckDB dialect operations (re-exported from core)."""

from __future__ import annotations

from codeintel.core.sqlglot_tools import (
    SELECT_ONLY_DISALLOWED_NODES,
    AstCapabilityConfig,
    AstCapabilityError,
    AstCapabilityIssue,
    AstCapabilityReport,
    GeneratorConfig,
    ParseError,
    QuerySummaryConfig,
    canonical_sql_duckdb,
    canonicalize_expression_duckdb,
    canonicalize_select_duckdb,
    capability_envelope_report,
    ensure_ast_capability,
    extract_column_lineage_duckdb,
    extract_column_lineage_from_ast,
    extract_table_keys_duckdb,
    extract_table_refs,
    fingerprint_canonical_sql,
    fingerprint_expression_duckdb,
    fingerprint_sql_duckdb,
    fingerprint_sql_duckdb_safe,
    normalize_sql_for_hash,
    parse_one_duckdb,
    render_sql_duckdb,
    render_sql_duckdb_safe,
    schema_mapping_for_table_key,
    semantic_diff_sql_duckdb,
    summarize_sql_duckdb,
    table_expr_from_ref,
)

__all__ = [
    "SELECT_ONLY_DISALLOWED_NODES",
    "AstCapabilityConfig",
    "AstCapabilityError",
    "AstCapabilityIssue",
    "AstCapabilityReport",
    "GeneratorConfig",
    "ParseError",
    "QuerySummaryConfig",
    "canonical_sql_duckdb",
    "canonicalize_expression_duckdb",
    "canonicalize_select_duckdb",
    "capability_envelope_report",
    "ensure_ast_capability",
    "extract_column_lineage_duckdb",
    "extract_column_lineage_from_ast",
    "extract_table_keys_duckdb",
    "extract_table_refs",
    "fingerprint_canonical_sql",
    "fingerprint_expression_duckdb",
    "fingerprint_sql_duckdb",
    "fingerprint_sql_duckdb_safe",
    "normalize_sql_for_hash",
    "parse_one_duckdb",
    "render_sql_duckdb",
    "render_sql_duckdb_safe",
    "schema_mapping_for_table_key",
    "semantic_diff_sql_duckdb",
    "summarize_sql_duckdb",
    "table_expr_from_ref",
]
