"""Columnar streaming protocols and adapters."""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from codeintel.core.columnar.acero_ops import build_exec_plan
    from codeintel.core.columnar.arrowdsl import (
        ExecutionContext,
        ExecutionPlan,
        JoinPrecheckSpec,
        apply_deterministic_order,
        join_safe_projection,
        list_payload_columns,
        precheck_join_keys,
        require_join_safe_schema,
        run_pipeline,
    )
    from codeintel.core.columnar.compute import (
        count_distinct,
        count_non_positive,
        count_true,
        orphan_ref_count,
    )
    from codeintel.core.columnar.compute_config import (
        DEFAULT_CAST_SAFE,
        DEFAULT_SCALAR_AGG,
        DEFAULT_SCALAR_AGG_ALLOW_NULL,
        DEFAULT_TAKE,
    )
    from codeintel.core.columnar.compute_helpers import call_compute, require_array, require_scalar
    from codeintel.core.columnar.dedupe_ops import (
        DedupeDeterminism,
        DedupeLegacy,
        DedupeSpec,
        DedupeStrategy,
        DedupeTier,
        dedupe_table_for_table,
    )
    from codeintel.core.columnar.explode_ops import (
        ExplodeResult,
        ExplodeSpec,
        explode_edges,
        explode_list_struct,
    )
    from codeintel.core.columnar.expr_vocab import E, ExprVocab
    from codeintel.core.columnar.finalize_ops import (
        AlignmentReport,
        FinalizeDedupe,
        FinalizeInvariant,
        FinalizeListPolicy,
        FinalizeMode,
        FinalizeResult,
        FinalizeSpec,
        JoinPrecheckReport,
        NullListPolicy,
        drain_join_precheck_reports,
        finalize_join_keys,
        finalize_reader,
        finalize_reader_batches,
        finalize_table,
        record_join_precheck_errors,
    )
    from codeintel.core.columnar.groupby import group_by_aggregate
    from codeintel.core.columnar.ipc_ops import (
        ArrowIpcStreamError,
        iter_ipc_stream,
        read_ipc_stream,
        write_ipc_stream,
    )
    from codeintel.core.columnar.iter import iter_array_values, iter_batches, iter_rows
    from codeintel.core.columnar.kernels import (
        case_when,
        coalesce,
        hash_struct_goid,
        hash_struct_ordinal,
        indices_nonzero,
        list_element,
        list_slice,
        list_value_length,
        regex_match,
        regex_replace,
        replace_with_mask,
        safe_cast,
        safe_divide,
        stable_sort_indices,
        stable_sort_table,
        struct_field,
    )
    from codeintel.core.columnar.masks import (
        and_mask,
        fill_null_false,
        filter_valid,
        invert_mask,
        is_valid_mask,
    )
    from codeintel.core.columnar.nested_ops import (
        deep_cast_array,
        deep_cast_table_to_contract,
        make_extras_kv_map,
        make_extras_struct,
        unify_schemas_with_contract_first,
    )
    from codeintel.core.columnar.normalization import (
        normalize_array,
        normalize_array_for_compute,
        normalize_table,
        normalize_table_for_compute,
    )
    from codeintel.core.columnar.plan_ops import (
        ExternalPlanSpec,
        HashJoinSpec,
        Plan,
        list_external_plan_runners,
        materialize_plan,
        register_external_plan_runner,
        run_external_plan,
    )
    from codeintel.core.columnar.rows import (
        ColumnarRowBuffer,
        ColumnarRows,
        columnar_buffer_for_table_key,
        columnar_row_count,
    )
    from codeintel.core.columnar.schema_alignment import (
        align_reader_to_contract,
        extras_policy_from_schema,
    )
    from codeintel.core.columnar.schema_ops import concat_tables_unified, unify_schemas
    from codeintel.core.columnar.set_ops import is_in_mask, value_set
    from codeintel.core.columnar.stream import (
        ColumnarStream,
        ColumnarStreamAdapter,
        LazyFrameStream,
        RecordBatchReaderStream,
        coerce_arrow_reader,
        coerce_arrow_table,
    )

    _TYPE_CHECKING_EXPORTS = (
        DEFAULT_CAST_SAFE,
        DEFAULT_SCALAR_AGG,
        DEFAULT_SCALAR_AGG_ALLOW_NULL,
        DEFAULT_TAKE,
        count_distinct,
        count_non_positive,
        count_true,
        orphan_ref_count,
        call_compute,
        require_array,
        require_scalar,
        DedupeDeterminism,
        DedupeLegacy,
        DedupeSpec,
        DedupeStrategy,
        DedupeTier,
        dedupe_table_for_table,
        build_exec_plan,
        E,
        ExprVocab,
        ExecutionContext,
        ExecutionPlan,
        JoinPrecheckSpec,
        ExplodeResult,
        ExplodeSpec,
        explode_edges,
        explode_list_struct,
        AlignmentReport,
        FinalizeDedupe,
        FinalizeInvariant,
        FinalizeListPolicy,
        FinalizeMode,
        FinalizeResult,
        FinalizeSpec,
        JoinPrecheckReport,
        NullListPolicy,
        drain_join_precheck_reports,
        finalize_join_keys,
        finalize_reader_batches,
        finalize_reader,
        finalize_table,
        record_join_precheck_errors,
        group_by_aggregate,
        apply_deterministic_order,
        ArrowIpcStreamError,
        join_safe_projection,
        iter_ipc_stream,
        list_payload_columns,
        precheck_join_keys,
        read_ipc_stream,
        require_join_safe_schema,
        run_pipeline,
        write_ipc_stream,
        iter_array_values,
        iter_batches,
        iter_rows,
        case_when,
        coalesce,
        hash_struct_goid,
        hash_struct_ordinal,
        indices_nonzero,
        list_element,
        list_slice,
        list_value_length,
        regex_match,
        regex_replace,
        replace_with_mask,
        safe_cast,
        safe_divide,
        stable_sort_indices,
        stable_sort_table,
        struct_field,
        and_mask,
        fill_null_false,
        filter_valid,
        invert_mask,
        is_valid_mask,
        normalize_array,
        normalize_array_for_compute,
        normalize_table,
        normalize_table_for_compute,
        deep_cast_array,
        deep_cast_table_to_contract,
        make_extras_kv_map,
        make_extras_struct,
        unify_schemas_with_contract_first,
        ExternalPlanSpec,
        HashJoinSpec,
        Plan,
        list_external_plan_runners,
        materialize_plan,
        register_external_plan_runner,
        run_external_plan,
        ColumnarRowBuffer,
        ColumnarRows,
        columnar_buffer_for_table_key,
        columnar_row_count,
        align_reader_to_contract,
        extras_policy_from_schema,
        concat_tables_unified,
        unify_schemas,
        ColumnarStream,
        ColumnarStreamAdapter,
        LazyFrameStream,
        RecordBatchReaderStream,
        coerce_arrow_reader,
        coerce_arrow_table,
        is_in_mask,
        value_set,
    )

_EXPORTS: dict[str, tuple[str, str]] = {
    "DEFAULT_CAST_SAFE": ("codeintel.core.columnar.compute_config", "DEFAULT_CAST_SAFE"),
    "DEFAULT_SCALAR_AGG": ("codeintel.core.columnar.compute_config", "DEFAULT_SCALAR_AGG"),
    "DEFAULT_SCALAR_AGG_ALLOW_NULL": (
        "codeintel.core.columnar.compute_config",
        "DEFAULT_SCALAR_AGG_ALLOW_NULL",
    ),
    "DEFAULT_TAKE": ("codeintel.core.columnar.compute_config", "DEFAULT_TAKE"),
    "count_distinct": ("codeintel.core.columnar.compute", "count_distinct"),
    "count_non_positive": ("codeintel.core.columnar.compute", "count_non_positive"),
    "count_true": ("codeintel.core.columnar.compute", "count_true"),
    "orphan_ref_count": ("codeintel.core.columnar.compute", "orphan_ref_count"),
    "call_compute": ("codeintel.core.columnar.compute_helpers", "call_compute"),
    "require_array": ("codeintel.core.columnar.compute_helpers", "require_array"),
    "require_scalar": ("codeintel.core.columnar.compute_helpers", "require_scalar"),
    "DedupeDeterminism": ("codeintel.core.columnar.dedupe_ops", "DedupeDeterminism"),
    "DedupeLegacy": ("codeintel.core.columnar.dedupe_ops", "DedupeLegacy"),
    "DedupeSpec": ("codeintel.core.columnar.dedupe_ops", "DedupeSpec"),
    "DedupeStrategy": ("codeintel.core.columnar.dedupe_ops", "DedupeStrategy"),
    "DedupeTier": ("codeintel.core.columnar.dedupe_ops", "DedupeTier"),
    "dedupe_table_for_table": ("codeintel.core.columnar.dedupe_ops", "dedupe_table_for_table"),
    "ExecutionContext": ("codeintel.core.columnar.arrowdsl", "ExecutionContext"),
    "ExecutionPlan": ("codeintel.core.columnar.arrowdsl", "ExecutionPlan"),
    "JoinPrecheckSpec": ("codeintel.core.columnar.arrowdsl", "JoinPrecheckSpec"),
    "build_exec_plan": ("codeintel.core.columnar.acero_ops", "build_exec_plan"),
    "ExternalPlanSpec": ("codeintel.core.columnar.plan_ops", "ExternalPlanSpec"),
    "E": ("codeintel.core.columnar.expr_vocab", "E"),
    "ExprVocab": ("codeintel.core.columnar.expr_vocab", "ExprVocab"),
    "apply_deterministic_order": (
        "codeintel.core.columnar.arrowdsl",
        "apply_deterministic_order",
    ),
    "ExplodeResult": ("codeintel.core.columnar.explode_ops", "ExplodeResult"),
    "ExplodeSpec": ("codeintel.core.columnar.explode_ops", "ExplodeSpec"),
    "explode_edges": ("codeintel.core.columnar.explode_ops", "explode_edges"),
    "explode_list_struct": ("codeintel.core.columnar.explode_ops", "explode_list_struct"),
    "AlignmentReport": ("codeintel.core.columnar.finalize_ops", "AlignmentReport"),
    "FinalizeDedupe": ("codeintel.core.columnar.finalize_ops", "FinalizeDedupe"),
    "FinalizeInvariant": ("codeintel.core.columnar.finalize_ops", "FinalizeInvariant"),
    "FinalizeListPolicy": ("codeintel.core.columnar.finalize_ops", "FinalizeListPolicy"),
    "FinalizeMode": ("codeintel.core.columnar.finalize_ops", "FinalizeMode"),
    "FinalizeResult": ("codeintel.core.columnar.finalize_ops", "FinalizeResult"),
    "FinalizeSpec": ("codeintel.core.columnar.finalize_ops", "FinalizeSpec"),
    "JoinPrecheckReport": ("codeintel.core.columnar.finalize_ops", "JoinPrecheckReport"),
    "NullListPolicy": ("codeintel.core.columnar.finalize_ops", "NullListPolicy"),
    "drain_join_precheck_reports": (
        "codeintel.core.columnar.finalize_ops",
        "drain_join_precheck_reports",
    ),
    "finalize_join_keys": ("codeintel.core.columnar.finalize_ops", "finalize_join_keys"),
    "finalize_reader_batches": (
        "codeintel.core.columnar.finalize_ops",
        "finalize_reader_batches",
    ),
    "finalize_reader": ("codeintel.core.columnar.finalize_ops", "finalize_reader"),
    "finalize_table": ("codeintel.core.columnar.finalize_ops", "finalize_table"),
    "record_join_precheck_errors": (
        "codeintel.core.columnar.finalize_ops",
        "record_join_precheck_errors",
    ),
    "group_by_aggregate": ("codeintel.core.columnar.groupby", "group_by_aggregate"),
    "ArrowIpcStreamError": ("codeintel.core.columnar.ipc_ops", "ArrowIpcStreamError"),
    "join_safe_projection": ("codeintel.core.columnar.arrowdsl", "join_safe_projection"),
    "iter_ipc_stream": ("codeintel.core.columnar.ipc_ops", "iter_ipc_stream"),
    "list_payload_columns": ("codeintel.core.columnar.arrowdsl", "list_payload_columns"),
    "precheck_join_keys": ("codeintel.core.columnar.arrowdsl", "precheck_join_keys"),
    "read_ipc_stream": ("codeintel.core.columnar.ipc_ops", "read_ipc_stream"),
    "require_join_safe_schema": ("codeintel.core.columnar.arrowdsl", "require_join_safe_schema"),
    "run_pipeline": ("codeintel.core.columnar.arrowdsl", "run_pipeline"),
    "write_ipc_stream": ("codeintel.core.columnar.ipc_ops", "write_ipc_stream"),
    "iter_array_values": ("codeintel.core.columnar.iter", "iter_array_values"),
    "iter_batches": ("codeintel.core.columnar.iter", "iter_batches"),
    "iter_rows": ("codeintel.core.columnar.iter", "iter_rows"),
    "case_when": ("codeintel.core.columnar.kernels", "case_when"),
    "coalesce": ("codeintel.core.columnar.kernels", "coalesce"),
    "hash_struct_goid": ("codeintel.core.columnar.kernels", "hash_struct_goid"),
    "hash_struct_ordinal": ("codeintel.core.columnar.kernels", "hash_struct_ordinal"),
    "indices_nonzero": ("codeintel.core.columnar.kernels", "indices_nonzero"),
    "list_element": ("codeintel.core.columnar.kernels", "list_element"),
    "list_slice": ("codeintel.core.columnar.kernels", "list_slice"),
    "list_value_length": ("codeintel.core.columnar.kernels", "list_value_length"),
    "regex_match": ("codeintel.core.columnar.kernels", "regex_match"),
    "regex_replace": ("codeintel.core.columnar.kernels", "regex_replace"),
    "replace_with_mask": ("codeintel.core.columnar.kernels", "replace_with_mask"),
    "safe_cast": ("codeintel.core.columnar.kernels", "safe_cast"),
    "safe_divide": ("codeintel.core.columnar.kernels", "safe_divide"),
    "stable_sort_indices": ("codeintel.core.columnar.kernels", "stable_sort_indices"),
    "stable_sort_table": ("codeintel.core.columnar.kernels", "stable_sort_table"),
    "struct_field": ("codeintel.core.columnar.kernels", "struct_field"),
    "and_mask": ("codeintel.core.columnar.masks", "and_mask"),
    "fill_null_false": ("codeintel.core.columnar.masks", "fill_null_false"),
    "filter_valid": ("codeintel.core.columnar.masks", "filter_valid"),
    "invert_mask": ("codeintel.core.columnar.masks", "invert_mask"),
    "is_valid_mask": ("codeintel.core.columnar.masks", "is_valid_mask"),
    "normalize_array": ("codeintel.core.columnar.normalization", "normalize_array"),
    "normalize_array_for_compute": (
        "codeintel.core.columnar.normalization",
        "normalize_array_for_compute",
    ),
    "normalize_table": ("codeintel.core.columnar.normalization", "normalize_table"),
    "normalize_table_for_compute": (
        "codeintel.core.columnar.normalization",
        "normalize_table_for_compute",
    ),
    "deep_cast_array": ("codeintel.core.columnar.nested_ops", "deep_cast_array"),
    "deep_cast_table_to_contract": (
        "codeintel.core.columnar.nested_ops",
        "deep_cast_table_to_contract",
    ),
    "make_extras_kv_map": ("codeintel.core.columnar.nested_ops", "make_extras_kv_map"),
    "make_extras_struct": ("codeintel.core.columnar.nested_ops", "make_extras_struct"),
    "unify_schemas_with_contract_first": (
        "codeintel.core.columnar.nested_ops",
        "unify_schemas_with_contract_first",
    ),
    "HashJoinSpec": ("codeintel.core.columnar.acero_ops", "HashJoinSpec"),
    "Plan": ("codeintel.core.columnar.acero_ops", "Plan"),
    "list_external_plan_runners": (
        "codeintel.core.columnar.plan_ops",
        "list_external_plan_runners",
    ),
    "materialize_plan": ("codeintel.core.columnar.plan_ops", "materialize_plan"),
    "register_external_plan_runner": (
        "codeintel.core.columnar.plan_ops",
        "register_external_plan_runner",
    ),
    "run_external_plan": ("codeintel.core.columnar.plan_ops", "run_external_plan"),
    "ColumnarRowBuffer": ("codeintel.core.columnar.rows", "ColumnarRowBuffer"),
    "ColumnarRows": ("codeintel.core.columnar.rows", "ColumnarRows"),
    "columnar_buffer_for_table_key": (
        "codeintel.core.columnar.rows",
        "columnar_buffer_for_table_key",
    ),
    "columnar_row_count": ("codeintel.core.columnar.rows", "columnar_row_count"),
    "align_reader_to_contract": (
        "codeintel.core.columnar.schema_alignment",
        "align_reader_to_contract",
    ),
    "extras_policy_from_schema": (
        "codeintel.core.columnar.schema_alignment",
        "extras_policy_from_schema",
    ),
    "concat_tables_unified": ("codeintel.core.columnar.schema_ops", "concat_tables_unified"),
    "unify_schemas": ("codeintel.core.columnar.schema_ops", "unify_schemas"),
    "ColumnarStream": ("codeintel.core.columnar.stream", "ColumnarStream"),
    "ColumnarStreamAdapter": ("codeintel.core.columnar.stream", "ColumnarStreamAdapter"),
    "LazyFrameStream": ("codeintel.core.columnar.stream", "LazyFrameStream"),
    "RecordBatchReaderStream": ("codeintel.core.columnar.stream", "RecordBatchReaderStream"),
    "coerce_arrow_reader": ("codeintel.core.columnar.stream", "coerce_arrow_reader"),
    "coerce_arrow_table": ("codeintel.core.columnar.stream", "coerce_arrow_table"),
    "is_in_mask": ("codeintel.core.columnar.set_ops", "is_in_mask"),
    "value_set": ("codeintel.core.columnar.set_ops", "value_set"),
}


def __getattr__(name: str) -> object:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(name)
    module_name, attr_name = target
    module = importlib.import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_EXPORTS))


__all__ = (
    "DEFAULT_CAST_SAFE",
    "DEFAULT_SCALAR_AGG",
    "DEFAULT_SCALAR_AGG_ALLOW_NULL",
    "DEFAULT_TAKE",
    "AlignmentReport",
    "ArrowIpcStreamError",
    "ColumnarRowBuffer",
    "ColumnarRows",
    "ColumnarStream",
    "ColumnarStreamAdapter",
    "DedupeDeterminism",
    "DedupeLegacy",
    "DedupeSpec",
    "DedupeStrategy",
    "DedupeTier",
    "E",
    "ExecutionContext",
    "ExecutionPlan",
    "ExplodeResult",
    "ExplodeSpec",
    "ExprVocab",
    "ExternalPlanSpec",
    "FinalizeDedupe",
    "FinalizeInvariant",
    "FinalizeListPolicy",
    "FinalizeMode",
    "FinalizeResult",
    "FinalizeSpec",
    "HashJoinSpec",
    "JoinPrecheckReport",
    "JoinPrecheckSpec",
    "LazyFrameStream",
    "NullListPolicy",
    "Plan",
    "RecordBatchReaderStream",
    "align_reader_to_contract",
    "and_mask",
    "apply_deterministic_order",
    "build_exec_plan",
    "call_compute",
    "case_when",
    "coalesce",
    "coerce_arrow_reader",
    "coerce_arrow_table",
    "columnar_buffer_for_table_key",
    "columnar_row_count",
    "concat_tables_unified",
    "count_distinct",
    "count_non_positive",
    "count_true",
    "dedupe_table_for_table",
    "deep_cast_array",
    "deep_cast_table_to_contract",
    "drain_join_precheck_reports",
    "explode_edges",
    "explode_list_struct",
    "extras_policy_from_schema",
    "fill_null_false",
    "filter_valid",
    "finalize_join_keys",
    "finalize_reader",
    "finalize_reader_batches",
    "finalize_table",
    "group_by_aggregate",
    "hash_struct_goid",
    "hash_struct_ordinal",
    "indices_nonzero",
    "invert_mask",
    "is_in_mask",
    "is_valid_mask",
    "iter_array_values",
    "iter_batches",
    "iter_ipc_stream",
    "iter_rows",
    "join_safe_projection",
    "list_element",
    "list_external_plan_runners",
    "list_payload_columns",
    "list_slice",
    "list_value_length",
    "make_extras_kv_map",
    "make_extras_struct",
    "materialize_plan",
    "normalize_array",
    "normalize_array_for_compute",
    "normalize_table",
    "normalize_table_for_compute",
    "orphan_ref_count",
    "precheck_join_keys",
    "read_ipc_stream",
    "record_join_precheck_errors",
    "regex_match",
    "regex_replace",
    "register_external_plan_runner",
    "replace_with_mask",
    "require_array",
    "require_join_safe_schema",
    "require_scalar",
    "run_external_plan",
    "run_pipeline",
    "safe_cast",
    "safe_divide",
    "stable_sort_indices",
    "stable_sort_table",
    "struct_field",
    "unify_schemas",
    "unify_schemas_with_contract_first",
    "value_set",
    "write_ipc_stream",
)
