"""Explicit TableSchema overrides for non-inferable build outputs."""

from __future__ import annotations

from codeintel.config.datasets.primitives import (
    CREATED_AT_COL,
    CREATED_AT_COL_NULLABLE,
    FUNCTION_ENTITY_COLS,
    FUNCTION_GOID_COL,
    MODULE_ENTITY_COLS,
    REPO_COMMIT_COLS,
    SUBSYSTEM_ENTITY_COLS,
)
from codeintel.core.schemas.primitives import Column, Index, TableSchema, TableWritePolicy
from codeintel.core.schemas.tables.ci_plan_entries import CI_PLAN_ENTRIES_TABLE_SCHEMA

AST_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="ast_nodes",
        columns=[
            Column("path", "VARCHAR", nullable=False, description="Relative path to source file"),
            Column("node_type", "VARCHAR", nullable=False),
            Column("name", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("lineno", "INTEGER"),
            Column("end_lineno", "INTEGER"),
            Column("decorator_start_line", "INTEGER"),
            Column("decorator_end_line", "INTEGER"),
            Column("col_offset", "INTEGER"),
            Column("end_col_offset", "INTEGER"),
            Column("parent_qualname", "VARCHAR"),
            Column("decorators", "JSON"),
            Column("docstring", "VARCHAR"),
            Column("hash", "VARCHAR", nullable=False),
        ],
        primary_key=("hash",),
        description="Flattened AST nodes",
    ),
    TableSchema(
        schema="core",
        name="ast_metrics",
        columns=[
            Column("rel_path", "VARCHAR", nullable=False),
            Column("node_count", "INTEGER", nullable=False),
            Column("function_count", "INTEGER", nullable=False),
            Column("class_count", "INTEGER", nullable=False),
            Column("avg_depth", "DOUBLE", nullable=False),
            Column("max_depth", "INTEGER", nullable=False),
            Column("complexity", "DOUBLE", nullable=False),
            Column("generated_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("rel_path",),
        description="Per-file AST metrics",
    ),
)

CST_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="cst_nodes",
        columns=[
            Column("path", "VARCHAR", nullable=False),
            Column("node_id", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("span", "JSON", nullable=False),
            Column("text_preview", "VARCHAR"),
            Column("parents", "JSON"),
            Column("qnames", "JSON"),
        ],
        primary_key=("node_id",),
        description="Concrete syntax tree nodes",
    ),
)

SYNTAX_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="parse_manifest",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("parse_ok", "BOOLEAN", nullable=False),
            Column("encoding", "VARCHAR"),
            Column("default_indent", "VARCHAR"),
            Column("default_newline", "VARCHAR"),
            Column("has_trailing_newline", "BOOLEAN"),
            Column("future_imports", "JSON"),
            Column("parser_backend", "VARCHAR"),
            Column("libcst_version", "VARCHAR"),
            Column("error_kind", "VARCHAR"),
            Column("error_message", "VARCHAR"),
            Column("error_line", "INTEGER"),
            Column("error_col", "INTEGER"),
            Column("error_snippet", "VARCHAR"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer"),
        write_policy=TableWritePolicy(
            mode="upsert",
            conflict_columns=("repo", "commit", "rel_path", "producer"),
        ),
        description="Per-file parser outcomes and error diagnostics.",
    ),
    TableSchema(
        schema="core",
        name="syntax_nodes",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("node_id", "VARCHAR", nullable=False),
            Column("node_kind", "VARCHAR", nullable=False),
            Column("raw_kind", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("text_preview", "VARCHAR"),
            Column("extras_json", "JSON"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "node_id"),
        description="Canonical syntax node inventory for CPG stitching.",
    ),
    TableSchema(
        schema="core",
        name="syntax_edges",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("parent_node_id", "VARCHAR", nullable=False),
            Column("child_node_id", "VARCHAR", nullable=False),
            Column("edge_kind", "VARCHAR", nullable=False),
            Column("field_name", "VARCHAR"),
            Column("child_ordinal", "INTEGER", nullable=False),
        ],
        primary_key=(
            "repo",
            "commit",
            "rel_path",
            "producer",
            "parent_node_id",
            "child_node_id",
            "edge_kind",
            "child_ordinal",
        ),
        description="Canonical syntax edges for parent/child structure.",
    ),
    TableSchema(
        schema="core",
        name="syntax_scopes",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("scope_id", "VARCHAR", nullable=False),
            Column("scope_kind", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("parent_scope_id", "VARCHAR"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "scope_id"),
        description="Normalized scope tree for syntax facts.",
    ),
    TableSchema(
        schema="core",
        name="syntax_spans",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("span_id", "VARCHAR", nullable=False),
            Column("span_kind", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "span_id"),
        description="Normalized span inventory for syntax facts.",
    ),
    TableSchema(
        schema="core",
        name="syntax_defs",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("def_id", "VARCHAR", nullable=False),
            Column("scope_id", "VARCHAR", nullable=False),
            Column("span_id", "VARCHAR", nullable=False),
            Column("def_kind", "VARCHAR", nullable=False),
            Column("name", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("extras_json", "JSON"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "def_id"),
        description="Definition/binding facts extracted from syntax trees.",
    ),
    TableSchema(
        schema="core",
        name="syntax_refs",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("ref_id", "VARCHAR", nullable=False),
            Column("scope_id", "VARCHAR", nullable=False),
            Column("span_id", "VARCHAR", nullable=False),
            Column("ref_kind", "VARCHAR", nullable=False),
            Column("name", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("extras_json", "JSON"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "ref_id"),
        description="Reference/use facts extracted from syntax trees.",
    ),
    TableSchema(
        schema="core",
        name="syntax_calls",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("call_id", "VARCHAR", nullable=False),
            Column("scope_id", "VARCHAR", nullable=False),
            Column("span_id", "VARCHAR", nullable=False),
            Column("callee_span_id", "VARCHAR"),
            Column("callee_text", "VARCHAR"),
            Column("arg_count", "INTEGER"),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("extras_json", "JSON"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "call_id"),
        description="Callsite facts extracted from syntax trees.",
    ),
    TableSchema(
        schema="core",
        name="syntax_imports",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("import_id", "VARCHAR", nullable=False),
            Column("scope_id", "VARCHAR", nullable=False),
            Column("span_id", "VARCHAR", nullable=False),
            Column("import_kind", "VARCHAR", nullable=False),
            Column("module", "VARCHAR"),
            Column("name", "VARCHAR"),
            Column("alias", "VARCHAR"),
            Column("level", "INTEGER"),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("extras_json", "JSON"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "import_id"),
        description="Import facts extracted from syntax trees.",
    ),
)

SYNTAX_RESOLVED_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="syntax_defs_resolved",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("def_id", "VARCHAR", nullable=False),
            Column("scope_id", "VARCHAR", nullable=False),
            Column("span_id", "VARCHAR", nullable=False),
            Column("def_kind", "VARCHAR", nullable=False),
            Column("name", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("scip_symbol", "VARCHAR"),
            Column("scip_occurrence_id", "VARCHAR"),
            Column("scip_roles", "INTEGER"),
            Column("is_definition", "BOOLEAN"),
            Column("is_reference", "BOOLEAN"),
            Column("is_import", "BOOLEAN"),
            Column("is_write", "BOOLEAN"),
            Column("is_read", "BOOLEAN"),
            Column("goid_h128", "DECIMAL(38,0)"),
            Column("syntax_node_id", "VARCHAR"),
            Column("match_kind", "VARCHAR"),
            Column("candidate_count", "INTEGER"),
            Column("extras_json", "JSON"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "def_id"),
        description="Syntax definitions enriched with SCIP resolution metadata.",
    ),
    TableSchema(
        schema="core",
        name="syntax_refs_resolved",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("ref_id", "VARCHAR", nullable=False),
            Column("scope_id", "VARCHAR", nullable=False),
            Column("span_id", "VARCHAR", nullable=False),
            Column("ref_kind", "VARCHAR", nullable=False),
            Column("name", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("scip_symbol", "VARCHAR"),
            Column("scip_occurrence_id", "VARCHAR"),
            Column("scip_roles", "INTEGER"),
            Column("is_definition", "BOOLEAN"),
            Column("is_reference", "BOOLEAN"),
            Column("is_import", "BOOLEAN"),
            Column("is_write", "BOOLEAN"),
            Column("is_read", "BOOLEAN"),
            Column("goid_h128", "DECIMAL(38,0)"),
            Column("syntax_node_id", "VARCHAR"),
            Column("match_kind", "VARCHAR"),
            Column("candidate_count", "INTEGER"),
            Column("extras_json", "JSON"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "ref_id"),
        description="Syntax references enriched with SCIP resolution metadata.",
    ),
    TableSchema(
        schema="core",
        name="syntax_calls_resolved",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("call_id", "VARCHAR", nullable=False),
            Column("scope_id", "VARCHAR", nullable=False),
            Column("span_id", "VARCHAR", nullable=False),
            Column("callee_span_id", "VARCHAR"),
            Column("callee_text", "VARCHAR"),
            Column("arg_count", "INTEGER"),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("scip_symbol", "VARCHAR"),
            Column("scip_occurrence_id", "VARCHAR"),
            Column("scip_roles", "INTEGER"),
            Column("is_definition", "BOOLEAN"),
            Column("is_reference", "BOOLEAN"),
            Column("is_import", "BOOLEAN"),
            Column("is_write", "BOOLEAN"),
            Column("is_read", "BOOLEAN"),
            Column("goid_h128", "DECIMAL(38,0)"),
            Column("syntax_node_id", "VARCHAR"),
            Column("match_kind", "VARCHAR"),
            Column("candidate_count", "INTEGER"),
            Column("extras_json", "JSON"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "call_id"),
        description="Syntax callsites enriched with SCIP resolution metadata.",
    ),
    TableSchema(
        schema="core",
        name="syntax_imports_resolved",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("import_id", "VARCHAR", nullable=False),
            Column("scope_id", "VARCHAR", nullable=False),
            Column("span_id", "VARCHAR", nullable=False),
            Column("import_kind", "VARCHAR", nullable=False),
            Column("module", "VARCHAR"),
            Column("name", "VARCHAR"),
            Column("alias", "VARCHAR"),
            Column("level", "INTEGER"),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("scip_symbol", "VARCHAR"),
            Column("scip_occurrence_id", "VARCHAR"),
            Column("scip_roles", "INTEGER"),
            Column("is_definition", "BOOLEAN"),
            Column("is_reference", "BOOLEAN"),
            Column("is_import", "BOOLEAN"),
            Column("is_write", "BOOLEAN"),
            Column("is_read", "BOOLEAN"),
            Column("goid_h128", "DECIMAL(38,0)"),
            Column("syntax_node_id", "VARCHAR"),
            Column("match_kind", "VARCHAR"),
            Column("candidate_count", "INTEGER"),
            Column("extras_json", "JSON"),
        ],
        primary_key=("repo", "commit", "rel_path", "producer", "import_id"),
        description="Syntax imports enriched with SCIP resolution metadata.",
    ),
)

TREE_SITTER_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="ts_captures",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("query_pack", "VARCHAR", nullable=False),
            Column("capture_name", "VARCHAR", nullable=False),
            Column("start_byte", "BIGINT", nullable=False),
            Column("end_byte", "BIGINT", nullable=False),
            Column("start_row", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_row", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("node_type", "VARCHAR", nullable=False),
            Column("text_preview", "VARCHAR"),
            Column("extras", "JSON"),
        ],
        primary_key=(
            "repo",
            "commit",
            "rel_path",
            "language",
            "query_pack",
            "capture_name",
            "start_byte",
            "end_byte",
            "node_type",
        ),
        indexes=(
            Index("idx_core_ts_captures_path", ("rel_path",)),
            Index("idx_core_ts_captures_capture", ("capture_name",)),
        ),
        description="Tree-sitter query captures emitted by language packs.",
    ),
    TableSchema(
        schema="core",
        name="ts_parse_errors",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("error_type", "VARCHAR", nullable=False),
            Column("message", "VARCHAR"),
            Column("start_byte", "BIGINT", nullable=False),
            Column("end_byte", "BIGINT", nullable=False),
            Column("start_row", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_row", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("text_preview", "VARCHAR"),
        ],
        primary_key=(
            "repo",
            "commit",
            "rel_path",
            "language",
            "start_byte",
            "end_byte",
            "error_type",
        ),
        indexes=(Index("idx_core_ts_parse_errors_path", ("rel_path",)),),
        description="Tree-sitter parse errors and missing nodes.",
    ),
)

CI_PLAN_OVERRIDE_TABLES: tuple[TableSchema, ...] = (CI_PLAN_ENTRIES_TABLE_SCHEMA,)

DOCSTRINGS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="docstrings",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("lineno", "INTEGER"),
            Column("end_lineno", "INTEGER"),
            Column("raw_docstring", "VARCHAR"),
            Column("style", "VARCHAR"),
            Column("short_desc", "VARCHAR"),
            Column("long_desc", "VARCHAR"),
            Column("params", "JSON"),
            Column("returns", "JSON"),
            Column("raises", "JSON"),
            Column("examples", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        description="Structured docstring facts extracted with griffe",
    ),
)

MODULES_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="modules",
        columns=[
            Column("module", "VARCHAR", nullable=False),
            Column("path", "VARCHAR", nullable=False),
            Column("repo", "VARCHAR"),
            Column("commit", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("tags", "JSON"),
            Column("owners", "JSON"),
            Column("row_hash", "VARCHAR"),
        ],
        primary_key=("module", "path"),
        indexes=(
            Index("idx_core_modules_path", ("path",)),
            Index("idx_core_modules_module", ("module",)),
        ),
        write_policy=TableWritePolicy(
            mode="upsert",
            conflict_columns=("module", "path"),
            update_columns=("repo", "commit", "language", "tags", "owners", "row_hash"),
            hash_column="row_hash",
            use_staging=True,
        ),
        description="Discovered modules per repo/commit",
    ),
    TableSchema(
        schema="core",
        name="file_state",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("size_bytes", "BIGINT", nullable=False),
            Column("mtime_ns", "BIGINT", nullable=False),
            Column("content_hash", "VARCHAR", nullable=False),
        ],
        primary_key=("repo", "rel_path", "language"),
        indexes=(
            Index("idx_core_file_state_path", ("rel_path",)),
            Index("idx_core_file_state_repo_commit", ("repo", "commit")),
        ),
        description="Per-commit file digests used for incremental ingestion",
    ),
    TableSchema(
        schema="core",
        name="repo_map",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("modules", "JSON"),
            Column("overlays", "JSON"),
            Column("generated_at", "TIMESTAMP"),
        ],
        primary_key=("repo", "commit"),
        description="Per-commit module manifest and overlays",
    ),
)

FILE_LINE_INDEX_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="file_line_index",
        columns=[
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("line", "INTEGER", nullable=False),
            Column("start_byte", "BIGINT", nullable=False),
            Column("end_byte", "BIGINT", nullable=False),
            Column("encoding", "VARCHAR", nullable=False),
        ],
        primary_key=("repo", "commit", "rel_path", "line"),
        indexes=(Index("idx_core_file_line_index_path", ("rel_path",)),),
        description="Line-level byte offsets for each source file.",
    ),
)

EXAMPLE_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="hello_example",
        columns=[
            Column("message", "VARCHAR", nullable=False),
            Column("value", "INTEGER", nullable=False),
        ],
        description="Example analytics output for local dev targets.",
    ),
)

GOIDS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="goids",
        columns=[
            Column("goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("urn", "VARCHAR", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER"),
            Column("end_line", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("goid_h128",),
        indexes=(
            Index("idx_core_goids_h128", ("goid_h128",), unique=True),
            Index("idx_core_goids_urn", ("urn",), unique=True),
            Index("idx_core_goids_path", ("rel_path",)),
        ),
        description="Global object identifiers for code entities",
    ),
    TableSchema(
        schema="core",
        name="goid_crosswalk",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("goid", "VARCHAR", nullable=False),
            Column("lang", "VARCHAR", nullable=False),
            Column("module_path", "VARCHAR", nullable=False),
            Column("file_path", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER"),
            Column("end_line", "INTEGER"),
            Column("scip_symbol", "VARCHAR"),
            Column("ast_qualname", "VARCHAR"),
            Column("cst_node_id", "VARCHAR"),
            Column("chunk_id", "VARCHAR"),
            Column("symbol_id", "VARCHAR"),
            Column("updated_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "goid"),
        indexes=(Index("idx_core_gcw_goid", ("goid",)),),
        description="Crosswalk from GOIDs to language-specific symbols/paths",
    ),
)

SCHEMA_INFERENCE_ERRORS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="schema_inference_errors",
        columns=[
            Column("table_key", "VARCHAR", nullable=False),
            *REPO_COMMIT_COLS,
            Column("error", "VARCHAR", nullable=False),
            Column("occurred_at", "TIMESTAMP", nullable=False),
            Column("run_id", "VARCHAR", nullable=False),
        ],
        primary_key=("table_key", "repo", "commit", "run_id"),
        indexes=(
            Index("idx_core_schema_inference_errors_table_key", ("table_key",)),
            Index("idx_core_schema_inference_errors_run_id", ("run_id",)),
        ),
        description="Schema inference failures recorded during schema compile.",
    ),
)

SCIP_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="scip_symbols",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("symbol", "VARCHAR", nullable=False),
            Column("documentation", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "rel_path", "symbol"),
        indexes=(Index("idx_core_scip_symbols_symbol", ("symbol",)),),
        description="SCIP symbol definitions",
    ),
    TableSchema(
        schema="core",
        name="scip_occurrences",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("symbol", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("roles", "INTEGER", nullable=False),
            Column("position_encoding", "INTEGER"),
            Column("text_document_encoding", "VARCHAR"),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "rel_path", "symbol", "start_line", "start_col"),
        indexes=(
            Index("idx_core_scip_occ_symbol", ("symbol",)),
            Index("idx_core_scip_occ_path", ("rel_path",)),
        ),
        description="SCIP symbol occurrences (definitions and references)",
    ),
    TableSchema(
        schema="core",
        name="scip_symbol_information",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("symbol", "VARCHAR", nullable=False),
            Column("documentation", "VARCHAR"),
            Column("kind", "INTEGER"),
            Column("display_name", "VARCHAR"),
            Column("signature", "VARCHAR"),
            Column("enclosing_symbol", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "symbol"),
        indexes=(Index("idx_core_scip_symbol_info_symbol", ("symbol",)),),
        description="SCIP symbol metadata and documentation",
    ),
    TableSchema(
        schema="core",
        name="scip_symbol_relationships",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("symbol", "VARCHAR", nullable=False),
            Column("related_symbol", "VARCHAR", nullable=False),
            Column("relationship_kind", "VARCHAR", nullable=False),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "symbol", "related_symbol", "relationship_kind"),
        indexes=(Index("idx_core_scip_rel_symbol", ("symbol",)),),
        description="SCIP symbol relationship edges",
    ),
    TableSchema(
        schema="core",
        name="scip_diagnostics",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("position_encoding", "INTEGER"),
            Column("text_document_encoding", "VARCHAR"),
            Column("severity", "VARCHAR", nullable=False),
            Column("code", "VARCHAR"),
            Column("message", "VARCHAR", nullable=False),
            Column("source", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=(
            "repo",
            "commit",
            "rel_path",
            "start_line",
            "start_col",
            "message",
        ),
        indexes=(Index("idx_core_scip_diag_path", ("rel_path",)),),
        description="Diagnostics emitted during SCIP indexing",
    ),
    TableSchema(
        schema="core",
        name="scip_external_symbols",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("symbol", "VARCHAR", nullable=False),
            Column("package_manager", "VARCHAR"),
            Column("package_name", "VARCHAR"),
            Column("package_version", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "symbol"),
        indexes=(Index("idx_core_scip_external_symbol", ("symbol",)),),
        description="External SCIP symbols referenced by the index",
    ),
    TableSchema(
        schema="core",
        name="scip_module_state",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("content_hash", "VARCHAR", nullable=False),
            Column("options_hash", "VARCHAR"),
            Column("tool_version", "VARCHAR"),
            Column("shard_path", "VARCHAR", nullable=False),
            Column("updated_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "rel_path"),
        indexes=(
            Index("idx_core_scip_module_state_path", ("rel_path",)),
            Index("idx_core_scip_module_state_repo_commit", ("repo", "commit")),
        ),
        description="Per-module SCIP shard state for incremental updates",
    ),
)

SCIP_RESOLUTION_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="core",
        name="scip_symbol_goid_xref",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("scip_symbol", "VARCHAR", nullable=False),
            Column("goid_h128", "DECIMAL(38,0)"),
            Column("def_rel_path", "VARCHAR"),
            Column("def_start_line", "INTEGER"),
            Column("def_start_col", "INTEGER"),
            Column("def_end_line", "INTEGER"),
            Column("def_end_col", "INTEGER"),
            Column("position_encoding", "INTEGER"),
            Column("text_document_encoding", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "scip_symbol"),
        indexes=(
            Index("idx_core_scip_symbol_goid_xref_symbol", ("scip_symbol",)),
            Index("idx_core_scip_symbol_goid_xref_goid", ("goid_h128",)),
        ),
        description="SCIP symbol to GOID mapping derived from definition occurrences.",
    ),
    TableSchema(
        schema="core",
        name="scip_occurrence_span_xref",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("scip_symbol", "VARCHAR", nullable=False),
            Column("roles", "INTEGER", nullable=False),
            Column("is_definition", "BOOLEAN", nullable=False),
            Column("is_reference", "BOOLEAN", nullable=False),
            Column("is_import", "BOOLEAN", nullable=False),
            Column("is_write", "BOOLEAN", nullable=False),
            Column("is_read", "BOOLEAN", nullable=False),
            Column("enclosing_symbol", "VARCHAR"),
            Column("start_line", "INTEGER", nullable=False),
            Column("start_col", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("end_col", "INTEGER", nullable=False),
            Column("position_encoding", "INTEGER"),
            Column("text_document_encoding", "VARCHAR"),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("goid_h128", "DECIMAL(38,0)"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=(
            "repo",
            "commit",
            "rel_path",
            "scip_symbol",
            "start_line",
            "start_col",
            "end_line",
            "end_col",
        ),
        indexes=(
            Index("idx_core_scip_occ_span_symbol", ("scip_symbol",)),
            Index("idx_core_scip_occ_span_path", ("rel_path",)),
            Index("idx_core_scip_occ_span_goid", ("goid_h128",)),
        ),
        description="SCIP occurrence span join keys with GOID and role metadata.",
    ),
    TableSchema(
        schema="core",
        name="scip_occurrence_syntax_xref",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("producer", "VARCHAR", nullable=False),
            Column("scip_symbol", "VARCHAR", nullable=False),
            Column("scip_occurrence_id", "VARCHAR", nullable=False),
            Column("occ_start_byte", "BIGINT"),
            Column("occ_end_byte", "BIGINT"),
            Column("occ_start_line", "INTEGER", nullable=False),
            Column("occ_start_col", "INTEGER", nullable=False),
            Column("occ_end_line", "INTEGER", nullable=False),
            Column("occ_end_col", "INTEGER", nullable=False),
            Column("syntax_node_id", "VARCHAR"),
            Column("match_kind", "VARCHAR", nullable=False),
            Column("candidate_count", "INTEGER", nullable=False),
        ],
        primary_key=(
            "repo",
            "commit",
            "rel_path",
            "producer",
            "scip_occurrence_id",
        ),
        indexes=(Index("idx_core_scip_occ_syntax_symbol", ("scip_symbol",)),),
        description="SCIP occurrence to syntax-node weld table.",
    ),
)

TYPING_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="static_diagnostics",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("pyrefly_errors", "INTEGER", nullable=False),
            Column("pyright_errors", "INTEGER", nullable=False),
            Column("ruff_errors", "INTEGER", nullable=False),
            Column("total_errors", "INTEGER", nullable=False),
            Column("has_errors", "BOOLEAN", nullable=False),
        ],
        primary_key=("repo", "commit", "rel_path"),
        description="Per-file static diagnostic counts",
    ),
)

CONFIG_INGEST_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="config_values",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("config_path", "VARCHAR", nullable=False),
            Column("format", "VARCHAR", nullable=False),
            Column("key", "VARCHAR", nullable=False),
            Column("reference_paths", "JSON"),
            Column("reference_modules", "JSON"),
            Column("reference_count", "INTEGER", nullable=False),
        ],
        primary_key=("repo", "commit", "config_path", "key"),
        description="Flattened config key/value paths",
    ),
)

TESTS_INGEST_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="test_catalog",
        columns=[
            Column("test_id", "VARCHAR", nullable=False),
            Column("test_goid_h128", "DOUBLE"),
            Column("urn", "VARCHAR"),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR"),
            Column("kind", "VARCHAR"),
            Column("status", "VARCHAR"),
            Column("duration_ms", "DOUBLE"),
            Column("markers", "JSON"),
            Column("parametrized", "BOOLEAN"),
            Column("flaky", "BOOLEAN"),
            Column("created_at", "TIMESTAMP"),
        ],
        primary_key=("test_id",),
        indexes=(Index("idx_analytics_test_catalog_id", ("test_id",), unique=True),),
        description="Pytest test catalog",
    ),
)

CALL_GRAPH_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="graph",
        name="call_graph_nodes",
        columns=[
            Column("goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("arity", "INTEGER", nullable=False),
            Column("is_public", "BOOLEAN", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
        ],
        primary_key=("goid_h128",),
        description="Functions and methods participating in the call graph",
    ),
    TableSchema(
        schema="graph",
        name="call_graph_edges",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("caller_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("callee_goid_h128", "DECIMAL(38,0)"),
            Column("callsite_path", "VARCHAR", nullable=False),
            Column("callsite_line", "INTEGER", nullable=False),
            Column("callsite_col", "INTEGER", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("resolved_via", "VARCHAR"),
            Column("confidence", "DOUBLE"),
            Column("evidence_json", "JSON"),
        ],
        indexes=(
            Index("idx_graph_call_edges_repo_commit", ("repo", "commit")),
            Index("idx_graph_call_edges_caller", ("caller_goid_h128",)),
            Index("idx_graph_call_edges_callee", ("callee_goid_h128",)),
        ),
        description="Caller->callee edges with callsite evidence",
    ),
)

CFG_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="graph",
        name="cfg_blocks",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("block_idx", "INTEGER", nullable=False),
            Column("block_id", "VARCHAR", nullable=False),
            Column("label", "VARCHAR", nullable=False),
            Column("file_path", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("stmts_json", "JSON", nullable=False),
            Column("in_degree", "INTEGER", nullable=False),
            Column("out_degree", "INTEGER", nullable=False),
        ],
        primary_key=("function_goid_h128", "block_idx"),
        indexes=(Index("idx_graph_cfg_blocks_fn", ("function_goid_h128",)),),
        description="Control-flow blocks per function",
    ),
    TableSchema(
        schema="graph",
        name="cfg_edges",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("src_block_id", "VARCHAR", nullable=False),
            Column("dst_block_id", "VARCHAR", nullable=False),
            Column("edge_kind", "VARCHAR"),
        ],
        indexes=(Index("idx_graph_cfg_edges_fn", ("function_goid_h128",)),),
        description="Control-flow edges between blocks",
    ),
)

DFG_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="graph",
        name="dfg_edges",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("src_block_id", "VARCHAR", nullable=False),
            Column("dst_block_id", "VARCHAR", nullable=False),
            Column("src_var", "VARCHAR"),
            Column("dst_var", "VARCHAR"),
            Column("edge_kind", "VARCHAR"),
            Column("via_phi", "BOOLEAN"),
            Column("use_kind", "VARCHAR"),
        ],
        indexes=(Index("idx_graph_dfg_edges_fn", ("function_goid_h128",)),),
        description="Data-flow edges between blocks/vars",
    ),
)

IMPORT_GRAPH_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="graph",
        name="import_modules",
        columns=[
            *MODULE_ENTITY_COLS,
            Column("scc_id", "INTEGER", nullable=False),
            Column("component_size", "INTEGER", nullable=False),
            Column("layer", "INTEGER"),
            Column("cycle_group", "INTEGER", nullable=False),
        ],
        indexes=(
            Index("idx_graph_import_modules_repo_commit", ("repo", "commit")),
            Index("idx_graph_import_modules_module", ("module",)),
        ),
        description="Per-module import graph condensation metadata keyed by repo/commit",
    ),
    TableSchema(
        schema="graph",
        name="import_graph_edges",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("src_module", "VARCHAR", nullable=False),
            Column("dst_module", "VARCHAR", nullable=False),
            Column("src_fan_out", "INTEGER", nullable=False),
            Column("dst_fan_in", "INTEGER", nullable=False),
            Column("cycle_group", "INTEGER", nullable=False),
            Column("module_layer", "INTEGER"),
        ],
        indexes=(
            Index("idx_graph_import_edges_repo_commit", ("repo", "commit")),
            Index("idx_graph_import_edges_src", ("src_module",)),
            Index("idx_graph_import_edges_dst", ("dst_module",)),
        ),
        description="Module-level import edges with fan-in/out metrics",
    ),
)

SYMBOL_USES_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="graph",
        name="symbol_use_edges",
        columns=[
            Column("symbol", "VARCHAR", nullable=False),
            Column("def_path", "VARCHAR", nullable=False),
            Column("use_path", "VARCHAR", nullable=False),
            Column("same_file", "BOOLEAN", nullable=False),
            Column("same_module", "BOOLEAN", nullable=False),
            Column("def_goid_h128", "DECIMAL(38,0)"),
            Column("use_goid_h128", "DECIMAL(38,0)"),
        ],
        primary_key=("symbol", "def_path", "use_path"),
        indexes=(Index("idx_graph_symbol_use_symbol", ("symbol",)),),
        description="Definition-to-use edges derived from SCIP",
    ),
)

CPG_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="graph",
        name="cpg_nodes",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("cpg_node_id", "DECIMAL(38,0)", nullable=False),
            Column("node_kind", "VARCHAR", nullable=False),
            Column("source_table_key", "VARCHAR", nullable=False),
            Column("source_pk_json", "JSON", nullable=False),
            Column("rel_path", "VARCHAR"),
            Column("start_byte", "BIGINT"),
            Column("end_byte", "BIGINT"),
            Column("extras_json", "JSON"),
        ],
        primary_key=("repo", "commit", "cpg_node_id"),
        indexes=(Index("idx_graph_cpg_nodes_kind", ("node_kind",)),),
        description="Unified CPG node inventory with source table pointers.",
    ),
    TableSchema(
        schema="graph",
        name="cpg_edges",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("src_cpg_node_id", "DECIMAL(38,0)", nullable=False),
            Column("dst_cpg_node_id", "DECIMAL(38,0)", nullable=False),
            Column("edge_kind", "VARCHAR", nullable=False),
            Column("edge_layer", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR"),
            Column("ordinal", "INTEGER", nullable=False),
            Column("extras_json", "JSON"),
        ],
        primary_key=(
            "repo",
            "commit",
            "src_cpg_node_id",
            "dst_cpg_node_id",
            "edge_kind",
            "edge_layer",
            "ordinal",
        ),
        indexes=(
            Index("idx_graph_cpg_edges_src", ("src_cpg_node_id",)),
            Index("idx_graph_cpg_edges_dst", ("dst_cpg_node_id",)),
            Index("idx_graph_cpg_edges_kind", ("edge_kind",)),
        ),
        description="Unified CPG edge inventory across syntax, symbol, and flow layers.",
    ),
)

ENTRYPOINTS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="entrypoints",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("entrypoint_id", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("framework", "VARCHAR"),
            Column("handler_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("handler_urn", "VARCHAR", nullable=False),
            Column("handler_rel_path", "VARCHAR", nullable=False),
            Column("handler_module", "VARCHAR", nullable=False),
            Column("handler_qualname", "VARCHAR", nullable=False),
            Column("http_method", "VARCHAR"),
            Column("route_path", "VARCHAR"),
            Column("status_codes", "JSON"),
            Column("auth_required", "BOOLEAN"),
            Column("command_name", "VARCHAR"),
            Column("arguments_schema", "JSON"),
            Column("schedule", "VARCHAR"),
            Column("trigger", "VARCHAR"),
            Column("extra", "JSON"),
            Column("subsystem_id", "VARCHAR"),
            Column("subsystem_name", "VARCHAR"),
            Column("tags", "JSON"),
            Column("owners", "JSON"),
            Column("tests_touching", "INTEGER"),
            Column("failing_tests", "INTEGER"),
            Column("slow_tests", "INTEGER"),
            Column("flaky_tests", "INTEGER"),
            Column("last_test_status", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "entrypoint_id"),
        description="External entrypoints mapped to handlers, subsystems, and tests",
    ),
    TableSchema(
        schema="analytics",
        name="entrypoint_tests",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("entrypoint_id", "VARCHAR", nullable=False),
            Column("test_id", "VARCHAR", nullable=False),
            Column("test_goid_h128", "DECIMAL(38,0)"),
            Column("status", "VARCHAR"),
            Column("duration_ms", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "entrypoint_id", "test_id"),
        description="Bipartite edges between entrypoints and tests",
    ),
)

EXTERNAL_DEPS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="external_dependencies",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("dep_id", "VARCHAR", nullable=False),
            Column("library", "VARCHAR", nullable=False),
            Column("service_name", "VARCHAR"),
            Column("category", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("severity", "VARCHAR"),
            Column("criticality", "DOUBLE"),
            Column("risk_score", "DOUBLE"),
            Column("function_count", "INTEGER", nullable=False),
            Column("callsite_count", "INTEGER", nullable=False),
            Column("modules_json", "JSON", nullable=False),
            Column("usage_modes", "JSON", nullable=False),
            Column("config_keys", "JSON"),
            Column("risk_level", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "dep_id"),
        description="Aggregated view of external libraries/services used by the repo",
    ),
    TableSchema(
        schema="analytics",
        name="external_dependency_calls",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("dep_id", "VARCHAR", nullable=False),
            Column("library", "VARCHAR", nullable=False),
            Column("service_name", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("severity", "VARCHAR"),
            Column("criticality", "DOUBLE"),
            Column("risk_score", "DOUBLE"),
            Column("matched_pattern", "VARCHAR"),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("function_urn", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR", nullable=False),
            Column("callsite_count", "INTEGER", nullable=False),
            Column("modes", "JSON", nullable=False),
            Column("evidence_json", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "dep_id", "function_goid_h128"),
        description="Function-level callsites into external dependencies with modes and evidence",
    ),
)

CONFIG_DATA_FLOW_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="config_data_flow",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("config_key", "VARCHAR", nullable=False),
            Column("config_path", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("usage_kind", "VARCHAR", nullable=False),
            Column("evidence_json", "JSON"),
            Column("call_chain_id", "VARCHAR", nullable=False),
            Column("call_chain_json", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=(
            "repo",
            "commit",
            "config_key",
            "config_path",
            "function_goid_h128",
            "usage_kind",
            "call_chain_id",
        ),
        description="Function-level config key usage and call-chain context from entrypoints.",
    ),
    TableSchema(
        schema="analytics",
        name="config_graph_metrics_keys",
        columns=[
            *REPO_COMMIT_COLS,
            Column("config_key", "VARCHAR", nullable=False),
            Column("degree", "INTEGER"),
            Column("weighted_degree", "DOUBLE"),
            Column("betweenness", "DOUBLE"),
            Column("closeness", "DOUBLE"),
            Column("community_id", "INTEGER"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "config_key"),
        description="Metrics for config keys in config-module bipartite/projection graphs",
    ),
    TableSchema(
        schema="analytics",
        name="config_graph_metrics_modules",
        columns=[
            *MODULE_ENTITY_COLS,
            Column("degree", "INTEGER"),
            Column("weighted_degree", "DOUBLE"),
            Column("betweenness", "DOUBLE"),
            Column("closeness", "DOUBLE"),
            Column("community_id", "INTEGER"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "module"),
        description="Metrics for modules in config-module bipartite/projection graphs",
    ),
    TableSchema(
        schema="analytics",
        name="config_projection_key_edges",
        columns=[
            *REPO_COMMIT_COLS,
            Column("src_key", "VARCHAR", nullable=False),
            Column("dst_key", "VARCHAR", nullable=False),
            Column("weight", "DOUBLE"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "src_key", "dst_key"),
        description="Projected key-key edges from shared module usage",
    ),
    TableSchema(
        schema="analytics",
        name="config_projection_module_edges",
        columns=[
            *REPO_COMMIT_COLS,
            Column("src_module", "VARCHAR", nullable=False),
            Column("dst_module", "VARCHAR", nullable=False),
            Column("weight", "DOUBLE"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "src_module", "dst_module"),
        description="Projected module-module edges from shared config keys",
    ),
)

CFG_DFG_METRICS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="cfg_function_metrics",
        columns=[
            *FUNCTION_GOID_COL,
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("module", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("cfg_block_count", "INTEGER"),
            Column("cfg_edge_count", "INTEGER"),
            Column("cfg_has_cycles", "BOOLEAN"),
            Column("cfg_scc_count", "INTEGER"),
            Column("cfg_longest_path_len", "INTEGER"),
            Column("cfg_avg_shortest_path_len", "DOUBLE"),
            Column("cfg_branching_factor_mean", "DOUBLE"),
            Column("cfg_branching_factor_max", "INTEGER"),
            Column("cfg_linear_block_fraction", "DOUBLE"),
            Column("cfg_dom_tree_height", "INTEGER"),
            Column("cfg_dominance_frontier_size_mean", "DOUBLE"),
            Column("cfg_dominance_frontier_size_max", "INTEGER"),
            Column("cfg_loop_count", "INTEGER"),
            Column("cfg_loop_nesting_depth_max", "INTEGER"),
            Column("cfg_bc_betweenness_max", "DOUBLE"),
            Column("cfg_bc_betweenness_mean", "DOUBLE"),
            Column("cfg_bc_closeness_mean", "DOUBLE"),
            Column("cfg_bc_eigenvector_max", "DOUBLE"),
            *CREATED_AT_COL,
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_cfg_fn_goid", ("function_goid_h128",)),),
        description="Control-flow graph summary metrics per function",
    ),
    TableSchema(
        schema="analytics",
        name="cfg_block_metrics",
        columns=[
            *FUNCTION_GOID_COL,
            *REPO_COMMIT_COLS,
            Column("block_idx", "INTEGER", nullable=False),
            Column("is_entry", "BOOLEAN"),
            Column("is_exit", "BOOLEAN"),
            Column("is_branch", "BOOLEAN"),
            Column("is_join", "BOOLEAN"),
            Column("dom_depth", "INTEGER"),
            Column("dominates_exit", "BOOLEAN"),
            Column("bc_betweenness", "DOUBLE"),
            Column("bc_closeness", "DOUBLE"),
            Column("bc_eigenvector", "DOUBLE"),
            Column("in_loop_scc", "BOOLEAN"),
            Column("loop_header", "BOOLEAN"),
            Column("loop_nesting_depth", "INTEGER"),
            *CREATED_AT_COL,
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128", "block_idx"),
        indexes=(Index("idx_analytics_cfg_block_fn", ("function_goid_h128",)),),
        description="Control-flow graph block-level metrics per function",
    ),
    TableSchema(
        schema="analytics",
        name="cfg_function_metrics_ext",
        columns=[
            *FUNCTION_GOID_COL,
            *REPO_COMMIT_COLS,
            Column("unreachable_block_count", "INTEGER"),
            Column("loop_header_count", "INTEGER"),
            Column("true_edge_count", "INTEGER"),
            Column("false_edge_count", "INTEGER"),
            Column("back_edge_count", "INTEGER"),
            Column("exception_edge_count", "INTEGER"),
            Column("fallthrough_edge_count", "INTEGER"),
            Column("loop_edge_count", "INTEGER"),
            Column("entry_exit_simple_paths", "INTEGER"),
            *CREATED_AT_COL,
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_cfg_fn_ext_goid", ("function_goid_h128",)),),
        description="Extended control-flow graph metrics per function",
    ),
    TableSchema(
        schema="analytics",
        name="dfg_function_metrics",
        columns=[
            *FUNCTION_GOID_COL,
            *REPO_COMMIT_COLS,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("module", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("dfg_block_count", "INTEGER"),
            Column("dfg_edge_count", "INTEGER"),
            Column("dfg_phi_edge_count", "INTEGER"),
            Column("dfg_symbol_count", "INTEGER"),
            Column("dfg_component_count", "INTEGER"),
            Column("dfg_scc_count", "INTEGER"),
            Column("dfg_has_cycles", "BOOLEAN"),
            Column("dfg_longest_chain_len", "INTEGER"),
            Column("dfg_avg_shortest_path_len", "DOUBLE"),
            Column("dfg_avg_in_degree", "DOUBLE"),
            Column("dfg_avg_out_degree", "DOUBLE"),
            Column("dfg_max_in_degree", "INTEGER"),
            Column("dfg_max_out_degree", "INTEGER"),
            Column("dfg_branchy_block_fraction", "DOUBLE"),
            Column("dfg_bc_betweenness_max", "DOUBLE"),
            Column("dfg_bc_betweenness_mean", "DOUBLE"),
            Column("dfg_bc_eigenvector_max", "DOUBLE"),
            *CREATED_AT_COL,
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_dfg_fn_goid", ("function_goid_h128",)),),
        description="Data-flow graph summary metrics per function",
    ),
    TableSchema(
        schema="analytics",
        name="dfg_block_metrics",
        columns=[
            *FUNCTION_GOID_COL,
            *REPO_COMMIT_COLS,
            Column("block_idx", "INTEGER", nullable=False),
            Column("dfg_in_degree", "INTEGER"),
            Column("dfg_out_degree", "INTEGER"),
            Column("dfg_phi_in_degree", "INTEGER"),
            Column("dfg_phi_out_degree", "INTEGER"),
            Column("dfg_bc_betweenness", "DOUBLE"),
            Column("dfg_bc_closeness", "DOUBLE"),
            Column("dfg_bc_eigenvector", "DOUBLE"),
            Column("dfg_in_chain", "BOOLEAN"),
            Column("dfg_in_scc", "BOOLEAN"),
            *CREATED_AT_COL,
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128", "block_idx"),
        indexes=(Index("idx_analytics_dfg_block_fn", ("function_goid_h128",)),),
        description="Data-flow graph block-level metrics per function",
    ),
    TableSchema(
        schema="analytics",
        name="dfg_function_metrics_ext",
        columns=[
            *FUNCTION_GOID_COL,
            *REPO_COMMIT_COLS,
            Column("data_flow_edge_count", "INTEGER"),
            Column("intra_block_edge_count", "INTEGER"),
            Column("use_kind_phi_count", "INTEGER"),
            Column("use_kind_data_flow_count", "INTEGER"),
            Column("use_kind_intra_block_count", "INTEGER"),
            Column("use_kind_other_count", "INTEGER"),
            Column("phi_edge_ratio", "DOUBLE"),
            Column("entry_exit_simple_paths", "INTEGER"),
            *CREATED_AT_COL,
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_dfg_fn_ext_goid", ("function_goid_h128",)),),
        description="Extended data-flow graph metrics per function",
    ),
)

FUNCTION_ANALYTICS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="function_types",
        columns=[
            *FUNCTION_ENTITY_COLS,
            Column("total_params", "INTEGER"),
            Column("return_type", "VARCHAR"),
            Column("type_comment", "VARCHAR"),
            Column("param_types", "JSON"),
            *CREATED_AT_COL_NULLABLE,
        ],
        indexes=(Index("idx_analytics_function_types_goid", ("function_goid_h128",)),),
        description="Per-function parameter and return type annotations",
    ),
    TableSchema(
        schema="analytics",
        name="function_validation",
        columns=[
            *REPO_COMMIT_COLS,
            *FUNCTION_GOID_COL,
            Column("rel_path", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR", nullable=False),
            Column("issue", "VARCHAR", nullable=False),
            Column("detail", "VARCHAR", nullable=False),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "function_goid_h128", "issue"),
        indexes=(Index("idx_function_validation_repo_commit", ("repo", "commit")),),
        description="Validation findings for function analytics gaps",
    ),
)

FUNCTION_EFFECTS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="function_effects",
        columns=[
            *REPO_COMMIT_COLS,
            *FUNCTION_GOID_COL,
            Column("is_pure", "BOOLEAN", nullable=False),
            Column("uses_io", "BOOLEAN", nullable=False),
            Column("touches_db", "BOOLEAN", nullable=False),
            Column("uses_time", "BOOLEAN", nullable=False),
            Column("uses_randomness", "BOOLEAN", nullable=False),
            Column("modifies_globals", "BOOLEAN", nullable=False),
            Column("modifies_closure", "BOOLEAN", nullable=False),
            Column("spawns_threads_or_tasks", "BOOLEAN", nullable=False),
            Column("has_transitive_effects", "BOOLEAN", nullable=False),
            Column("purity_confidence", "DOUBLE"),
            Column("effects_json", "JSON"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_function_effects_goid", ("function_goid_h128",)),),
        description="Side-effect and purity classification per function GOID",
    ),
)

FUNCTION_CONTRACTS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="function_contracts",
        columns=[
            *REPO_COMMIT_COLS,
            *FUNCTION_GOID_COL,
            Column("preconditions_json", "JSON"),
            Column("postconditions_json", "JSON"),
            Column("raises_json", "JSON"),
            Column("param_nullability_json", "JSON"),
            Column("return_nullability", "VARCHAR"),
            Column("contract_confidence", "DOUBLE"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_function_contracts_goid", ("function_goid_h128",)),),
        description="Inferred pre/postconditions and nullability per function",
    ),
)

DATA_MODELS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="data_models",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("model_id", "VARCHAR", nullable=False),
            Column("goid_h128", "DECIMAL(38,0)"),
            Column("model_name", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("model_kind", "VARCHAR", nullable=False),
            Column("base_classes_json", "JSON"),
            Column("doc_short", "VARCHAR"),
            Column("doc_long", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "model_id"),
        description="Extracted data models (dataclasses, Pydantic, TypedDicts, ORMs)",
    ),
    TableSchema(
        schema="analytics",
        name="data_model_fields",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("model_id", "VARCHAR", nullable=False),
            Column("field_name", "VARCHAR", nullable=False),
            Column("field_type", "VARCHAR"),
            Column("required", "BOOLEAN", nullable=False),
            Column("has_default", "BOOLEAN", nullable=False),
            Column("default_expr", "VARCHAR"),
            Column("constraints_json", "JSON", nullable=False),
            Column("source", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("lineno", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "model_id", "field_name"),
        description="Normalized field definitions extracted from analytics.data_models.",
    ),
    TableSchema(
        schema="analytics",
        name="data_model_relationships",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("source_model_id", "VARCHAR", nullable=False),
            Column("target_model_id", "VARCHAR", nullable=False),
            Column("target_module", "VARCHAR"),
            Column("target_model_name", "VARCHAR"),
            Column("field_name", "VARCHAR", nullable=False),
            Column("relationship_kind", "VARCHAR", nullable=False),
            Column("multiplicity", "VARCHAR"),
            Column("via", "VARCHAR"),
            Column("evidence_json", "JSON"),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("lineno", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=(
            "repo",
            "commit",
            "source_model_id",
            "field_name",
            "target_model_id",
            "relationship_kind",
        ),
        description="Resolved relationships between data models with evidence and provenance.",
    ),
)

DATA_MODEL_USAGE_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="data_model_usage",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("model_id", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("usage_kinds_json", "JSON", nullable=False),
            Column("evidence_json", "JSON"),
            Column("context_json", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "model_id", "function_goid_h128"),
        description="Per function/model usage summary and context (CRUD/validate/serialize).",
    ),
)

FUNCTION_AST_FEATURES_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="function_ast_features",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR", nullable=False),
            Column("is_async", "BOOLEAN", nullable=False),
            Column("uses_network", "BOOLEAN", nullable=False),
            Column("uses_db", "BOOLEAN", nullable=False),
            Column("uses_filesystem", "BOOLEAN", nullable=False),
            Column("uses_subprocess", "BOOLEAN", nullable=False),
            Column("uses_concurrency_lib", "BOOLEAN", nullable=False),
            Column("uses_threading", "BOOLEAN", nullable=False),
            Column("uses_asyncio_lib", "BOOLEAN", nullable=False),
            Column("http_client_libs", "JSON", nullable=False),
            Column("http_server_libs", "JSON", nullable=False),
            Column("db_libs", "JSON", nullable=False),
            Column("message_libs", "JSON", nullable=False),
            Column("config_read_count", "INTEGER", nullable=False),
            Column("feature_flag_count", "INTEGER", nullable=False),
            Column("decorators", "JSON", nullable=False),
            Column("libraries_used", "JSON", nullable=False),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(
            Index(
                "idx_analytics_function_ast_features_repo_commit",
                ("repo", "commit"),
            ),
        ),
        description=(
            "Per-function AST-derived semantic features for explainability and classification."
        ),
    ),
)

GRAPH_METRICS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="graph_metrics_functions",
        columns=[
            *REPO_COMMIT_COLS,
            *FUNCTION_GOID_COL,
            Column("call_fan_in", "INTEGER", nullable=False),
            Column("call_fan_out", "INTEGER", nullable=False),
            Column("call_in_degree", "INTEGER", nullable=False),
            Column("call_out_degree", "INTEGER", nullable=False),
            Column("call_pagerank", "DOUBLE"),
            Column("call_betweenness", "DOUBLE"),
            Column("call_closeness", "DOUBLE"),
            Column("call_cycle_member", "BOOLEAN", nullable=False),
            Column("call_cycle_id", "INTEGER"),
            Column("call_layer", "INTEGER"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_graph_metrics_fn_goid", ("function_goid_h128",)),),
        description="Graph metrics per function computed from the call graph",
    ),
    TableSchema(
        schema="analytics",
        name="graph_metrics_functions_ext",
        columns=[
            *REPO_COMMIT_COLS,
            *FUNCTION_GOID_COL,
            Column("call_betweenness", "DOUBLE"),
            Column("call_closeness", "DOUBLE"),
            Column("call_eigenvector", "DOUBLE"),
            Column("call_harmonic", "DOUBLE"),
            Column("call_core_number", "INTEGER"),
            Column("call_clustering_coeff", "DOUBLE"),
            Column("call_triangle_count", "BIGINT"),
            Column("call_is_articulation", "BOOLEAN"),
            Column("call_articulation_impact", "INTEGER"),
            Column("call_is_bridge_endpoint", "BOOLEAN"),
            Column("call_component_id", "INTEGER"),
            Column("call_component_size", "INTEGER"),
            Column("call_scc_id", "INTEGER"),
            Column("call_scc_size", "INTEGER"),
            Column("call_ancestor_count", "INTEGER"),
            Column("call_descendant_count", "INTEGER"),
            Column("call_community_id", "INTEGER"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_graph_metrics_ext_fn_goid", ("function_goid_h128",)),),
        description="Extended call graph metrics per function (centralities, components)",
    ),
    TableSchema(
        schema="analytics",
        name="graph_metrics_modules",
        columns=[
            *MODULE_ENTITY_COLS,
            Column("import_fan_in", "INTEGER", nullable=False),
            Column("import_fan_out", "INTEGER", nullable=False),
            Column("import_in_degree", "INTEGER", nullable=False),
            Column("import_out_degree", "INTEGER", nullable=False),
            Column("import_pagerank", "DOUBLE"),
            Column("import_betweenness", "DOUBLE"),
            Column("import_closeness", "DOUBLE"),
            Column("import_cycle_member", "BOOLEAN", nullable=False),
            Column("import_cycle_id", "INTEGER"),
            Column("import_layer", "INTEGER"),
            Column("symbol_fan_in", "INTEGER", nullable=False),
            Column("symbol_fan_out", "INTEGER", nullable=False),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "module"),
        indexes=(Index("idx_analytics_graph_metrics_module", ("module",)),),
        description="Graph metrics per module computed from imports and symbol uses",
    ),
    TableSchema(
        schema="analytics",
        name="graph_metrics_modules_ext",
        columns=[
            *MODULE_ENTITY_COLS,
            Column("import_betweenness", "DOUBLE"),
            Column("import_closeness", "DOUBLE"),
            Column("import_eigenvector", "DOUBLE"),
            Column("import_harmonic", "DOUBLE"),
            Column("import_k_core", "INTEGER"),
            Column("import_constraint", "DOUBLE"),
            Column("import_effective_size", "DOUBLE"),
            Column("import_rich_club", "BOOLEAN"),
            Column("import_shell_index", "INTEGER"),
            Column("import_community_id", "INTEGER"),
            Column("import_component_id", "INTEGER"),
            Column("import_component_size", "INTEGER"),
            Column("import_scc_id", "INTEGER"),
            Column("import_scc_size", "INTEGER"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "module"),
        indexes=(Index("idx_analytics_graph_metrics_modules_ext_module", ("module",)),),
        description=(
            "Extended import-graph metrics per module (centralities, cores, structural holes)"
        ),
    ),
    TableSchema(
        schema="analytics",
        name="graph_stats",
        columns=[
            Column("graph_name", "VARCHAR", nullable=False),
            *REPO_COMMIT_COLS,
            Column("node_count", "BIGINT"),
            Column("edge_count", "BIGINT"),
            Column("weak_component_count", "INTEGER"),
            Column("scc_count", "INTEGER"),
            Column("component_layers", "INTEGER"),
            Column("avg_clustering", "DOUBLE"),
            Column("diameter_estimate", "DOUBLE"),
            Column("avg_shortest_path_estimate", "DOUBLE"),
            *CREATED_AT_COL,
        ],
        primary_key=("graph_name", "repo", "commit"),
        description="Global graph-level statistics for call/import graphs",
    ),
)

GRAPH_VALIDATION_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="graph_validation",
        columns=[
            *REPO_COMMIT_COLS,
            Column("graph_name", "VARCHAR", nullable=False),
            Column("entity_id", "VARCHAR", nullable=False),
            Column("issue", "VARCHAR", nullable=False),
            Column("severity", "VARCHAR", nullable=True),
            Column("rel_path", "VARCHAR", nullable=True),
            Column("detail", "VARCHAR", nullable=False),
            Column("metadata", "JSON", nullable=True),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "graph_name", "entity_id", "issue"),
        indexes=(Index("idx_graph_validation_repo_commit", ("repo", "commit")),),
        description="Validation findings for analytics graph consistency checks",
    ),
)

SYMBOL_GRAPH_METRICS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="symbol_graph_metrics_modules",
        columns=[
            *MODULE_ENTITY_COLS,
            Column("symbol_betweenness", "DOUBLE"),
            Column("symbol_closeness", "DOUBLE"),
            Column("symbol_eigenvector", "DOUBLE"),
            Column("symbol_harmonic", "DOUBLE"),
            Column("symbol_k_core", "INTEGER"),
            Column("symbol_constraint", "DOUBLE"),
            Column("symbol_effective_size", "DOUBLE"),
            Column("symbol_community_id", "INTEGER"),
            Column("symbol_component_id", "INTEGER"),
            Column("symbol_component_size", "INTEGER"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "module"),
        description="Symbol-coupling graph metrics per module",
    ),
    TableSchema(
        schema="analytics",
        name="symbol_graph_metrics_functions",
        columns=[
            *REPO_COMMIT_COLS,
            *FUNCTION_GOID_COL,
            Column("symbol_betweenness", "DOUBLE"),
            Column("symbol_closeness", "DOUBLE"),
            Column("symbol_eigenvector", "DOUBLE"),
            Column("symbol_harmonic", "DOUBLE"),
            Column("symbol_k_core", "INTEGER"),
            Column("symbol_constraint", "DOUBLE"),
            Column("symbol_effective_size", "DOUBLE"),
            Column("symbol_community_id", "INTEGER"),
            Column("symbol_component_id", "INTEGER"),
            Column("symbol_component_size", "INTEGER"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_symbol_graph_metrics_fn", ("function_goid_h128",)),),
        description="Symbol-coupling graph metrics per function",
    ),
)

SUBSYSTEM_GRAPH_METRICS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="subsystem_graph_metrics",
        columns=[
            *SUBSYSTEM_ENTITY_COLS,
            Column("import_in_degree", "DOUBLE"),
            Column("import_out_degree", "DOUBLE"),
            Column("import_pagerank", "DOUBLE"),
            Column("import_betweenness", "DOUBLE"),
            Column("import_closeness", "DOUBLE"),
            Column("import_layer", "INTEGER"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "subsystem_id"),
        description="Graph metrics on the subsystem-level condensed import graph",
    ),
)

SUBSYSTEM_AGREEMENT_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="subsystem_agreement",
        columns=[
            *MODULE_ENTITY_COLS,
            Column("subsystem_id", "VARCHAR"),
            Column("import_community_id", "INTEGER"),
            Column("agrees", "BOOLEAN"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "module"),
        description="Agreement check between subsystem labels and import communities",
    ),
)

SUBSYSTEMS_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="subsystems",
        columns=[
            *SUBSYSTEM_ENTITY_COLS,
            Column("name", "VARCHAR", nullable=False),
            Column("description", "VARCHAR"),
            Column("module_count", "INTEGER", nullable=False),
            Column("modules_json", "JSON", nullable=False),
            Column("entrypoints_json", "JSON"),
            Column("internal_edge_count", "INTEGER", nullable=False),
            Column("external_edge_count", "INTEGER", nullable=False),
            Column("fan_in", "INTEGER", nullable=False),
            Column("fan_out", "INTEGER", nullable=False),
            Column("function_count", "INTEGER", nullable=False),
            Column("avg_risk_score", "DOUBLE"),
            Column("max_risk_score", "DOUBLE"),
            Column("high_risk_function_count", "INTEGER", nullable=False),
            Column("risk_level", "VARCHAR"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "subsystem_id"),
        indexes=(
            Index(
                "idx_analytics_subsystems_repo_commit_id",
                ("repo", "commit", "subsystem_id"),
            ),
        ),
        description="Inferred architectural subsystems with summary metrics",
    ),
    TableSchema(
        schema="analytics",
        name="subsystem_modules",
        columns=[
            *SUBSYSTEM_ENTITY_COLS,
            Column("module", "VARCHAR", nullable=False),
            Column("role", "VARCHAR"),
        ],
        primary_key=("repo", "commit", "subsystem_id", "module"),
        indexes=(Index("idx_analytics_subsystem_modules_module", ("module",)),),
        description="Mapping of subsystems to member modules",
    ),
)

SUBSYSTEM_CACHE_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="subsystem_profile_cache",
        columns=[
            *SUBSYSTEM_ENTITY_COLS,
            Column("name", "VARCHAR"),
            Column("description", "VARCHAR"),
            Column("module_count", "INTEGER"),
            Column("modules_json", "JSON"),
            Column("entrypoints_json", "JSON"),
            Column("internal_edge_count", "INTEGER"),
            Column("external_edge_count", "INTEGER"),
            Column("fan_in", "INTEGER"),
            Column("fan_out", "INTEGER"),
            Column("function_count", "INTEGER"),
            Column("avg_risk_score", "DOUBLE"),
            Column("max_risk_score", "DOUBLE"),
            Column("high_risk_function_count", "INTEGER"),
            Column("risk_level", "VARCHAR"),
            Column("import_in_degree", "DOUBLE"),
            Column("import_out_degree", "DOUBLE"),
            Column("import_pagerank", "DOUBLE"),
            Column("import_betweenness", "DOUBLE"),
            Column("import_closeness", "DOUBLE"),
            Column("import_layer", "INTEGER"),
            *CREATED_AT_COL_NULLABLE,
        ],
        primary_key=("repo", "commit", "subsystem_id"),
        description="Cached subsystem profile metrics derived from subsystem analytics.",
    ),
)

SEMANTIC_ROLES_OVERRIDE_TABLES: tuple[TableSchema, ...] = (
    TableSchema(
        schema="analytics",
        name="semantic_roles_functions",
        columns=[
            *REPO_COMMIT_COLS,
            *FUNCTION_GOID_COL,
            Column("role", "VARCHAR"),
            Column("framework", "VARCHAR"),
            Column("role_confidence", "DOUBLE"),
            Column("role_sources_json", "JSON"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_semantic_roles_fn", ("function_goid_h128",)),),
        description="Semantic role classification per function",
    ),
    TableSchema(
        schema="analytics",
        name="semantic_roles_modules",
        columns=[
            *MODULE_ENTITY_COLS,
            Column("role", "VARCHAR"),
            Column("role_confidence", "DOUBLE"),
            Column("role_sources_json", "JSON"),
            *CREATED_AT_COL,
        ],
        primary_key=("repo", "commit", "module"),
        indexes=(Index("idx_analytics_semantic_roles_mod", ("module",)),),
        description="Semantic role classification per module",
    ),
)


def _all_output_tables() -> tuple[TableSchema, ...]:
    return (
        *AST_OVERRIDE_TABLES,
        *CALL_GRAPH_OVERRIDE_TABLES,
        *CFG_DFG_METRICS_OVERRIDE_TABLES,
        *CFG_OVERRIDE_TABLES,
        *CONFIG_DATA_FLOW_OVERRIDE_TABLES,
        *CONFIG_INGEST_OVERRIDE_TABLES,
        *CST_OVERRIDE_TABLES,
        *SYNTAX_OVERRIDE_TABLES,
        *SYNTAX_RESOLVED_OVERRIDE_TABLES,
        *TREE_SITTER_OVERRIDE_TABLES,
        *CI_PLAN_OVERRIDE_TABLES,
        *DATA_MODELS_OVERRIDE_TABLES,
        *DATA_MODEL_USAGE_OVERRIDE_TABLES,
        *DFG_OVERRIDE_TABLES,
        *DOCSTRINGS_OVERRIDE_TABLES,
        *EXAMPLE_OVERRIDE_TABLES,
        *ENTRYPOINTS_OVERRIDE_TABLES,
        *EXTERNAL_DEPS_OVERRIDE_TABLES,
        *FUNCTION_AST_FEATURES_OVERRIDE_TABLES,
        *FUNCTION_CONTRACTS_OVERRIDE_TABLES,
        *FUNCTION_EFFECTS_OVERRIDE_TABLES,
        *FUNCTION_ANALYTICS_OVERRIDE_TABLES,
        *GOIDS_OVERRIDE_TABLES,
        *GRAPH_METRICS_OVERRIDE_TABLES,
        *GRAPH_VALIDATION_OVERRIDE_TABLES,
        *IMPORT_GRAPH_OVERRIDE_TABLES,
        *MODULES_OVERRIDE_TABLES,
        *FILE_LINE_INDEX_OVERRIDE_TABLES,
        *SCHEMA_INFERENCE_ERRORS_OVERRIDE_TABLES,
        *SCIP_OVERRIDE_TABLES,
        *SCIP_RESOLUTION_OVERRIDE_TABLES,
        *SEMANTIC_ROLES_OVERRIDE_TABLES,
        *SUBSYSTEMS_OVERRIDE_TABLES,
        *SUBSYSTEM_AGREEMENT_OVERRIDE_TABLES,
        *SUBSYSTEM_CACHE_OVERRIDE_TABLES,
        *SUBSYSTEM_GRAPH_METRICS_OVERRIDE_TABLES,
        *SYMBOL_GRAPH_METRICS_OVERRIDE_TABLES,
        *SYMBOL_USES_OVERRIDE_TABLES,
        *CPG_OVERRIDE_TABLES,
        *TESTS_INGEST_OVERRIDE_TABLES,
        *TYPING_OVERRIDE_TABLES,
    )


NON_INFERABLE_OUTPUT_KEYS: frozenset[str] = frozenset(
    {
        "analytics.static_diagnostics",
        "ci.plan_entries",
        "core.ast_metrics",
        "core.ast_nodes",
        "core.cst_nodes",
        "core.docstrings",
        "core.file_line_index",
        "core.file_state",
        "core.modules",
        "core.parse_manifest",
        "core.repo_map",
        "core.schema_inference_errors",
        "core.scip_diagnostics",
        "core.scip_external_symbols",
        "core.scip_module_state",
        "core.scip_occurrences",
        "core.scip_occurrence_span_xref",
        "core.scip_symbol_information",
        "core.scip_symbol_relationships",
        "core.scip_symbol_goid_xref",
        "core.scip_symbols",
        "core.syntax_calls",
        "core.syntax_defs",
        "core.syntax_imports",
        "core.syntax_refs",
        "core.syntax_scopes",
        "core.syntax_spans",
        "core.ts_captures",
        "core.ts_parse_errors",
    }
)


def _build_output_table_schemas() -> dict[str, TableSchema]:
    table_map: dict[str, TableSchema] = {}
    for table in _all_output_tables():
        if table.table_key in table_map:
            msg = f"Duplicate output TableSchema: {table.table_key}"
            raise ValueError(msg)
        table_map[table.table_key] = table
    missing = NON_INFERABLE_OUTPUT_KEYS.difference(table_map)
    if missing:
        msg = f"Missing non-inferable TableSchemas: {sorted(missing)}"
        raise ValueError(msg)
    return table_map


OUTPUT_TABLE_SCHEMAS = _build_output_table_schemas()


__all__ = [
    "AST_OVERRIDE_TABLES",
    "CALL_GRAPH_OVERRIDE_TABLES",
    "CFG_DFG_METRICS_OVERRIDE_TABLES",
    "CFG_OVERRIDE_TABLES",
    "CI_PLAN_OVERRIDE_TABLES",
    "CONFIG_DATA_FLOW_OVERRIDE_TABLES",
    "CONFIG_INGEST_OVERRIDE_TABLES",
    "CPG_OVERRIDE_TABLES",
    "CST_OVERRIDE_TABLES",
    "DATA_MODELS_OVERRIDE_TABLES",
    "DATA_MODEL_USAGE_OVERRIDE_TABLES",
    "DFG_OVERRIDE_TABLES",
    "DOCSTRINGS_OVERRIDE_TABLES",
    "ENTRYPOINTS_OVERRIDE_TABLES",
    "EXAMPLE_OVERRIDE_TABLES",
    "EXTERNAL_DEPS_OVERRIDE_TABLES",
    "FILE_LINE_INDEX_OVERRIDE_TABLES",
    "FUNCTION_ANALYTICS_OVERRIDE_TABLES",
    "FUNCTION_AST_FEATURES_OVERRIDE_TABLES",
    "FUNCTION_CONTRACTS_OVERRIDE_TABLES",
    "FUNCTION_EFFECTS_OVERRIDE_TABLES",
    "GOIDS_OVERRIDE_TABLES",
    "GRAPH_METRICS_OVERRIDE_TABLES",
    "GRAPH_VALIDATION_OVERRIDE_TABLES",
    "IMPORT_GRAPH_OVERRIDE_TABLES",
    "MODULES_OVERRIDE_TABLES",
    "NON_INFERABLE_OUTPUT_KEYS",
    "OUTPUT_TABLE_SCHEMAS",
    "SCHEMA_INFERENCE_ERRORS_OVERRIDE_TABLES",
    "SCIP_OVERRIDE_TABLES",
    "SCIP_RESOLUTION_OVERRIDE_TABLES",
    "SEMANTIC_ROLES_OVERRIDE_TABLES",
    "SUBSYSTEMS_OVERRIDE_TABLES",
    "SUBSYSTEM_AGREEMENT_OVERRIDE_TABLES",
    "SUBSYSTEM_CACHE_OVERRIDE_TABLES",
    "SUBSYSTEM_GRAPH_METRICS_OVERRIDE_TABLES",
    "SYMBOL_GRAPH_METRICS_OVERRIDE_TABLES",
    "SYMBOL_USES_OVERRIDE_TABLES",
    "SYNTAX_OVERRIDE_TABLES",
    "SYNTAX_RESOLVED_OVERRIDE_TABLES",
    "TESTS_INGEST_OVERRIDE_TABLES",
    "TREE_SITTER_OVERRIDE_TABLES",
    "TYPING_OVERRIDE_TABLES",
]
