"""Error handling infrastructure for CLI operations.

This package provides:

- ``ProblemDetail``: RFC 9457 Problem Details support
- ``CliError``: Base exception hierarchy
- Error taxonomy with categorized error codes
- Error handling utilities for commands
"""

from __future__ import annotations

from codeintel.cli.errors._cli_errors import (
    CLI_EXIT_SUCCESS,
    CLI_EXIT_USAGE,
    CLI_EXIT_VALIDATION,
    CliError,
    DocsValidationError,
    ErrorType,
    OutputFormat,
    ProblemDetail,
    StorageConnectionError,
    StorageError,
    StorageQueryError,
    StorageSchemaError,
    UnknownCommandCliError,
    UnknownOptionCliError,
    ValidationError,
    handle_cli_error,
    run_handler,
    run_structured_handler,
    runtime_required,
)
from codeintel.cli.errors.builder import ProblemBuilder
from codeintel.cli.errors.results import (
    fail_config,
    fail_domain,
    fail_internal,
    fail_invalid_value,
    fail_job_not_completed,
    fail_job_not_found,
    fail_missing_required,
    fail_not_found,
    fail_operation,
    fail_storage,
    fail_storage_connection,
    fail_storage_query,
    fail_validation,
    fail_with_problem,
)
from codeintel.cli.errors.taxonomy import (
    ErrorContext,
    StructuredCliError,
    StructuredOperationError,
    StructuredValidationError,
    config_error,
    config_not_found_error,
    config_validation_error,
    internal_error,
    job_not_found_error,
    make_error_type,
    missing_required_error,
    not_found_error,
    operation_error,
    service_error,
    storage_error,
    timeout_error,
    validation_error,
)

__all__ = [
    "CLI_EXIT_SUCCESS",
    "CLI_EXIT_USAGE",
    "CLI_EXIT_VALIDATION",
    "CliError",
    "DocsValidationError",
    "ErrorContext",
    "ErrorType",
    "OutputFormat",
    "ProblemBuilder",
    "ProblemDetail",
    "StorageConnectionError",
    "StorageError",
    "StorageQueryError",
    "StorageSchemaError",
    "StructuredCliError",
    "StructuredOperationError",
    "StructuredValidationError",
    "UnknownCommandCliError",
    "UnknownOptionCliError",
    "ValidationError",
    "config_error",
    "config_not_found_error",
    "config_validation_error",
    "fail_config",
    "fail_domain",
    "fail_internal",
    "fail_invalid_value",
    "fail_job_not_completed",
    "fail_job_not_found",
    "fail_missing_required",
    "fail_not_found",
    "fail_operation",
    "fail_storage",
    "fail_storage_connection",
    "fail_storage_query",
    "fail_validation",
    "fail_with_problem",
    "handle_cli_error",
    "internal_error",
    "job_not_found_error",
    "make_error_type",
    "missing_required_error",
    "not_found_error",
    "operation_error",
    "run_handler",
    "run_structured_handler",
    "runtime_required",
    "service_error",
    "storage_error",
    "timeout_error",
    "validation_error",
]
