"""Error handling infrastructure for CLI operations.

This package provides:

- ``ProblemDetail``: RFC 9457 Problem Details support
- ``CliError``: Base exception hierarchy
- Error taxonomy with categorized error codes
- Error handling utilities for commands
"""

from __future__ import annotations

# CLI error handling exports
from codeintel.cli.errors._cli_errors import (
    CLI_EXIT_SUCCESS,
    CLI_EXIT_USAGE,
    CLI_EXIT_VALIDATION,
    CliError,
    DocsValidationError,
    ErrorType,
    OutputFormat,
    ProblemDetail,
    StorageConnectionError,
    StorageError,
    StorageQueryError,
    StorageSchemaError,
    UnknownCommandCliError,
    UnknownOptionCliError,
    ValidationError,
    handle_cli_error,
    run_handler,
    run_structured_handler,
    runtime_required,
)

# Error builder (consolidated ProblemDetail creation)
from codeintel.cli.errors.builder import ProblemBuilder

# Result factories (new consolidated API)
from codeintel.cli.errors.results import (
    fail_config,
    fail_domain,
    fail_job_not_completed,
    fail_job_not_found,
    fail_operation,
    fail_storage,
    fail_validation,
)
from codeintel.cli.errors.results import (
    fail_internal,
    fail_invalid_value,
    fail_missing_required,
    fail_not_found,
    fail_storage_connection,
)

# Legacy factory exports (for backward compatibility, use results.py instead)
from codeintel.cli.errors.factory import (
    fail_storage_query,
    fail_with_problem,
)

# Error taxonomy exports
from codeintel.cli.errors.taxonomy import (
    ALREADY_EXISTS,
    AUTH_FAILED,
    CANCELLED,
    CONFIG_FILE_NOT_FOUND,
    CONFIG_INVALID_VALUE,
    CONFIG_PARSE_ERROR,
    CONFIG_SCHEMA_VIOLATION,
    CONNECTION_FAILED,
    CONSTRAINT_VIOLATION,
    CORRUPTION_DETECTED,
    DEPENDENCY_FAILED,
    INTERNAL_ERROR,
    INVALID_FORMAT,
    INVALID_TYPE,
    JOB_ALREADY_RUNNING,
    JOB_EXPIRED,
    JOB_FAILED,
    JOB_NOT_FOUND,
    MISSING_REQUIRED,
    NOT_FOUND,
    OUT_OF_RANGE,
    PERMISSION_DENIED,
    QUERY_FAILED,
    RATE_LIMITED,
    SCHEMA_MISMATCH,
    SERVICE_UNAVAILABLE,
    TIMEOUT,
    ConfigErrorCode,
    ErrorCategory,
    ErrorCode,
    ErrorContext,
    JobErrorCode,
    OperationErrorCode,
    ServiceErrorCode,
    StorageErrorCode,
    StructuredCliError,
    StructuredOperationError,
    StructuredValidationError,
    ValidationErrorCode,
    config_error,
    config_not_found_error,
    config_validation_error,
    internal_error,
    job_not_found_error,
    make_error_type,
    missing_required_error,
    not_found_error,
    operation_error,
    service_error,
    storage_error,
    timeout_error,
    validation_error,
)

__all__ = [
    # Error codes
    "ALREADY_EXISTS",
    "AUTH_FAILED",
    "CANCELLED",
    "CLI_EXIT_SUCCESS",
    "CLI_EXIT_USAGE",
    "CLI_EXIT_VALIDATION",
    "CONFIG_FILE_NOT_FOUND",
    "CONFIG_INVALID_VALUE",
    "CONFIG_PARSE_ERROR",
    "CONFIG_SCHEMA_VIOLATION",
    "CONNECTION_FAILED",
    "CONSTRAINT_VIOLATION",
    "CORRUPTION_DETECTED",
    "DEPENDENCY_FAILED",
    "INTERNAL_ERROR",
    "INVALID_FORMAT",
    "INVALID_TYPE",
    "JOB_ALREADY_RUNNING",
    "JOB_EXPIRED",
    "JOB_FAILED",
    "JOB_NOT_FOUND",
    "MISSING_REQUIRED",
    "NOT_FOUND",
    "OUT_OF_RANGE",
    "PERMISSION_DENIED",
    "QUERY_FAILED",
    "RATE_LIMITED",
    "SCHEMA_MISMATCH",
    "SERVICE_UNAVAILABLE",
    "TIMEOUT",
    # Error types and enums
    "CliError",
    "ConfigErrorCode",
    "DocsValidationError",
    "ErrorCategory",
    "ErrorCode",
    "ErrorContext",
    "ErrorType",
    "JobErrorCode",
    "OperationErrorCode",
    "OutputFormat",
    "ProblemBuilder",
    "ProblemDetail",
    "ServiceErrorCode",
    "StorageConnectionError",
    "StorageError",
    "StorageErrorCode",
    "StorageQueryError",
    "StorageSchemaError",
    "StructuredCliError",
    "StructuredOperationError",
    "StructuredValidationError",
    "UnknownCommandCliError",
    "UnknownOptionCliError",
    "ValidationError",
    "ValidationErrorCode",
    # Taxonomy functions
    "config_error",
    "config_not_found_error",
    "config_validation_error",
    "internal_error",
    "job_not_found_error",
    "make_error_type",
    "missing_required_error",
    "not_found_error",
    "operation_error",
    "service_error",
    "storage_error",
    "timeout_error",
    "validation_error",
    # Result factories (new consolidated API)
    "fail_config",
    "fail_domain",
    "fail_internal",
    "fail_invalid_value",
    "fail_job_not_completed",
    "fail_job_not_found",
    "fail_missing_required",
    "fail_not_found",
    "fail_operation",
    "fail_storage",
    "fail_storage_connection",
    "fail_storage_query",
    "fail_validation",
    "fail_with_problem",
    # Handler utilities
    "handle_cli_error",
    "run_handler",
    "run_structured_handler",
    "runtime_required",
]
