"""Table schema registry for ingestion and exports."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

ColumnType = Literal[
    "BOOLEAN",
    "INTEGER",
    "BIGINT",
    "DOUBLE",
    "DECIMAL",
    "DECIMAL(38,0)",
    "VARCHAR",
    "JSON",
    "TIMESTAMP",
]
COLUMN_TYPE = ColumnType


@dataclass(frozen=True)
class Column:
    """Definition of a single table column."""

    name: str
    type: ColumnType
    nullable: bool = True
    description: str | None = None


@dataclass(frozen=True)
class TableSchema:
    """Schema definition for a DuckDB table."""

    schema: str
    name: str
    columns: list[Column]
    primary_key: tuple[str, ...] = ()
    indexes: tuple[Index, ...] = ()
    description: str | None = None

    @property
    def fq_name(self) -> str:
        """Fully qualified table name."""
        return f"{self.schema}.{self.name}"

    def column_names(self) -> list[str]:
        """
        Ordered column names.

        Returns
        -------
        list[str]
            Column names in definition order.
        """
        return [col.name for col in self.columns]


@dataclass(frozen=True)
class Index:
    """Secondary index definition."""

    name: str
    columns: tuple[str, ...]
    unique: bool = False


TABLE_SCHEMAS: dict[str, TableSchema] = {
    "core.ast_nodes": TableSchema(
        schema="core",
        name="ast_nodes",
        columns=[
            Column("path", "VARCHAR", nullable=False, description="Relative path to source file"),
            Column("node_type", "VARCHAR", nullable=False),
            Column("name", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("lineno", "INTEGER"),
            Column("end_lineno", "INTEGER"),
            Column("decorator_start_line", "INTEGER"),
            Column("decorator_end_line", "INTEGER"),
            Column("col_offset", "INTEGER"),
            Column("end_col_offset", "INTEGER"),
            Column("parent_qualname", "VARCHAR"),
            Column("decorators", "JSON"),
            Column("docstring", "VARCHAR"),
            Column("hash", "VARCHAR", nullable=False),
        ],
        primary_key=("hash",),
        description="Flattened AST nodes",
    ),
    "core.ast_metrics": TableSchema(
        schema="core",
        name="ast_metrics",
        columns=[
            Column("rel_path", "VARCHAR", nullable=False),
            Column("node_count", "INTEGER", nullable=False),
            Column("function_count", "INTEGER", nullable=False),
            Column("class_count", "INTEGER", nullable=False),
            Column("avg_depth", "DOUBLE", nullable=False),
            Column("max_depth", "INTEGER", nullable=False),
            Column("complexity", "DOUBLE", nullable=False),
            Column("generated_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("rel_path",),
        description="Per-file AST metrics",
    ),
    "core.cst_nodes": TableSchema(
        schema="core",
        name="cst_nodes",
        columns=[
            Column("path", "VARCHAR", nullable=False),
            Column("node_id", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("span", "JSON", nullable=False),
            Column("text_preview", "VARCHAR"),
            Column("parents", "JSON"),
            Column("qnames", "JSON"),
        ],
        primary_key=("node_id",),
        description="Concrete syntax tree nodes",
    ),
    "core.docstrings": TableSchema(
        schema="core",
        name="docstrings",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("lineno", "INTEGER"),
            Column("end_lineno", "INTEGER"),
            Column("raw_docstring", "VARCHAR"),
            Column("style", "VARCHAR"),
            Column("short_desc", "VARCHAR"),
            Column("long_desc", "VARCHAR"),
            Column("params", "JSON"),
            Column("returns", "JSON"),
            Column("raises", "JSON"),
            Column("examples", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        description="Structured docstring facts extracted with griffe",
    ),
    "core.modules": TableSchema(
        schema="core",
        name="modules",
        columns=[
            Column("module", "VARCHAR", nullable=False),
            Column("path", "VARCHAR", nullable=False),
            Column("repo", "VARCHAR"),
            Column("commit", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("tags", "JSON"),
            Column("owners", "JSON"),
        ],
        primary_key=("module", "path"),
        indexes=(
            Index("idx_core_modules_path", ("path",)),
            Index("idx_core_modules_module", ("module",)),
        ),
        description="Discovered modules per repo/commit",
    ),
    "core.repo_map": TableSchema(
        schema="core",
        name="repo_map",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("modules", "JSON"),
            Column("overlays", "JSON"),
            Column("generated_at", "TIMESTAMP"),
        ],
        primary_key=("repo", "commit"),
        description="Per-commit module manifest and overlays",
    ),
    "core.goids": TableSchema(
        schema="core",
        name="goids",
        columns=[
            Column("goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("urn", "VARCHAR", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER"),
            Column("end_line", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("goid_h128",),
        indexes=(
            Index("idx_core_goids_h128", ("goid_h128",), unique=True),
            Index("idx_core_goids_urn", ("urn",), unique=True),
            Index("idx_core_goids_path", ("rel_path",)),
        ),
        description="Global object identifiers for code entities",
    ),
    "core.goid_crosswalk": TableSchema(
        schema="core",
        name="goid_crosswalk",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("goid", "VARCHAR", nullable=False),
            Column("lang", "VARCHAR", nullable=False),
            Column("module_path", "VARCHAR", nullable=False),
            Column("file_path", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER"),
            Column("end_line", "INTEGER"),
            Column("scip_symbol", "VARCHAR"),
            Column("ast_qualname", "VARCHAR"),
            Column("cst_node_id", "VARCHAR"),
            Column("chunk_id", "VARCHAR"),
            Column("symbol_id", "VARCHAR"),
            Column("updated_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "goid"),
        indexes=(Index("idx_core_gcw_goid", ("goid",)),),
        description="Crosswalk from GOIDs to language-specific symbols/paths",
    ),
    "analytics.coverage_lines": TableSchema(
        schema="analytics",
        name="coverage_lines",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("line", "INTEGER", nullable=False),
            Column("is_executable", "BOOLEAN", nullable=False),
            Column("is_covered", "BOOLEAN", nullable=False),
            Column("hits", "INTEGER", nullable=False),
            Column("context_count", "INTEGER", nullable=False),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        indexes=(
            Index("idx_analytics_cov_lines_repo_path", ("repo", "commit", "rel_path")),
            Index("idx_analytics_cov_lines_line", ("line",)),
        ),
        description="Line-level coverage facts",
    ),
    "analytics.test_catalog": TableSchema(
        schema="analytics",
        name="test_catalog",
        columns=[
            Column("test_id", "VARCHAR", nullable=False),
            Column("test_goid_h128", "DOUBLE"),
            Column("urn", "VARCHAR"),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR"),
            Column("kind", "VARCHAR"),
            Column("status", "VARCHAR"),
            Column("duration_ms", "DOUBLE"),
            Column("markers", "JSON"),
            Column("parametrized", "BOOLEAN"),
            Column("flaky", "BOOLEAN"),
            Column("created_at", "TIMESTAMP"),
        ],
        primary_key=("test_id",),
        indexes=(Index("idx_analytics_test_catalog_id", ("test_id",), unique=True),),
        description="Pytest test catalog",
    ),
    "analytics.config_values": TableSchema(
        schema="analytics",
        name="config_values",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("config_path", "VARCHAR", nullable=False),
            Column("format", "VARCHAR", nullable=False),
            Column("key", "VARCHAR", nullable=False),
            Column("reference_paths", "JSON"),
            Column("reference_modules", "JSON"),
            Column("reference_count", "INTEGER", nullable=False),
        ],
        primary_key=("repo", "commit", "config_path", "key"),
        description="Flattened config key/value paths",
    ),
    "analytics.tags_index": TableSchema(
        schema="analytics",
        name="tags_index",
        columns=[
            Column("tag", "VARCHAR", nullable=False),
            Column("description", "VARCHAR"),
            Column("includes", "JSON"),
            Column("excludes", "JSON"),
            Column("matches", "JSON"),
        ],
        primary_key=("tag",),
        description="Path classification rules",
    ),
    "analytics.typedness": TableSchema(
        schema="analytics",
        name="typedness",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("path", "VARCHAR", nullable=False),
            Column("type_error_count", "INTEGER", nullable=False),
            Column("annotation_ratio", "JSON", nullable=False),
            Column("untyped_defs", "INTEGER", nullable=False),
            Column("overlay_needed", "BOOLEAN", nullable=False),
        ],
        primary_key=("repo", "commit", "path"),
        description="Per-file annotation ratios and static error counts",
    ),
    "analytics.static_diagnostics": TableSchema(
        schema="analytics",
        name="static_diagnostics",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("pyrefly_errors", "INTEGER", nullable=False),
            Column("pyright_errors", "INTEGER", nullable=False),
            Column("ruff_errors", "INTEGER", nullable=False),
            Column("total_errors", "INTEGER", nullable=False),
            Column("has_errors", "BOOLEAN", nullable=False),
        ],
        primary_key=("repo", "commit", "rel_path"),
        description="Per-file static diagnostic counts",
    ),
    "analytics.entrypoints": TableSchema(
        schema="analytics",
        name="entrypoints",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("entrypoint_id", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("framework", "VARCHAR"),
            Column("handler_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("handler_urn", "VARCHAR", nullable=False),
            Column("handler_rel_path", "VARCHAR", nullable=False),
            Column("handler_module", "VARCHAR", nullable=False),
            Column("handler_qualname", "VARCHAR", nullable=False),
            Column("http_method", "VARCHAR"),
            Column("route_path", "VARCHAR"),
            Column("status_codes", "JSON"),
            Column("auth_required", "BOOLEAN"),
            Column("command_name", "VARCHAR"),
            Column("arguments_schema", "JSON"),
            Column("schedule", "VARCHAR"),
            Column("trigger", "VARCHAR"),
            Column("extra", "JSON"),
            Column("subsystem_id", "VARCHAR"),
            Column("subsystem_name", "VARCHAR"),
            Column("tags", "JSON"),
            Column("owners", "JSON"),
            Column("tests_touching", "INTEGER"),
            Column("failing_tests", "INTEGER"),
            Column("slow_tests", "INTEGER"),
            Column("flaky_tests", "INTEGER"),
            Column("entrypoint_coverage_ratio", "DOUBLE"),
            Column("last_test_status", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "entrypoint_id"),
        description="External entrypoints mapped to handlers, subsystems, and tests",
    ),
    "analytics.entrypoint_tests": TableSchema(
        schema="analytics",
        name="entrypoint_tests",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("entrypoint_id", "VARCHAR", nullable=False),
            Column("test_id", "VARCHAR", nullable=False),
            Column("test_goid_h128", "DECIMAL(38,0)"),
            Column("coverage_ratio", "DOUBLE"),
            Column("status", "VARCHAR"),
            Column("duration_ms", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "entrypoint_id", "test_id"),
        description="Bipartite edges between entrypoints and tests",
    ),
    "analytics.external_dependencies": TableSchema(
        schema="analytics",
        name="external_dependencies",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("dep_id", "VARCHAR", nullable=False),
            Column("library", "VARCHAR", nullable=False),
            Column("service_name", "VARCHAR"),
            Column("category", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("severity", "VARCHAR"),
            Column("criticality", "DOUBLE"),
            Column("risk_score", "DOUBLE"),
            Column("function_count", "INTEGER", nullable=False),
            Column("callsite_count", "INTEGER", nullable=False),
            Column("modules_json", "JSON", nullable=False),
            Column("usage_modes", "JSON", nullable=False),
            Column("config_keys", "JSON"),
            Column("risk_level", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "dep_id"),
        description="Aggregated view of external libraries/services used by the repo",
    ),
    "analytics.external_dependency_calls": TableSchema(
        schema="analytics",
        name="external_dependency_calls",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("dep_id", "VARCHAR", nullable=False),
            Column("library", "VARCHAR", nullable=False),
            Column("service_name", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("severity", "VARCHAR"),
            Column("criticality", "DOUBLE"),
            Column("risk_score", "DOUBLE"),
            Column("matched_pattern", "VARCHAR"),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("function_urn", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR", nullable=False),
            Column("callsite_count", "INTEGER", nullable=False),
            Column("modes", "JSON", nullable=False),
            Column("evidence_json", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "dep_id", "function_goid_h128"),
        description="Function-level callsites into external dependencies with modes and evidence",
    ),
    "analytics.data_models": TableSchema(
        schema="analytics",
        name="data_models",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("model_id", "VARCHAR", nullable=False),
            Column("goid_h128", "DECIMAL(38,0)"),
            Column("model_name", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("model_kind", "VARCHAR", nullable=False),
            Column("base_classes_json", "JSON"),
            Column("fields_json", "JSON", nullable=False),
            Column("relationships_json", "JSON"),
            Column("doc_short", "VARCHAR"),
            Column("doc_long", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "model_id"),
        description=(
            "Extracted data models (dataclasses, Pydantic, TypedDicts, ORMs) and their "
            "fields/relationships."
        ),
    ),
    "analytics.data_model_fields": TableSchema(
        schema="analytics",
        name="data_model_fields",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("model_id", "VARCHAR", nullable=False),
            Column("field_name", "VARCHAR", nullable=False),
            Column("field_type", "VARCHAR"),
            Column("required", "BOOLEAN", nullable=False),
            Column("has_default", "BOOLEAN", nullable=False),
            Column("default_expr", "VARCHAR"),
            Column("constraints_json", "JSON", nullable=False),
            Column("source", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("lineno", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "model_id", "field_name"),
        description="Normalized field definitions extracted from analytics.data_models.",
    ),
    "analytics.data_model_relationships": TableSchema(
        schema="analytics",
        name="data_model_relationships",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("source_model_id", "VARCHAR", nullable=False),
            Column("target_model_id", "VARCHAR", nullable=False),
            Column("target_module", "VARCHAR"),
            Column("target_model_name", "VARCHAR"),
            Column("field_name", "VARCHAR", nullable=False),
            Column("relationship_kind", "VARCHAR", nullable=False),
            Column("multiplicity", "VARCHAR"),
            Column("via", "VARCHAR"),
            Column("evidence_json", "JSON"),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("lineno", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=(
            "repo",
            "commit",
            "source_model_id",
            "field_name",
            "target_model_id",
            "relationship_kind",
        ),
        description="Resolved relationships between data models with evidence and provenance.",
    ),
    "analytics.data_model_usage": TableSchema(
        schema="analytics",
        name="data_model_usage",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("model_id", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("usage_kinds_json", "JSON", nullable=False),
            Column("evidence_json", "JSON"),
            Column("context_json", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "model_id", "function_goid_h128"),
        description="Per function/model usage summary and context (CRUD/validate/serialize).",
    ),
    "analytics.config_data_flow": TableSchema(
        schema="analytics",
        name="config_data_flow",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("config_key", "VARCHAR", nullable=False),
            Column("config_path", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("usage_kind", "VARCHAR", nullable=False),
            Column("evidence_json", "JSON"),
            Column("call_chain_id", "VARCHAR", nullable=False),
            Column("call_chain_json", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=(
            "repo",
            "commit",
            "config_key",
            "config_path",
            "function_goid_h128",
            "usage_kind",
            "call_chain_id",
        ),
        description="Function-level config key usage and call-chain context from entrypoints.",
    ),
    "analytics.function_validation": TableSchema(
        schema="analytics",
        name="function_validation",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR", nullable=False),
            Column("issue", "VARCHAR", nullable=False),
            Column("detail", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "rel_path", "qualname", "issue"),
        indexes=(Index("idx_function_validation_repo_commit", ("repo", "commit")),),
        description="Validation findings for function analytics gaps",
    ),
    "analytics.test_coverage_edges": TableSchema(
        schema="analytics",
        name="test_coverage_edges",
        columns=[
            Column("test_id", "VARCHAR"),
            Column("test_goid_h128", "DECIMAL(38,0)"),
            Column("function_goid_h128", "DECIMAL(38,0)"),
            Column("urn", "VARCHAR"),
            Column("repo", "VARCHAR"),
            Column("commit", "VARCHAR"),
            Column("rel_path", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("covered_lines", "INTEGER"),
            Column("executable_lines", "INTEGER"),
            Column("coverage_ratio", "DOUBLE"),
            Column("last_status", "VARCHAR"),
            Column("created_at", "TIMESTAMP"),
        ],
        indexes=(Index("idx_analytics_test_cov_edges_goid", ("function_goid_h128",)),),
        description="Per-test coverage edges between tests and functions",
    ),
    "analytics.function_metrics": TableSchema(
        schema="analytics",
        name="function_metrics",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)"),
            Column("urn", "VARCHAR"),
            Column("repo", "VARCHAR"),
            Column("commit", "VARCHAR"),
            Column("rel_path", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("kind", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("start_line", "INTEGER"),
            Column("end_line", "INTEGER"),
            Column("loc", "INTEGER"),
            Column("logical_loc", "INTEGER"),
            Column("param_count", "INTEGER"),
            Column("positional_params", "INTEGER"),
            Column("keyword_only_params", "INTEGER"),
            Column("has_varargs", "BOOLEAN"),
            Column("has_varkw", "BOOLEAN"),
            Column("is_async", "BOOLEAN"),
            Column("is_generator", "BOOLEAN"),
            Column("return_count", "INTEGER"),
            Column("yield_count", "INTEGER"),
            Column("raise_count", "INTEGER"),
            Column("cyclomatic_complexity", "INTEGER"),
            Column("max_nesting_depth", "INTEGER"),
            Column("stmt_count", "INTEGER"),
            Column("decorator_count", "INTEGER"),
            Column("has_docstring", "BOOLEAN"),
            Column("complexity_bucket", "VARCHAR"),
            Column("created_at", "TIMESTAMP"),
        ],
        indexes=(Index("idx_analytics_function_metrics_goid", ("function_goid_h128",)),),
        description="Per-function structural metrics",
    ),
    "analytics.function_types": TableSchema(
        schema="analytics",
        name="function_types",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)"),
            Column("urn", "VARCHAR"),
            Column("repo", "VARCHAR"),
            Column("commit", "VARCHAR"),
            Column("rel_path", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("kind", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("start_line", "INTEGER"),
            Column("end_line", "INTEGER"),
            Column("total_params", "INTEGER"),
            Column("annotated_params", "INTEGER"),
            Column("unannotated_params", "INTEGER"),
            Column("param_typed_ratio", "DOUBLE"),
            Column("has_return_annotation", "BOOLEAN"),
            Column("return_type", "VARCHAR"),
            Column("return_type_source", "VARCHAR"),
            Column("type_comment", "VARCHAR"),
            Column("param_types", "JSON"),
            Column("fully_typed", "BOOLEAN"),
            Column("partial_typed", "BOOLEAN"),
            Column("untyped", "BOOLEAN"),
            Column("typedness_bucket", "VARCHAR"),
            Column("typedness_source", "VARCHAR"),
            Column("created_at", "TIMESTAMP"),
        ],
        indexes=(Index("idx_analytics_function_types_goid", ("function_goid_h128",)),),
        description="Per-function annotation coverage",
    ),
    "analytics.function_effects": TableSchema(
        schema="analytics",
        name="function_effects",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("is_pure", "BOOLEAN", nullable=False),
            Column("uses_io", "BOOLEAN", nullable=False),
            Column("touches_db", "BOOLEAN", nullable=False),
            Column("uses_time", "BOOLEAN", nullable=False),
            Column("uses_randomness", "BOOLEAN", nullable=False),
            Column("modifies_globals", "BOOLEAN", nullable=False),
            Column("modifies_closure", "BOOLEAN", nullable=False),
            Column("spawns_threads_or_tasks", "BOOLEAN", nullable=False),
            Column("has_transitive_effects", "BOOLEAN", nullable=False),
            Column("purity_confidence", "DOUBLE"),
            Column("effects_json", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_function_effects_goid", ("function_goid_h128",)),),
        description="Side-effect and purity classification per function GOID",
    ),
    "analytics.function_contracts": TableSchema(
        schema="analytics",
        name="function_contracts",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("preconditions_json", "JSON"),
            Column("postconditions_json", "JSON"),
            Column("raises_json", "JSON"),
            Column("param_nullability_json", "JSON"),
            Column("return_nullability", "VARCHAR"),
            Column("contract_confidence", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_function_contracts_goid", ("function_goid_h128",)),),
        description="Inferred pre/postconditions and nullability per function",
    ),
    "analytics.coverage_functions": TableSchema(
        schema="analytics",
        name="coverage_functions",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)"),
            Column("urn", "VARCHAR"),
            Column("repo", "VARCHAR"),
            Column("commit", "VARCHAR"),
            Column("rel_path", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("kind", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("start_line", "INTEGER"),
            Column("end_line", "INTEGER"),
            Column("executable_lines", "INTEGER"),
            Column("covered_lines", "INTEGER"),
            Column("coverage_ratio", "DOUBLE"),
            Column("tested", "BOOLEAN"),
            Column("untested_reason", "VARCHAR"),
            Column("created_at", "TIMESTAMP"),
        ],
        indexes=(Index("idx_analytics_coverage_functions_goid", ("function_goid_h128",)),),
        description="Line coverage aggregates per function",
    ),
    "analytics.goid_risk_factors": TableSchema(
        schema="analytics",
        name="goid_risk_factors",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)"),
            Column("urn", "VARCHAR"),
            Column("repo", "VARCHAR"),
            Column("commit", "VARCHAR"),
            Column("rel_path", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("kind", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("loc", "INTEGER"),
            Column("logical_loc", "INTEGER"),
            Column("cyclomatic_complexity", "INTEGER"),
            Column("complexity_bucket", "VARCHAR"),
            Column("typedness_bucket", "VARCHAR"),
            Column("typedness_source", "VARCHAR"),
            Column("hotspot_score", "DOUBLE"),
            Column("file_typed_ratio", "DOUBLE"),
            Column("static_error_count", "INTEGER"),
            Column("has_static_errors", "BOOLEAN"),
            Column("executable_lines", "INTEGER"),
            Column("covered_lines", "INTEGER"),
            Column("coverage_ratio", "DOUBLE"),
            Column("tested", "BOOLEAN"),
            Column("test_count", "INTEGER"),
            Column("failing_test_count", "INTEGER"),
            Column("last_test_status", "VARCHAR"),
            Column("risk_score", "DOUBLE"),
            Column("risk_level", "VARCHAR"),
            Column("tags", "JSON"),
            Column("owners", "JSON"),
            Column("created_at", "TIMESTAMP"),
        ],
        indexes=(Index("idx_analytics_gorf_goid", ("function_goid_h128",)),),
        description="Composite risk factors per function",
    ),
    "analytics.graph_metrics_functions": TableSchema(
        schema="analytics",
        name="graph_metrics_functions",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("call_fan_in", "INTEGER", nullable=False),
            Column("call_fan_out", "INTEGER", nullable=False),
            Column("call_in_degree", "INTEGER", nullable=False),
            Column("call_out_degree", "INTEGER", nullable=False),
            Column("call_pagerank", "DOUBLE"),
            Column("call_betweenness", "DOUBLE"),
            Column("call_closeness", "DOUBLE"),
            Column("call_cycle_member", "BOOLEAN", nullable=False),
            Column("call_cycle_id", "INTEGER"),
            Column("call_layer", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_graph_metrics_fn_goid", ("function_goid_h128",)),),
        description="Graph metrics per function computed from the call graph",
    ),
    "analytics.graph_metrics_modules": TableSchema(
        schema="analytics",
        name="graph_metrics_modules",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("import_fan_in", "INTEGER", nullable=False),
            Column("import_fan_out", "INTEGER", nullable=False),
            Column("import_in_degree", "INTEGER", nullable=False),
            Column("import_out_degree", "INTEGER", nullable=False),
            Column("import_pagerank", "DOUBLE"),
            Column("import_betweenness", "DOUBLE"),
            Column("import_closeness", "DOUBLE"),
            Column("import_cycle_member", "BOOLEAN", nullable=False),
            Column("import_cycle_id", "INTEGER"),
            Column("import_layer", "INTEGER"),
            Column("symbol_fan_in", "INTEGER", nullable=False),
            Column("symbol_fan_out", "INTEGER", nullable=False),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "module"),
        indexes=(Index("idx_analytics_graph_metrics_module", ("module",)),),
        description="Graph metrics per module computed from imports and symbol uses",
    ),
    "analytics.graph_metrics_modules_ext": TableSchema(
        schema="analytics",
        name="graph_metrics_modules_ext",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("import_betweenness", "DOUBLE"),
            Column("import_closeness", "DOUBLE"),
            Column("import_eigenvector", "DOUBLE"),
            Column("import_harmonic", "DOUBLE"),
            Column("import_k_core", "INTEGER"),
            Column("import_constraint", "DOUBLE"),
            Column("import_effective_size", "DOUBLE"),
            Column("import_rich_club", "BOOLEAN"),
            Column("import_shell_index", "INTEGER"),
            Column("import_community_id", "INTEGER"),
            Column("import_component_id", "INTEGER"),
            Column("import_component_size", "INTEGER"),
            Column("import_scc_id", "INTEGER"),
            Column("import_scc_size", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "module"),
        indexes=(Index("idx_analytics_graph_metrics_modules_ext_module", ("module",)),),
        description=(
            "Extended import-graph metrics per module (centralities, cores, structural holes)"
        ),
    ),
    "analytics.subsystem_graph_metrics": TableSchema(
        schema="analytics",
        name="subsystem_graph_metrics",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("subsystem_id", "VARCHAR", nullable=False),
            Column("import_in_degree", "DOUBLE"),
            Column("import_out_degree", "DOUBLE"),
            Column("import_pagerank", "DOUBLE"),
            Column("import_betweenness", "DOUBLE"),
            Column("import_closeness", "DOUBLE"),
            Column("import_layer", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "subsystem_id"),
        description="Graph metrics on the subsystem-level condensed import graph",
    ),
    "analytics.graph_stats": TableSchema(
        schema="analytics",
        name="graph_stats",
        columns=[
            Column("graph_name", "VARCHAR", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("node_count", "BIGINT"),
            Column("edge_count", "BIGINT"),
            Column("weak_component_count", "INTEGER"),
            Column("scc_count", "INTEGER"),
            Column("component_layers", "INTEGER"),
            Column("avg_clustering", "DOUBLE"),
            Column("diameter_estimate", "DOUBLE"),
            Column("avg_shortest_path_estimate", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("graph_name", "repo", "commit"),
        description="Global graph-level statistics for call/import graphs",
    ),
    "analytics.symbol_graph_metrics_modules": TableSchema(
        schema="analytics",
        name="symbol_graph_metrics_modules",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("symbol_betweenness", "DOUBLE"),
            Column("symbol_closeness", "DOUBLE"),
            Column("symbol_eigenvector", "DOUBLE"),
            Column("symbol_harmonic", "DOUBLE"),
            Column("symbol_k_core", "INTEGER"),
            Column("symbol_constraint", "DOUBLE"),
            Column("symbol_effective_size", "DOUBLE"),
            Column("symbol_community_id", "INTEGER"),
            Column("symbol_component_id", "INTEGER"),
            Column("symbol_component_size", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "module"),
        description="Symbol-coupling graph metrics per module",
    ),
    "analytics.symbol_graph_metrics_functions": TableSchema(
        schema="analytics",
        name="symbol_graph_metrics_functions",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("symbol_betweenness", "DOUBLE"),
            Column("symbol_closeness", "DOUBLE"),
            Column("symbol_eigenvector", "DOUBLE"),
            Column("symbol_harmonic", "DOUBLE"),
            Column("symbol_k_core", "INTEGER"),
            Column("symbol_constraint", "DOUBLE"),
            Column("symbol_effective_size", "DOUBLE"),
            Column("symbol_community_id", "INTEGER"),
            Column("symbol_component_id", "INTEGER"),
            Column("symbol_component_size", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_symbol_graph_metrics_fn", ("function_goid_h128",)),),
        description="Symbol-coupling graph metrics per function",
    ),
    "analytics.config_graph_metrics_keys": TableSchema(
        schema="analytics",
        name="config_graph_metrics_keys",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("config_key", "VARCHAR", nullable=False),
            Column("degree", "INTEGER"),
            Column("weighted_degree", "DOUBLE"),
            Column("betweenness", "DOUBLE"),
            Column("closeness", "DOUBLE"),
            Column("community_id", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "config_key"),
        description="Metrics for config keys in config-module bipartite/projection graphs",
    ),
    "analytics.config_graph_metrics_modules": TableSchema(
        schema="analytics",
        name="config_graph_metrics_modules",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("degree", "INTEGER"),
            Column("weighted_degree", "DOUBLE"),
            Column("betweenness", "DOUBLE"),
            Column("closeness", "DOUBLE"),
            Column("community_id", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "module"),
        description="Metrics for modules in config-module bipartite/projection graphs",
    ),
    "analytics.config_projection_key_edges": TableSchema(
        schema="analytics",
        name="config_projection_key_edges",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("src_key", "VARCHAR", nullable=False),
            Column("dst_key", "VARCHAR", nullable=False),
            Column("weight", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "src_key", "dst_key"),
        description="Projected key-key edges from shared module usage",
    ),
    "analytics.config_projection_module_edges": TableSchema(
        schema="analytics",
        name="config_projection_module_edges",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("src_module", "VARCHAR", nullable=False),
            Column("dst_module", "VARCHAR", nullable=False),
            Column("weight", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "src_module", "dst_module"),
        description="Projected module-module edges from shared config keys",
    ),
    "analytics.subsystem_agreement": TableSchema(
        schema="analytics",
        name="subsystem_agreement",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("subsystem_id", "VARCHAR"),
            Column("import_community_id", "INTEGER"),
            Column("agrees", "BOOLEAN"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "module"),
        description="Agreement check between subsystem labels and import communities",
    ),
    "analytics.graph_metrics_functions_ext": TableSchema(
        schema="analytics",
        name="graph_metrics_functions_ext",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("call_betweenness", "DOUBLE"),
            Column("call_closeness", "DOUBLE"),
            Column("call_eigenvector", "DOUBLE"),
            Column("call_harmonic", "DOUBLE"),
            Column("call_core_number", "INTEGER"),
            Column("call_clustering_coeff", "DOUBLE"),
            Column("call_triangle_count", "BIGINT"),
            Column("call_is_articulation", "BOOLEAN"),
            Column("call_articulation_impact", "INTEGER"),
            Column("call_is_bridge_endpoint", "BOOLEAN"),
            Column("call_component_id", "INTEGER"),
            Column("call_component_size", "INTEGER"),
            Column("call_scc_id", "INTEGER"),
            Column("call_scc_size", "INTEGER"),
            Column("call_ancestor_count", "INTEGER"),
            Column("call_descendant_count", "INTEGER"),
            Column("call_community_id", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_graph_metrics_ext_fn_goid", ("function_goid_h128",)),),
        description="Extended call graph metrics per function (centralities, components)",
    ),
    "analytics.test_graph_metrics_tests": TableSchema(
        schema="analytics",
        name="test_graph_metrics_tests",
        columns=[
            Column("test_id", "VARCHAR", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("degree", "INTEGER"),
            Column("weighted_degree", "DOUBLE"),
            Column("degree_centrality", "DOUBLE"),
            Column("proj_degree", "INTEGER"),
            Column("proj_weight", "DOUBLE"),
            Column("proj_clustering", "DOUBLE"),
            Column("proj_betweenness", "DOUBLE"),
            Column("risk_weighted_degree", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("test_id", "repo", "commit"),
        description="Graph metrics for tests in the test-function bipartite graph",
    ),
    "analytics.test_graph_metrics_functions": TableSchema(
        schema="analytics",
        name="test_graph_metrics_functions",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("tests_degree", "INTEGER"),
            Column("tests_weighted_degree", "DOUBLE"),
            Column("tests_degree_centrality", "DOUBLE"),
            Column("proj_degree", "INTEGER"),
            Column("proj_weight", "DOUBLE"),
            Column("proj_clustering", "DOUBLE"),
            Column("proj_betweenness", "DOUBLE"),
            Column("tests_risk_weighted_degree", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("function_goid_h128", "repo", "commit"),
        indexes=(Index("idx_analytics_test_graph_metrics_fn_goid", ("function_goid_h128",)),),
        description="Function-side graph metrics from the test-function bipartite graph",
    ),
    "analytics.test_profile": TableSchema(
        schema="analytics",
        name="test_profile",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("test_id", "VARCHAR", nullable=False),
            Column("test_goid_h128", "DECIMAL(38,0)"),
            Column("urn", "VARCHAR"),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("module", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("kind", "VARCHAR"),
            Column("status", "VARCHAR"),
            Column("duration_ms", "DOUBLE"),
            Column("markers", "JSON"),
            Column("flaky", "BOOLEAN"),
            Column("last_run_at", "TIMESTAMP"),
            Column("functions_covered", "JSON"),
            Column("functions_covered_count", "INTEGER"),
            Column("primary_function_goids", "JSON"),
            Column("subsystems_covered", "JSON"),
            Column("subsystems_covered_count", "INTEGER"),
            Column("primary_subsystem_id", "VARCHAR"),
            Column("assert_count", "INTEGER"),
            Column("raise_count", "INTEGER"),
            Column("uses_parametrize", "BOOLEAN"),
            Column("uses_fixtures", "BOOLEAN"),
            Column("io_bound", "BOOLEAN"),
            Column("uses_network", "BOOLEAN"),
            Column("uses_db", "BOOLEAN"),
            Column("uses_filesystem", "BOOLEAN"),
            Column("uses_subprocess", "BOOLEAN"),
            Column("flakiness_score", "DOUBLE"),
            Column("importance_score", "DOUBLE"),
            Column("notes", "VARCHAR"),
            Column("tg_degree", "INTEGER"),
            Column("tg_weighted_degree", "DOUBLE"),
            Column("tg_proj_degree", "INTEGER"),
            Column("tg_proj_weight", "DOUBLE"),
            Column("tg_proj_clustering", "DOUBLE"),
            Column("tg_proj_betweenness", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "test_id"),
        indexes=(Index("idx_analytics_test_profile_test_id", ("test_id",)),),
        description=(
            "Per-test profile combining execution status, coverage footprint, AST metrics, IO usage, "
            "and flakiness/importance heuristics."
        ),
    ),
    "analytics.behavioral_coverage": TableSchema(
        schema="analytics",
        name="behavioral_coverage",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("test_id", "VARCHAR", nullable=False),
            Column("test_goid_h128", "DECIMAL(38,0)"),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR"),
            Column("behavior_tags", "JSON", nullable=False),
            Column("tag_source", "VARCHAR", nullable=False),
            Column("heuristic_version", "VARCHAR"),
            Column("llm_model", "VARCHAR"),
            Column("llm_run_id", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "test_id"),
        indexes=(Index("idx_analytics_behavioral_cov_test_id", ("test_id",)),),
        description="Behavioral coverage tags per test with heuristic/LLM provenance.",
    ),
    "analytics.cfg_block_metrics": TableSchema(
        schema="analytics",
        name="cfg_block_metrics",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("block_idx", "INTEGER", nullable=False),
            Column("is_entry", "BOOLEAN"),
            Column("is_exit", "BOOLEAN"),
            Column("is_branch", "BOOLEAN"),
            Column("is_join", "BOOLEAN"),
            Column("dom_depth", "INTEGER"),
            Column("dominates_exit", "BOOLEAN"),
            Column("bc_betweenness", "DOUBLE"),
            Column("bc_closeness", "DOUBLE"),
            Column("bc_eigenvector", "DOUBLE"),
            Column("in_loop_scc", "BOOLEAN"),
            Column("loop_header", "BOOLEAN"),
            Column("loop_nesting_depth", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128", "block_idx"),
        indexes=(Index("idx_analytics_cfg_block_fn", ("function_goid_h128",)),),
        description="Control-flow graph block-level metrics per function",
    ),
    "analytics.cfg_function_metrics": TableSchema(
        schema="analytics",
        name="cfg_function_metrics",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("module", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("cfg_block_count", "INTEGER"),
            Column("cfg_edge_count", "INTEGER"),
            Column("cfg_has_cycles", "BOOLEAN"),
            Column("cfg_scc_count", "INTEGER"),
            Column("cfg_longest_path_len", "INTEGER"),
            Column("cfg_avg_shortest_path_len", "DOUBLE"),
            Column("cfg_branching_factor_mean", "DOUBLE"),
            Column("cfg_branching_factor_max", "INTEGER"),
            Column("cfg_linear_block_fraction", "DOUBLE"),
            Column("cfg_dom_tree_height", "INTEGER"),
            Column("cfg_dominance_frontier_size_mean", "DOUBLE"),
            Column("cfg_dominance_frontier_size_max", "INTEGER"),
            Column("cfg_loop_count", "INTEGER"),
            Column("cfg_loop_nesting_depth_max", "INTEGER"),
            Column("cfg_bc_betweenness_max", "DOUBLE"),
            Column("cfg_bc_betweenness_mean", "DOUBLE"),
            Column("cfg_bc_closeness_mean", "DOUBLE"),
            Column("cfg_bc_eigenvector_max", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_cfg_fn_goid", ("function_goid_h128",)),),
        description="Control-flow graph summary metrics per function",
    ),
    "analytics.cfg_function_metrics_ext": TableSchema(
        schema="analytics",
        name="cfg_function_metrics_ext",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("unreachable_block_count", "INTEGER"),
            Column("loop_header_count", "INTEGER"),
            Column("true_edge_count", "INTEGER"),
            Column("false_edge_count", "INTEGER"),
            Column("back_edge_count", "INTEGER"),
            Column("exception_edge_count", "INTEGER"),
            Column("fallthrough_edge_count", "INTEGER"),
            Column("loop_edge_count", "INTEGER"),
            Column("entry_exit_simple_paths", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_cfg_fn_ext_goid", ("function_goid_h128",)),),
        description="Extended control-flow graph metrics per function",
    ),
    "analytics.dfg_block_metrics": TableSchema(
        schema="analytics",
        name="dfg_block_metrics",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("block_idx", "INTEGER", nullable=False),
            Column("dfg_in_degree", "INTEGER"),
            Column("dfg_out_degree", "INTEGER"),
            Column("dfg_phi_in_degree", "INTEGER"),
            Column("dfg_phi_out_degree", "INTEGER"),
            Column("dfg_bc_betweenness", "DOUBLE"),
            Column("dfg_bc_closeness", "DOUBLE"),
            Column("dfg_bc_eigenvector", "DOUBLE"),
            Column("dfg_in_chain", "BOOLEAN"),
            Column("dfg_in_scc", "BOOLEAN"),
            Column("created_at", "TIMESTAMP", nullable=False),
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128", "block_idx"),
        indexes=(Index("idx_analytics_dfg_block_fn", ("function_goid_h128",)),),
        description="Data-flow graph block-level metrics per function",
    ),
    "analytics.dfg_function_metrics": TableSchema(
        schema="analytics",
        name="dfg_function_metrics",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("module", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("dfg_block_count", "INTEGER"),
            Column("dfg_edge_count", "INTEGER"),
            Column("dfg_phi_edge_count", "INTEGER"),
            Column("dfg_symbol_count", "INTEGER"),
            Column("dfg_component_count", "INTEGER"),
            Column("dfg_scc_count", "INTEGER"),
            Column("dfg_has_cycles", "BOOLEAN"),
            Column("dfg_longest_chain_len", "INTEGER"),
            Column("dfg_avg_shortest_path_len", "DOUBLE"),
            Column("dfg_avg_in_degree", "DOUBLE"),
            Column("dfg_avg_out_degree", "DOUBLE"),
            Column("dfg_max_in_degree", "INTEGER"),
            Column("dfg_max_out_degree", "INTEGER"),
            Column("dfg_branchy_block_fraction", "DOUBLE"),
            Column("dfg_bc_betweenness_max", "DOUBLE"),
            Column("dfg_bc_betweenness_mean", "DOUBLE"),
            Column("dfg_bc_eigenvector_max", "DOUBLE"),
            Column("created_at", "TIMESTAMP", nullable=False),
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_dfg_fn_goid", ("function_goid_h128",)),),
        description="Data-flow graph summary metrics per function",
    ),
    "analytics.dfg_function_metrics_ext": TableSchema(
        schema="analytics",
        name="dfg_function_metrics_ext",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("data_flow_edge_count", "INTEGER"),
            Column("intra_block_edge_count", "INTEGER"),
            Column("use_kind_phi_count", "INTEGER"),
            Column("use_kind_data_flow_count", "INTEGER"),
            Column("use_kind_intra_block_count", "INTEGER"),
            Column("use_kind_other_count", "INTEGER"),
            Column("phi_edge_ratio", "DOUBLE"),
            Column("entry_exit_simple_paths", "INTEGER"),
            Column("created_at", "TIMESTAMP", nullable=False),
            Column("metrics_version", "INTEGER"),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_dfg_fn_ext_goid", ("function_goid_h128",)),),
        description="Extended data-flow graph metrics per function",
    ),
    "analytics.function_history": TableSchema(
        schema="analytics",
        name="function_history",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("urn", "VARCHAR", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR", nullable=False),
            Column("created_in_commit", "VARCHAR"),
            Column("created_at", "TIMESTAMP"),
            Column("last_modified_commit", "VARCHAR"),
            Column("last_modified_at", "TIMESTAMP"),
            Column("age_days", "INTEGER"),
            Column("commit_count", "INTEGER", nullable=False),
            Column("author_count", "INTEGER", nullable=False),
            Column("lines_added", "BIGINT", nullable=False),
            Column("lines_deleted", "BIGINT", nullable=False),
            Column("churn_score", "DOUBLE", nullable=False),
            Column("stability_bucket", "VARCHAR", nullable=False),
            Column("history_window_start", "TIMESTAMP"),
            Column("history_window_end", "TIMESTAMP"),
            Column("created_at_row", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(
            Index("idx_analytics_function_history_goid", ("function_goid_h128",)),
            Index("idx_analytics_function_history_repo_commit", ("repo", "commit")),
        ),
        description=(
            "Per-function compressed git history & churn metrics derived from file history "
            "and GOID spans."
        ),
    ),
    "analytics.function_profile": TableSchema(
        schema="analytics",
        name="function_profile",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)"),
            Column("urn", "VARCHAR"),
            Column("repo", "VARCHAR"),
            Column("commit", "VARCHAR"),
            Column("rel_path", "VARCHAR"),
            Column("module", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("kind", "VARCHAR"),
            Column("qualname", "VARCHAR"),
            Column("start_line", "INTEGER"),
            Column("end_line", "INTEGER"),
            Column("loc", "INTEGER"),
            Column("logical_loc", "INTEGER"),
            Column("cyclomatic_complexity", "INTEGER"),
            Column("complexity_bucket", "VARCHAR"),
            Column("param_count", "INTEGER"),
            Column("positional_params", "INTEGER"),
            Column("keyword_params", "INTEGER"),
            Column("vararg", "BOOLEAN"),
            Column("kwarg", "BOOLEAN"),
            Column("max_nesting_depth", "INTEGER"),
            Column("stmt_count", "INTEGER"),
            Column("decorator_count", "INTEGER"),
            Column("has_docstring", "BOOLEAN"),
            Column("total_params", "INTEGER"),
            Column("annotated_params", "INTEGER"),
            Column("return_type", "VARCHAR"),
            Column("param_types", "JSON"),
            Column("fully_typed", "BOOLEAN"),
            Column("partial_typed", "BOOLEAN"),
            Column("untyped", "BOOLEAN"),
            Column("typedness_bucket", "VARCHAR"),
            Column("typedness_source", "VARCHAR"),
            Column("file_typed_ratio", "DOUBLE"),
            Column("static_error_count", "INTEGER"),
            Column("has_static_errors", "BOOLEAN"),
            Column("executable_lines", "INTEGER"),
            Column("covered_lines", "INTEGER"),
            Column("coverage_ratio", "DOUBLE"),
            Column("tested", "BOOLEAN"),
            Column("untested_reason", "VARCHAR"),
            Column("tests_touching", "INTEGER"),
            Column("failing_tests", "INTEGER"),
            Column("slow_tests", "INTEGER"),
            Column("flaky_tests", "INTEGER"),
            Column("last_test_status", "VARCHAR"),
            Column("dominant_test_status", "VARCHAR"),
            Column("slow_test_threshold_ms", "DOUBLE"),
            Column("created_in_commit", "VARCHAR"),
            Column("created_at_history", "TIMESTAMP"),
            Column("last_modified_commit", "VARCHAR"),
            Column("last_modified_at", "TIMESTAMP"),
            Column("age_days", "INTEGER"),
            Column("commit_count", "INTEGER"),
            Column("author_count", "INTEGER"),
            Column("lines_added", "BIGINT"),
            Column("lines_deleted", "BIGINT"),
            Column("churn_score", "DOUBLE"),
            Column("stability_bucket", "VARCHAR"),
            Column("call_fan_in", "INTEGER"),
            Column("call_fan_out", "INTEGER"),
            Column("call_edge_in_count", "INTEGER"),
            Column("call_edge_out_count", "INTEGER"),
            Column("call_is_leaf", "BOOLEAN"),
            Column("call_is_entrypoint", "BOOLEAN"),
            Column("call_is_public", "BOOLEAN"),
            Column("risk_score", "DOUBLE"),
            Column("risk_level", "VARCHAR"),
            Column("risk_component_coverage", "DOUBLE"),
            Column("risk_component_complexity", "DOUBLE"),
            Column("risk_component_static", "DOUBLE"),
            Column("risk_component_hotspot", "DOUBLE"),
            Column("is_pure", "BOOLEAN"),
            Column("uses_io", "BOOLEAN"),
            Column("touches_db", "BOOLEAN"),
            Column("uses_time", "BOOLEAN"),
            Column("uses_randomness", "BOOLEAN"),
            Column("modifies_globals", "BOOLEAN"),
            Column("modifies_closure", "BOOLEAN"),
            Column("spawns_threads_or_tasks", "BOOLEAN"),
            Column("has_transitive_effects", "BOOLEAN"),
            Column("purity_confidence", "DOUBLE"),
            Column("param_nullability_json", "JSON"),
            Column("return_nullability", "VARCHAR"),
            Column("has_preconditions", "BOOLEAN"),
            Column("has_postconditions", "BOOLEAN"),
            Column("has_raises", "BOOLEAN"),
            Column("contract_confidence", "DOUBLE"),
            Column("role", "VARCHAR"),
            Column("framework", "VARCHAR"),
            Column("role_confidence", "DOUBLE"),
            Column("role_sources_json", "JSON"),
            Column("tags", "JSON"),
            Column("owners", "JSON"),
            Column("doc_short", "VARCHAR"),
            Column("doc_long", "VARCHAR"),
            Column("doc_params", "JSON"),
            Column("doc_returns", "JSON"),
            Column("created_at", "TIMESTAMP"),
        ],
        indexes=(
            Index("idx_analytics_function_profile_goid", ("function_goid_h128",)),
            Index("idx_analytics_function_profile_repo_commit", ("repo", "commit")),
        ),
        description=(
            "Denormalized per-function profile combining risk, coverage, tests, docs, and graph "
            "metrics"
        ),
    ),
    "analytics.file_profile": TableSchema(
        schema="analytics",
        name="file_profile",
        columns=[
            Column("repo", "VARCHAR"),
            Column("commit", "VARCHAR"),
            Column("rel_path", "VARCHAR"),
            Column("module", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("node_count", "INTEGER"),
            Column("function_count", "INTEGER"),
            Column("class_count", "INTEGER"),
            Column("avg_depth", "DOUBLE"),
            Column("max_depth", "INTEGER"),
            Column("ast_complexity", "DOUBLE"),
            Column("hotspot_score", "DOUBLE"),
            Column("commit_count", "INTEGER"),
            Column("author_count", "INTEGER"),
            Column("lines_added", "INTEGER"),
            Column("lines_deleted", "INTEGER"),
            Column("annotation_ratio", "DOUBLE"),
            Column("untyped_defs", "INTEGER"),
            Column("overlay_needed", "BOOLEAN"),
            Column("type_error_count", "INTEGER"),
            Column("static_error_count", "INTEGER"),
            Column("has_static_errors", "BOOLEAN"),
            Column("total_functions", "INTEGER"),
            Column("public_functions", "INTEGER"),
            Column("avg_loc", "DOUBLE"),
            Column("max_loc", "INTEGER"),
            Column("avg_cyclomatic_complexity", "DOUBLE"),
            Column("max_cyclomatic_complexity", "INTEGER"),
            Column("high_risk_function_count", "INTEGER"),
            Column("medium_risk_function_count", "INTEGER"),
            Column("max_risk_score", "DOUBLE"),
            Column("file_coverage_ratio", "DOUBLE"),
            Column("tested_function_count", "INTEGER"),
            Column("untested_function_count", "INTEGER"),
            Column("tests_touching", "INTEGER"),
            Column("tags", "JSON"),
            Column("owners", "JSON"),
            Column("created_at", "TIMESTAMP"),
        ],
        indexes=(
            Index(
                "idx_analytics_file_profile_repo_commit_relpath",
                ("repo", "commit", "rel_path"),
            ),
        ),
        description="Per-file aggregation of structure, risk, coverage, and ownership",
    ),
    "analytics.history_timeseries": TableSchema(
        schema="analytics",
        name="history_timeseries",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("entity_kind", "VARCHAR", nullable=False),
            Column("entity_stable_id", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)"),
            Column("module", "VARCHAR"),
            Column("rel_path", "VARCHAR", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("qualname", "VARCHAR"),
            Column("commit", "VARCHAR", nullable=False),
            Column("commit_ts", "TIMESTAMP", nullable=False),
            Column("loc", "INTEGER"),
            Column("cyclomatic_complexity", "INTEGER"),
            Column("coverage_ratio", "DOUBLE"),
            Column("static_error_count", "INTEGER"),
            Column("typedness_bucket", "VARCHAR"),
            Column("risk_score", "DOUBLE"),
            Column("risk_level", "VARCHAR"),
            Column("bucket_label", "VARCHAR"),
            Column("created_at_row", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "entity_kind", "entity_stable_id", "commit"),
        indexes=(
            Index(
                "idx_analytics_history_timeseries_entity",
                ("repo", "entity_kind", "entity_stable_id"),
            ),
        ),
        description="Per-commit metrics for selected functions/modules for temporal analysis.",
    ),
    "analytics.module_profile": TableSchema(
        schema="analytics",
        name="module_profile",
        columns=[
            Column("repo", "VARCHAR"),
            Column("commit", "VARCHAR"),
            Column("module", "VARCHAR"),
            Column("path", "VARCHAR"),
            Column("language", "VARCHAR"),
            Column("file_count", "INTEGER"),
            Column("total_loc", "INTEGER"),
            Column("total_logical_loc", "INTEGER"),
            Column("function_count", "INTEGER"),
            Column("class_count", "INTEGER"),
            Column("avg_file_complexity", "DOUBLE"),
            Column("max_file_complexity", "DOUBLE"),
            Column("high_risk_function_count", "INTEGER"),
            Column("medium_risk_function_count", "INTEGER"),
            Column("low_risk_function_count", "INTEGER"),
            Column("max_risk_score", "DOUBLE"),
            Column("avg_risk_score", "DOUBLE"),
            Column("module_coverage_ratio", "DOUBLE"),
            Column("tested_function_count", "INTEGER"),
            Column("untested_function_count", "INTEGER"),
            Column("import_fan_in", "INTEGER"),
            Column("import_fan_out", "INTEGER"),
            Column("cycle_group", "INTEGER"),
            Column("in_cycle", "BOOLEAN"),
            Column("role", "VARCHAR"),
            Column("role_confidence", "DOUBLE"),
            Column("role_sources_json", "JSON"),
            Column("tags", "JSON"),
            Column("owners", "JSON"),
            Column("created_at", "TIMESTAMP"),
        ],
        indexes=(
            Index(
                "idx_analytics_module_profile_repo_commit_module",
                ("repo", "commit", "module"),
            ),
        ),
        description="Per-module summary of size, risk, coverage, imports, and ownership",
    ),
    "analytics.semantic_roles_functions": TableSchema(
        schema="analytics",
        name="semantic_roles_functions",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("role", "VARCHAR"),
            Column("framework", "VARCHAR"),
            Column("role_confidence", "DOUBLE"),
            Column("role_sources_json", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "function_goid_h128"),
        indexes=(Index("idx_analytics_semantic_roles_fn", ("function_goid_h128",)),),
        description="Semantic role classification per function",
    ),
    "analytics.semantic_roles_modules": TableSchema(
        schema="analytics",
        name="semantic_roles_modules",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("role", "VARCHAR"),
            Column("role_confidence", "DOUBLE"),
            Column("role_sources_json", "JSON"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "module"),
        indexes=(Index("idx_analytics_semantic_roles_mod", ("module",)),),
        description="Semantic role classification per module",
    ),
    "analytics.subsystems": TableSchema(
        schema="analytics",
        name="subsystems",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("subsystem_id", "VARCHAR", nullable=False),
            Column("name", "VARCHAR", nullable=False),
            Column("description", "VARCHAR"),
            Column("module_count", "INTEGER", nullable=False),
            Column("modules_json", "JSON", nullable=False),
            Column("entrypoints_json", "JSON"),
            Column("internal_edge_count", "INTEGER", nullable=False),
            Column("external_edge_count", "INTEGER", nullable=False),
            Column("fan_in", "INTEGER", nullable=False),
            Column("fan_out", "INTEGER", nullable=False),
            Column("function_count", "INTEGER", nullable=False),
            Column("avg_risk_score", "DOUBLE"),
            Column("max_risk_score", "DOUBLE"),
            Column("high_risk_function_count", "INTEGER", nullable=False),
            Column("risk_level", "VARCHAR"),
            Column("created_at", "TIMESTAMP", nullable=False),
        ],
        primary_key=("repo", "commit", "subsystem_id"),
        description="Inferred architectural subsystems with summary metrics",
    ),
    "analytics.subsystem_modules": TableSchema(
        schema="analytics",
        name="subsystem_modules",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("subsystem_id", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("role", "VARCHAR"),
        ],
        primary_key=("repo", "commit", "subsystem_id", "module"),
        indexes=(Index("idx_analytics_subsystem_modules_module", ("module",)),),
        description="Mapping of subsystems to member modules",
    ),
    "analytics.hotspots": TableSchema(
        schema="analytics",
        name="hotspots",
        columns=[
            Column("rel_path", "VARCHAR"),
            Column("commit_count", "INTEGER"),
            Column("author_count", "INTEGER"),
            Column("lines_added", "INTEGER"),
            Column("lines_deleted", "INTEGER"),
            Column("complexity", "DOUBLE"),
            Column("score", "DOUBLE"),
        ],
        description="File-level hotspot scores",
    ),
    "graph.call_graph_nodes": TableSchema(
        schema="graph",
        name="call_graph_nodes",
        columns=[
            Column("goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("arity", "INTEGER", nullable=False),
            Column("is_public", "BOOLEAN", nullable=False),
            Column("rel_path", "VARCHAR", nullable=False),
        ],
        primary_key=("goid_h128",),
        description="Functions and methods participating in the call graph",
    ),
    "graph.call_graph_edges": TableSchema(
        schema="graph",
        name="call_graph_edges",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("caller_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("callee_goid_h128", "DECIMAL(38,0)"),
            Column("callsite_path", "VARCHAR", nullable=False),
            Column("callsite_line", "INTEGER", nullable=False),
            Column("callsite_col", "INTEGER", nullable=False),
            Column("language", "VARCHAR", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("resolved_via", "VARCHAR"),
            Column("confidence", "DOUBLE"),
            Column("evidence_json", "JSON"),
        ],
        indexes=(
            Index("idx_graph_call_edges_repo_commit", ("repo", "commit")),
            Index("idx_graph_call_edges_caller", ("caller_goid_h128",)),
            Index("idx_graph_call_edges_callee", ("callee_goid_h128",)),
        ),
        description="Caller->callee edges with callsite evidence",
    ),
    "graph.import_graph_edges": TableSchema(
        schema="graph",
        name="import_graph_edges",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("src_module", "VARCHAR", nullable=False),
            Column("dst_module", "VARCHAR", nullable=False),
            Column("src_fan_out", "INTEGER", nullable=False),
            Column("dst_fan_in", "INTEGER", nullable=False),
            Column("cycle_group", "INTEGER", nullable=False),
            Column("module_layer", "INTEGER"),
        ],
        indexes=(
            Index("idx_graph_import_edges_repo_commit", ("repo", "commit")),
            Index("idx_graph_import_edges_src", ("src_module",)),
            Index("idx_graph_import_edges_dst", ("dst_module",)),
        ),
        description="Module-level import edges with fan-in/out metrics",
    ),
    "graph.import_modules": TableSchema(
        schema="graph",
        name="import_modules",
        columns=[
            Column("repo", "VARCHAR", nullable=False),
            Column("commit", "VARCHAR", nullable=False),
            Column("module", "VARCHAR", nullable=False),
            Column("scc_id", "INTEGER", nullable=False),
            Column("component_size", "INTEGER", nullable=False),
            Column("layer", "INTEGER"),
            Column("cycle_group", "INTEGER", nullable=False),
        ],
        indexes=(
            Index("idx_graph_import_modules_repo_commit", ("repo", "commit")),
            Index("idx_graph_import_modules_module", ("module",)),
        ),
        description="Per-module import graph condensation metadata keyed by repo/commit",
    ),
    "graph.cfg_blocks": TableSchema(
        schema="graph",
        name="cfg_blocks",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("block_idx", "INTEGER", nullable=False),
            Column("block_id", "VARCHAR", nullable=False),
            Column("label", "VARCHAR", nullable=False),
            Column("file_path", "VARCHAR", nullable=False),
            Column("start_line", "INTEGER", nullable=False),
            Column("end_line", "INTEGER", nullable=False),
            Column("kind", "VARCHAR", nullable=False),
            Column("stmts_json", "JSON", nullable=False),
            Column("in_degree", "INTEGER", nullable=False),
            Column("out_degree", "INTEGER", nullable=False),
        ],
        primary_key=("function_goid_h128", "block_idx"),
        indexes=(Index("idx_graph_cfg_blocks_fn", ("function_goid_h128",)),),
        description="Control-flow blocks per function",
    ),
    "graph.cfg_edges": TableSchema(
        schema="graph",
        name="cfg_edges",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("src_block_id", "VARCHAR", nullable=False),
            Column("dst_block_id", "VARCHAR", nullable=False),
            Column("edge_kind", "VARCHAR"),
        ],
        indexes=(Index("idx_graph_cfg_edges_fn", ("function_goid_h128",)),),
        description="Control-flow edges between blocks",
    ),
    "graph.dfg_edges": TableSchema(
        schema="graph",
        name="dfg_edges",
        columns=[
            Column("function_goid_h128", "DECIMAL(38,0)", nullable=False),
            Column("src_block_id", "VARCHAR", nullable=False),
            Column("dst_block_id", "VARCHAR", nullable=False),
            Column("src_var", "VARCHAR"),
            Column("dst_var", "VARCHAR"),
            Column("edge_kind", "VARCHAR"),
            Column("via_phi", "BOOLEAN"),
            Column("use_kind", "VARCHAR"),
        ],
        indexes=(Index("idx_graph_dfg_edges_fn", ("function_goid_h128",)),),
        description="Data-flow edges between blocks/vars",
    ),
    "graph.symbol_use_edges": TableSchema(
        schema="graph",
        name="symbol_use_edges",
        columns=[
            Column("symbol", "VARCHAR", nullable=False),
            Column("def_path", "VARCHAR", nullable=False),
            Column("use_path", "VARCHAR", nullable=False),
            Column("same_file", "BOOLEAN", nullable=False),
            Column("same_module", "BOOLEAN", nullable=False),
            Column("def_goid_h128", "DECIMAL(38,0)"),
            Column("use_goid_h128", "DECIMAL(38,0)"),
        ],
        primary_key=("symbol", "def_path", "use_path"),
        indexes=(Index("idx_graph_symbol_use_symbol", ("symbol",)),),
        description="Definition-to-use edges derived from SCIP",
    ),
}
