"""Generated insert methods for table accessors.

AUTO-GENERATED by tools/generate_accessor_inserts.py
Do not edit manually. Regenerate with:
    python -m tools.generate_accessor_inserts > src/codeintel/storage/gateway/_generated_inserts.py
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any

__all__ = [
    "AnalyticsTableInsertsMixin",
    "CoreTableInsertsMixin",
    "GraphTableInsertsMixin",
]


class CoreTableInsertsMixin:
    """Generated insert methods for core schema tables.

    This class provides typed insert methods that delegate to the
    BaseTableAccessor._insert_rows method. Methods are generated from
    TABLE_SCHEMAS to ensure type safety.

    Note: Some tables have special handling (e.g., insert_modules,
    insert_symbol_use_edges) and are defined manually in accessors.py.
    """

    # Type annotation for _insert_rows inherited from BaseTableAccessor
    _insert_rows: Any

    def insert_ast_metrics(
        self,
        rows: Iterable[tuple[str, int, int, int, float, int, float, str]],
    ) -> None:
        """Insert rows into core.ast_metrics.

        Parameters
        ----------
        rows
            Iterable of (rel_path, node_count, function_count, class_count, avg_depth, max_depth, complexity, generated_at).
        """
        self._insert_rows("core.ast_metrics", rows)

    def insert_ast_nodes(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                str | None,
                str | None,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into core.ast_nodes.

        Parameters
        ----------
        rows
            Iterable of (path, node_type, name, qualname, lineno, end_lineno, decorator_start_line, decorator_end_line, ...).
        """
        self._insert_rows("core.ast_nodes", rows)

    def insert_cst_nodes(
        self,
        rows: Iterable[tuple[str, str, str, str, str | None, str | None, str | None]],
    ) -> None:
        """Insert rows into core.cst_nodes.

        Parameters
        ----------
        rows
            Iterable of (path, node_id, kind, span, text_preview, parents, qnames).
        """
        self._insert_rows("core.cst_nodes", rows)

    def insert_docstrings(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                str,
                str,
                int | None,
                int | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into core.docstrings.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, rel_path, module, qualname, kind, lineno, end_lineno, ...).
        """
        self._insert_rows("core.docstrings", rows)

    def insert_file_state(
        self,
        rows: Iterable[tuple[str, str, str, str, int, int, str]],
    ) -> None:
        """Insert rows into core.file_state.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, rel_path, language, size_bytes, mtime_ns, content_hash).
        """
        self._insert_rows("core.file_state", rows)

    def insert_goid_crosswalk(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                str,
                str,
                int | None,
                int | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into core.goid_crosswalk.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, goid, lang, module_path, file_path, start_line, end_line, ...).
        """
        self._insert_rows("core.goid_crosswalk", rows)

    def insert_goids(
        self,
        rows: Iterable[
            tuple[
                float,
                str,
                str,
                str,
                str,
                str,
                str,
                str,
                int | None,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into core.goids.

        Parameters
        ----------
        rows
            Iterable of (goid_h128, urn, repo, commit, rel_path, language, kind, qualname, ...).
        """
        self._insert_rows("core.goids", rows)

    def insert_ingest_runs(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                str,
                str,
                str | None,
                float | None,
                int,
                int,
                str,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                float | None,
                float | None,
                bool | None,
            ]
        ],
    ) -> None:
        """Insert rows into core.ingest_runs.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, step, run_id, mode, started_at, finished_at, duration_s, ...).
        """
        self._insert_rows("core.ingest_runs", rows)

    def insert_repo_map(
        self,
        rows: Iterable[tuple[str, str, str | None, str | None, str | None]],
    ) -> None:
        """Insert rows into core.repo_map.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, modules, overlays, generated_at).
        """
        self._insert_rows("core.repo_map", rows)


class GraphTableInsertsMixin:
    """Generated insert methods for graph schema tables.

    This class provides typed insert methods that delegate to the
    BaseTableAccessor._insert_rows method. Methods are generated from
    TABLE_SCHEMAS to ensure type safety.

    Note: Some tables have special handling (e.g., insert_modules,
    insert_symbol_use_edges) and are defined manually in accessors.py.
    """

    # Type annotation for _insert_rows inherited from BaseTableAccessor
    _insert_rows: Any

    def insert_call_graph_edges(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                float,
                float | None,
                str,
                int,
                int,
                str,
                str,
                str | None,
                float | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into graph.call_graph_edges.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, caller_goid_h128, callee_goid_h128, callsite_path, callsite_line, callsite_col, language, ...).
        """
        self._insert_rows("graph.call_graph_edges", rows)

    def insert_call_graph_nodes(
        self,
        rows: Iterable[tuple[float, str, str, int, bool, str]],
    ) -> None:
        """Insert rows into graph.call_graph_nodes.

        Parameters
        ----------
        rows
            Iterable of (goid_h128, language, kind, arity, is_public, rel_path).
        """
        self._insert_rows("graph.call_graph_nodes", rows)

    def insert_cfg_blocks(
        self,
        rows: Iterable[
            tuple[
                float,
                int,
                str,
                str,
                str,
                int,
                int,
                str,
                str,
                int,
                int,
            ]
        ],
    ) -> None:
        """Insert rows into graph.cfg_blocks.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, block_idx, block_id, label, file_path, start_line, end_line, kind, ...).
        """
        self._insert_rows("graph.cfg_blocks", rows)

    def insert_cfg_edges(
        self,
        rows: Iterable[tuple[float, str, str, str | None]],
    ) -> None:
        """Insert rows into graph.cfg_edges.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, src_block_id, dst_block_id, edge_kind).
        """
        self._insert_rows("graph.cfg_edges", rows)

    def insert_dfg_edges(
        self,
        rows: Iterable[
            tuple[float, str, str, str | None, str | None, str | None, bool | None, str | None]
        ],
    ) -> None:
        """Insert rows into graph.dfg_edges.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, src_block_id, dst_block_id, src_var, dst_var, edge_kind, via_phi, use_kind).
        """
        self._insert_rows("graph.dfg_edges", rows)

    def insert_import_graph_edges(
        self,
        rows: Iterable[tuple[str, str, str, str, int, int, int, int | None]],
    ) -> None:
        """Insert rows into graph.import_graph_edges.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, src_module, dst_module, src_fan_out, dst_fan_in, cycle_group, module_layer).
        """
        self._insert_rows("graph.import_graph_edges", rows)

    def insert_import_modules(
        self,
        rows: Iterable[tuple[str, str, str, int, int, int | None, int]],
    ) -> None:
        """Insert rows into graph.import_modules.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, module, scc_id, component_size, layer, cycle_group).
        """
        self._insert_rows("graph.import_modules", rows)


class AnalyticsTableInsertsMixin:
    """Generated insert methods for analytics schema tables.

    This class provides typed insert methods that delegate to the
    BaseTableAccessor._insert_rows method. Methods are generated from
    TABLE_SCHEMAS to ensure type safety.

    Note: Some tables have special handling (e.g., insert_modules,
    insert_symbol_use_edges) and are defined manually in accessors.py.
    """

    # Type annotation for _insert_rows inherited from BaseTableAccessor
    _insert_rows: Any

    def insert_behavioral_coverage(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                float | None,
                str,
                str | None,
                str,
                str,
                str | None,
                str | None,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.behavioral_coverage.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, test_id, test_goid_h128, rel_path, qualname, behavior_tags, tag_source, ...).
        """
        self._insert_rows("analytics.behavioral_coverage", rows)

    def insert_cfg_block_metrics(
        self,
        rows: Iterable[
            tuple[
                float,
                str,
                str,
                int,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                int | None,
                bool | None,
                float | None,
                float | None,
                float | None,
                bool | None,
                bool | None,
                int | None,
                str,
                int | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.cfg_block_metrics.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, repo, commit, block_idx, is_entry, is_exit, is_branch, is_join, ...).
        """
        self._insert_rows("analytics.cfg_block_metrics", rows)

    def insert_cfg_function_metrics(
        self,
        rows: Iterable[
            tuple[
                float,
                str,
                str,
                str,
                str | None,
                str | None,
                int | None,
                int | None,
                bool | None,
                int | None,
                int | None,
                float | None,
                float | None,
                int | None,
                float | None,
                int | None,
                float | None,
                int | None,
                int | None,
                int | None,
                float | None,
                float | None,
                float | None,
                float | None,
                str,
                int | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.cfg_function_metrics.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, repo, commit, rel_path, module, qualname, cfg_block_count, cfg_edge_count, ...).
        """
        self._insert_rows("analytics.cfg_function_metrics", rows)

    def insert_cfg_function_metrics_ext(
        self,
        rows: Iterable[
            tuple[
                float,
                str,
                str,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                str,
                int | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.cfg_function_metrics_ext.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, repo, commit, unreachable_block_count, loop_header_count, true_edge_count, false_edge_count, back_edge_count, ...).
        """
        self._insert_rows("analytics.cfg_function_metrics_ext", rows)

    def insert_config_data_flow(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                float,
                str,
                str | None,
                str,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.config_data_flow.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, config_key, config_path, function_goid_h128, usage_kind, evidence_json, call_chain_id, call_chain_json, created_at).
        """
        self._insert_rows("analytics.config_data_flow", rows)

    def insert_config_graph_metrics_keys(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                int | None,
                float | None,
                float | None,
                float | None,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.config_graph_metrics_keys.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, config_key, degree, weighted_degree, betweenness, closeness, community_id, created_at).
        """
        self._insert_rows("analytics.config_graph_metrics_keys", rows)

    def insert_config_graph_metrics_modules(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                int | None,
                float | None,
                float | None,
                float | None,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.config_graph_metrics_modules.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, module, degree, weighted_degree, betweenness, closeness, community_id, created_at).
        """
        self._insert_rows("analytics.config_graph_metrics_modules", rows)

    def insert_config_projection_key_edges(
        self,
        rows: Iterable[tuple[str, str, str, str, float | None, str]],
    ) -> None:
        """Insert rows into analytics.config_projection_key_edges.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, src_key, dst_key, weight, created_at).
        """
        self._insert_rows("analytics.config_projection_key_edges", rows)

    def insert_config_projection_module_edges(
        self,
        rows: Iterable[tuple[str, str, str, str, float | None, str]],
    ) -> None:
        """Insert rows into analytics.config_projection_module_edges.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, src_module, dst_module, weight, created_at).
        """
        self._insert_rows("analytics.config_projection_module_edges", rows)

    def insert_config_values(
        self,
        rows: Iterable[tuple[str, str, str, str, str, str | None, str | None, int]],
    ) -> None:
        """Insert rows into analytics.config_values.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, config_path, format, key, reference_paths, reference_modules, reference_count).
        """
        self._insert_rows("analytics.config_values", rows)

    def insert_coverage_functions(
        self,
        rows: Iterable[
            tuple[
                float | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                bool | None,
                str | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.coverage_functions.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, urn, repo, commit, rel_path, language, kind, qualname, ...).
        """
        self._insert_rows("analytics.coverage_functions", rows)

    def insert_coverage_lines(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                int,
                bool,
                bool,
                int,
                int,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.coverage_lines.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, rel_path, line, is_executable, is_covered, hits, context_count, created_at).
        """
        self._insert_rows("analytics.coverage_lines", rows)

    def insert_data_model_fields(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                str | None,
                bool,
                bool,
                str | None,
                str,
                str,
                str,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.data_model_fields.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, model_id, field_name, field_type, required, has_default, default_expr, ...).
        """
        self._insert_rows("analytics.data_model_fields", rows)

    def insert_data_model_relationships(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                str | None,
                str | None,
                str,
                str,
                str | None,
                str | None,
                str | None,
                str,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.data_model_relationships.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, source_model_id, target_model_id, target_module, target_model_name, field_name, relationship_kind, ...).
        """
        self._insert_rows("analytics.data_model_relationships", rows)

    def insert_data_model_usage(
        self,
        rows: Iterable[tuple[str, str, str, float, str, str | None, str | None, str]],
    ) -> None:
        """Insert rows into analytics.data_model_usage.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, model_id, function_goid_h128, usage_kinds_json, evidence_json, context_json, created_at).
        """
        self._insert_rows("analytics.data_model_usage", rows)

    def insert_data_models(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                float | None,
                str,
                str,
                str,
                str,
                str | None,
                str | None,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.data_models.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, model_id, goid_h128, model_name, module, rel_path, model_kind, ...).
        """
        self._insert_rows("analytics.data_models", rows)

    def insert_dfg_block_metrics(
        self,
        rows: Iterable[
            tuple[
                float,
                str,
                str,
                int,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                float | None,
                float | None,
                bool | None,
                bool | None,
                str,
                int | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.dfg_block_metrics.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, repo, commit, block_idx, dfg_in_degree, dfg_out_degree, dfg_phi_in_degree, dfg_phi_out_degree, ...).
        """
        self._insert_rows("analytics.dfg_block_metrics", rows)

    def insert_dfg_function_metrics(
        self,
        rows: Iterable[
            tuple[
                float,
                str,
                str,
                str,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                bool | None,
                int | None,
                float | None,
                float | None,
                float | None,
                int | None,
                int | None,
                float | None,
                float | None,
                float | None,
                float | None,
                str,
                int | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.dfg_function_metrics.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, repo, commit, rel_path, module, qualname, dfg_block_count, dfg_edge_count, ...).
        """
        self._insert_rows("analytics.dfg_function_metrics", rows)

    def insert_dfg_function_metrics_ext(
        self,
        rows: Iterable[
            tuple[
                float,
                str,
                str,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                int | None,
                str,
                int | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.dfg_function_metrics_ext.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, repo, commit, data_flow_edge_count, intra_block_edge_count, use_kind_phi_count, use_kind_data_flow_count, use_kind_intra_block_count, ...).
        """
        self._insert_rows("analytics.dfg_function_metrics_ext", rows)

    def insert_entrypoint_tests(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                float | None,
                float | None,
                str | None,
                float | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.entrypoint_tests.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, entrypoint_id, test_id, test_goid_h128, coverage_ratio, status, duration_ms, created_at).
        """
        self._insert_rows("analytics.entrypoint_tests", rows)

    def insert_entrypoints(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                str | None,
                float,
                str,
                str,
                str,
                str,
                str | None,
                str | None,
                str | None,
                bool | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.entrypoints.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, entrypoint_id, kind, framework, handler_goid_h128, handler_urn, handler_rel_path, ...).
        """
        self._insert_rows("analytics.entrypoints", rows)

    def insert_external_dependencies(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                str | None,
                str | None,
                str | None,
                str | None,
                float | None,
                float | None,
                int,
                int,
                str,
                str,
                str | None,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.external_dependencies.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, dep_id, library, service_name, category, language, severity, ...).
        """
        self._insert_rows("analytics.external_dependencies", rows)

    def insert_external_dependency_calls(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                str | None,
                str | None,
                str | None,
                float | None,
                float | None,
                str | None,
                float,
                str,
                str,
                str,
                str,
                int,
                str,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.external_dependency_calls.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, dep_id, library, service_name, language, severity, criticality, ...).
        """
        self._insert_rows("analytics.external_dependency_calls", rows)

    def insert_file_profile(
        self,
        rows: Iterable[
            tuple[
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                float | None,
                int | None,
                float | None,
                float | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                int | None,
                bool | None,
                int | None,
                int | None,
                bool | None,
                int | None,
                int | None,
                float | None,
                int | None,
                float | None,
                int | None,
                int | None,
                int | None,
                float | None,
                float | None,
                int | None,
                int | None,
                int | None,
                str | None,
                str | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.file_profile.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, rel_path, module, language, node_count, function_count, class_count, ...).
        """
        self._insert_rows("analytics.file_profile", rows)

    def insert_function_ast_features(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                float,
                str,
                str,
                bool,
                bool,
                bool,
                bool,
                bool,
                bool,
                bool,
                bool,
                str,
                str,
                str,
                str,
                int,
                int,
                str,
                str,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.function_ast_features.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, function_goid_h128, rel_path, qualname, is_async, uses_network, uses_db, ...).
        """
        self._insert_rows("analytics.function_ast_features", rows)

    def insert_function_contracts(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                float,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                float | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.function_contracts.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, function_goid_h128, preconditions_json, postconditions_json, raises_json, param_nullability_json, return_nullability, contract_confidence, created_at).
        """
        self._insert_rows("analytics.function_contracts", rows)

    def insert_function_effects(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                float,
                bool,
                bool,
                bool,
                bool,
                bool,
                bool,
                bool,
                bool,
                bool,
                float | None,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.function_effects.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, function_goid_h128, is_pure, uses_io, touches_db, uses_time, uses_randomness, ...).
        """
        self._insert_rows("analytics.function_effects", rows)

    def insert_function_history(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                float,
                str,
                str,
                str,
                str,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int,
                int,
                int,
                int,
                float,
                str,
                str | None,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.function_history.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, function_goid_h128, urn, rel_path, module, qualname, created_in_commit, ...).
        """
        self._insert_rows("analytics.function_history", rows)

    def insert_function_metrics(
        self,
        rows: Iterable[
            tuple[
                float | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                bool | None,
                str | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.function_metrics.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, urn, repo, commit, rel_path, language, kind, qualname, ...).
        """
        self._insert_rows("analytics.function_metrics", rows)

    def insert_function_profile(
        self,
        rows: Iterable[
            tuple[
                float | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                str | None,
                int | None,
                int | None,
                int | None,
                bool | None,
                bool | None,
                int | None,
                int | None,
                int | None,
                bool | None,
                int | None,
                int | None,
                str | None,
                str | None,
                bool | None,
                bool | None,
                bool | None,
                str | None,
                str | None,
                float | None,
                int | None,
                bool | None,
                int | None,
                int | None,
                float | None,
                bool | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                str | None,
                str | None,
                float | None,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                bool | None,
                bool | None,
                bool | None,
                float | None,
                str | None,
                float | None,
                float | None,
                float | None,
                float | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                float | None,
                str | None,
                str | None,
                bool | None,
                bool | None,
                bool | None,
                float | None,
                str | None,
                str | None,
                float | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.function_profile.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, urn, repo, commit, rel_path, module, language, kind, ...).
        """
        self._insert_rows("analytics.function_profile", rows)

    def insert_function_types(
        self,
        rows: Iterable[
            tuple[
                float | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                bool | None,
                str | None,
                str | None,
                str | None,
                str | None,
                bool | None,
                bool | None,
                bool | None,
                str | None,
                str | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.function_types.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, urn, repo, commit, rel_path, language, kind, qualname, ...).
        """
        self._insert_rows("analytics.function_types", rows)

    def insert_function_validation(
        self,
        rows: Iterable[tuple[str, str, float, str, str, str, str, str]],
    ) -> None:
        """Insert rows into analytics.function_validation.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, function_goid_h128, rel_path, qualname, issue, detail, created_at).
        """
        self._insert_rows("analytics.function_validation", rows)

    def insert_goid_risk_factors(
        self,
        rows: Iterable[
            tuple[
                float | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                str | None,
                str | None,
                str | None,
                float | None,
                float | None,
                int | None,
                bool | None,
                int | None,
                int | None,
                float | None,
                bool | None,
                int | None,
                int | None,
                str | None,
                float | None,
                str | None,
                str | None,
                str | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.goid_risk_factors.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, urn, repo, commit, rel_path, language, kind, qualname, ...).
        """
        self._insert_rows("analytics.goid_risk_factors", rows)

    def insert_graph_metrics_functions(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                float,
                int,
                int,
                int,
                int,
                float | None,
                float | None,
                float | None,
                bool,
                int | None,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.graph_metrics_functions.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, function_goid_h128, call_fan_in, call_fan_out, call_in_degree, call_out_degree, call_pagerank, ...).
        """
        self._insert_rows("analytics.graph_metrics_functions", rows)

    def insert_graph_metrics_functions_ext(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                float,
                float | None,
                float | None,
                float | None,
                float | None,
                int | None,
                float | None,
                int | None,
                bool | None,
                int | None,
                bool | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.graph_metrics_functions_ext.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, function_goid_h128, call_betweenness, call_closeness, call_eigenvector, call_harmonic, call_core_number, ...).
        """
        self._insert_rows("analytics.graph_metrics_functions_ext", rows)

    def insert_graph_metrics_modules(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                int,
                int,
                int,
                int,
                float | None,
                float | None,
                float | None,
                bool,
                int | None,
                int | None,
                int,
                int,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.graph_metrics_modules.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, module, import_fan_in, import_fan_out, import_in_degree, import_out_degree, import_pagerank, ...).
        """
        self._insert_rows("analytics.graph_metrics_modules", rows)

    def insert_graph_metrics_modules_ext(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                float | None,
                float | None,
                float | None,
                float | None,
                int | None,
                float | None,
                float | None,
                bool | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.graph_metrics_modules_ext.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, module, import_betweenness, import_closeness, import_eigenvector, import_harmonic, import_k_core, ...).
        """
        self._insert_rows("analytics.graph_metrics_modules_ext", rows)

    def insert_graph_stats(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                float | None,
                float | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.graph_stats.

        Parameters
        ----------
        rows
            Iterable of (graph_name, repo, commit, node_count, edge_count, weak_component_count, scc_count, component_layers, ...).
        """
        self._insert_rows("analytics.graph_stats", rows)

    def insert_graph_validation(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                str,
                str | None,
                str | None,
                str,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.graph_validation.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, graph_name, entity_id, issue, severity, rel_path, detail, metadata, created_at).
        """
        self._insert_rows("analytics.graph_validation", rows)

    def insert_history_timeseries(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                float | None,
                str | None,
                str,
                str,
                str | None,
                str,
                str,
                int | None,
                int | None,
                float | None,
                int | None,
                str | None,
                float | None,
                str | None,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.history_timeseries.

        Parameters
        ----------
        rows
            Iterable of (repo, entity_kind, entity_stable_id, function_goid_h128, module, rel_path, language, qualname, ...).
        """
        self._insert_rows("analytics.history_timeseries", rows)

    def insert_hotspots(
        self,
        rows: Iterable[
            tuple[
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                float | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.hotspots.

        Parameters
        ----------
        rows
            Iterable of (rel_path, commit_count, author_count, lines_added, lines_deleted, complexity, score).
        """
        self._insert_rows("analytics.hotspots", rows)

    def insert_module_profile(
        self,
        rows: Iterable[
            tuple[
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                float | None,
                int | None,
                int | None,
                int | None,
                float | None,
                float | None,
                float | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                bool | None,
                str | None,
                float | None,
                str | None,
                str | None,
                str | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.module_profile.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, module, path, language, file_count, total_loc, total_logical_loc, ...).
        """
        self._insert_rows("analytics.module_profile", rows)

    def insert_semantic_roles_functions(
        self,
        rows: Iterable[
            tuple[str, str, float, str | None, str | None, float | None, str | None, str]
        ],
    ) -> None:
        """Insert rows into analytics.semantic_roles_functions.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, function_goid_h128, role, framework, role_confidence, role_sources_json, created_at).
        """
        self._insert_rows("analytics.semantic_roles_functions", rows)

    def insert_semantic_roles_modules(
        self,
        rows: Iterable[tuple[str, str, str, str | None, float | None, str | None, str]],
    ) -> None:
        """Insert rows into analytics.semantic_roles_modules.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, module, role, role_confidence, role_sources_json, created_at).
        """
        self._insert_rows("analytics.semantic_roles_modules", rows)

    def insert_static_diagnostics(
        self,
        rows: Iterable[tuple[str, str, str, int, int, int, int, bool]],
    ) -> None:
        """Insert rows into analytics.static_diagnostics.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, rel_path, pyrefly_errors, pyright_errors, ruff_errors, total_errors, has_errors).
        """
        self._insert_rows("analytics.static_diagnostics", rows)

    def insert_subsystem_agreement(
        self,
        rows: Iterable[tuple[str, str, str, str | None, int | None, bool | None, str]],
    ) -> None:
        """Insert rows into analytics.subsystem_agreement.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, module, subsystem_id, import_community_id, agrees, created_at).
        """
        self._insert_rows("analytics.subsystem_agreement", rows)

    def insert_subsystem_coverage_cache(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str | None,
                str | None,
                int | None,
                int | None,
                str | None,
                float | None,
                float | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                float | None,
                float | None,
                float | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.subsystem_coverage_cache.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, subsystem_id, name, description, module_count, function_count, risk_level, ...).
        """
        self._insert_rows("analytics.subsystem_coverage_cache", rows)

    def insert_subsystem_graph_metrics(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                float | None,
                float | None,
                float | None,
                float | None,
                float | None,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.subsystem_graph_metrics.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, subsystem_id, import_in_degree, import_out_degree, import_pagerank, import_betweenness, import_closeness, import_layer, created_at).
        """
        self._insert_rows("analytics.subsystem_graph_metrics", rows)

    def insert_subsystem_modules(
        self,
        rows: Iterable[tuple[str, str, str, str, str | None]],
    ) -> None:
        """Insert rows into analytics.subsystem_modules.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, subsystem_id, module, role).
        """
        self._insert_rows("analytics.subsystem_modules", rows)

    def insert_subsystem_profile_cache(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str | None,
                str | None,
                int | None,
                str | None,
                str | None,
                int | None,
                int | None,
                int | None,
                int | None,
                int | None,
                float | None,
                float | None,
                int | None,
                str | None,
                float | None,
                float | None,
                float | None,
                float | None,
                float | None,
                int | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.subsystem_profile_cache.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, subsystem_id, name, description, module_count, modules_json, entrypoints_json, ...).
        """
        self._insert_rows("analytics.subsystem_profile_cache", rows)

    def insert_subsystems(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                str,
                str | None,
                int,
                str,
                str | None,
                int,
                int,
                int,
                int,
                int,
                float | None,
                float | None,
                int,
                str | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.subsystems.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, subsystem_id, name, description, module_count, modules_json, entrypoints_json, ...).
        """
        self._insert_rows("analytics.subsystems", rows)

    def insert_symbol_graph_metrics_functions(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                float,
                float | None,
                float | None,
                float | None,
                float | None,
                int | None,
                float | None,
                float | None,
                int | None,
                int | None,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.symbol_graph_metrics_functions.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, function_goid_h128, symbol_betweenness, symbol_closeness, symbol_eigenvector, symbol_harmonic, symbol_k_core, ...).
        """
        self._insert_rows("analytics.symbol_graph_metrics_functions", rows)

    def insert_symbol_graph_metrics_modules(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                float | None,
                float | None,
                float | None,
                float | None,
                int | None,
                float | None,
                float | None,
                int | None,
                int | None,
                int | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.symbol_graph_metrics_modules.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, module, symbol_betweenness, symbol_closeness, symbol_eigenvector, symbol_harmonic, symbol_k_core, ...).
        """
        self._insert_rows("analytics.symbol_graph_metrics_modules", rows)

    def insert_tags_index(
        self,
        rows: Iterable[tuple[str, str | None, str | None, str | None, str | None]],
    ) -> None:
        """Insert rows into analytics.tags_index.

        Parameters
        ----------
        rows
            Iterable of (tag, description, includes, excludes, matches).
        """
        self._insert_rows("analytics.tags_index", rows)

    def insert_test_catalog(
        self,
        rows: Iterable[
            tuple[
                str,
                float | None,
                str | None,
                str,
                str,
                str,
                str | None,
                str | None,
                str | None,
                float | None,
                str | None,
                bool | None,
                bool | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.test_catalog.

        Parameters
        ----------
        rows
            Iterable of (test_id, test_goid_h128, urn, repo, commit, rel_path, qualname, kind, ...).
        """
        self._insert_rows("analytics.test_catalog", rows)

    def insert_test_coverage_edges(
        self,
        rows: Iterable[
            tuple[
                str | None,
                float | None,
                float | None,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                int | None,
                int | None,
                float | None,
                str | None,
                str | None,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.test_coverage_edges.

        Parameters
        ----------
        rows
            Iterable of (test_id, test_goid_h128, function_goid_h128, urn, repo, commit, rel_path, qualname, ...).
        """
        self._insert_rows("analytics.test_coverage_edges", rows)

    def insert_test_graph_metrics_functions(
        self,
        rows: Iterable[
            tuple[
                float,
                str,
                str,
                int | None,
                float | None,
                float | None,
                int | None,
                float | None,
                float | None,
                float | None,
                float | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.test_graph_metrics_functions.

        Parameters
        ----------
        rows
            Iterable of (function_goid_h128, repo, commit, tests_degree, tests_weighted_degree, tests_degree_centrality, proj_degree, proj_weight, ...).
        """
        self._insert_rows("analytics.test_graph_metrics_functions", rows)

    def insert_test_graph_metrics_tests(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                int | None,
                float | None,
                float | None,
                int | None,
                float | None,
                float | None,
                float | None,
                float | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.test_graph_metrics_tests.

        Parameters
        ----------
        rows
            Iterable of (test_id, repo, commit, degree, weighted_degree, degree_centrality, proj_degree, proj_weight, ...).
        """
        self._insert_rows("analytics.test_graph_metrics_tests", rows)

    def insert_test_profile(
        self,
        rows: Iterable[
            tuple[
                str,
                str,
                str,
                float | None,
                str | None,
                str,
                str | None,
                str | None,
                str | None,
                str | None,
                str | None,
                float | None,
                str | None,
                bool | None,
                str | None,
                str | None,
                int | None,
                str | None,
                str | None,
                int | None,
                str | None,
                int | None,
                int | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                bool | None,
                float | None,
                float | None,
                str | None,
                int | None,
                float | None,
                int | None,
                float | None,
                float | None,
                float | None,
                str,
            ]
        ],
    ) -> None:
        """Insert rows into analytics.test_profile.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, test_id, test_goid_h128, urn, rel_path, module, qualname, ...).
        """
        self._insert_rows("analytics.test_profile", rows)

    def insert_typedness(
        self,
        rows: Iterable[tuple[str, str, str, int, str, int, bool]],
    ) -> None:
        """Insert rows into analytics.typedness.

        Parameters
        ----------
        rows
            Iterable of (repo, commit, path, type_error_count, annotation_ratio, untyped_defs, overlay_needed).
        """
        self._insert_rows("analytics.typedness", rows)
