"""Generated table registry for insert helpers.

AUTO-GENERATED by tools/generate_accessor_inserts.py
Do not edit manually.
"""

from __future__ import annotations

from typing import Final

TableMeta = dict[str, object]
TABLE_REGISTRY: Final[dict[str, TableMeta]] = {
    "analytics.behavioral_coverage": {
        "table": "analytics.behavioral_coverage",
        "columns": ["repo", "commit", "test_id", "test_goid_h128", "rel_path", "qualname", "behavior_tags", "tag_source", "heuristic_version", "llm_model", "llm_run_id", "created_at", "test_goid_h128_1", "created_at_1"],
    },
    "analytics.cfg_block_metrics": {
        "table": "analytics.cfg_block_metrics",
        "columns": ["function_goid_h128", "repo", "commit", "block_idx", "is_entry", "is_exit", "is_branch", "is_join", "dom_depth", "dominates_exit", "bc_betweenness", "bc_closeness", "bc_eigenvector", "in_loop_scc", "loop_header", "loop_nesting_depth", "created_at", "metrics_version"],
    },
    "analytics.cfg_function_metrics": {
        "table": "analytics.cfg_function_metrics",
        "columns": ["function_goid_h128", "repo", "commit", "rel_path", "module", "qualname", "cfg_block_count", "cfg_edge_count", "cfg_has_cycles", "cfg_scc_count", "cfg_longest_path_len", "cfg_avg_shortest_path_len", "cfg_branching_factor_mean", "cfg_branching_factor_max", "cfg_linear_block_fraction", "cfg_dom_tree_height", "cfg_dominance_frontier_size_mean", "cfg_dominance_frontier_size_max", "cfg_loop_count", "cfg_loop_nesting_depth_max", "cfg_bc_betweenness_max", "cfg_bc_betweenness_mean", "cfg_bc_closeness_mean", "cfg_bc_eigenvector_max", "created_at", "metrics_version"],
    },
    "analytics.cfg_function_metrics_ext": {
        "table": "analytics.cfg_function_metrics_ext",
        "columns": ["function_goid_h128", "repo", "commit", "unreachable_block_count", "loop_header_count", "true_edge_count", "false_edge_count", "back_edge_count", "exception_edge_count", "fallthrough_edge_count", "loop_edge_count", "entry_exit_simple_paths", "created_at", "metrics_version"],
    },
    "analytics.config_data_flow": {
        "table": "analytics.config_data_flow",
        "columns": ["repo", "commit", "config_key", "config_path", "function_goid_h128", "usage_kind", "evidence_json", "call_chain_id", "call_chain_json", "created_at"],
    },
    "analytics.config_graph_metrics_keys": {
        "table": "analytics.config_graph_metrics_keys",
        "columns": ["repo", "commit", "config_key", "degree", "weighted_degree", "betweenness", "closeness", "community_id", "created_at"],
    },
    "analytics.config_graph_metrics_modules": {
        "table": "analytics.config_graph_metrics_modules",
        "columns": ["repo", "commit", "module", "degree", "weighted_degree", "betweenness", "closeness", "community_id", "created_at"],
    },
    "analytics.config_projection_key_edges": {
        "table": "analytics.config_projection_key_edges",
        "columns": ["repo", "commit", "src_key", "dst_key", "weight", "created_at"],
    },
    "analytics.config_projection_module_edges": {
        "table": "analytics.config_projection_module_edges",
        "columns": ["repo", "commit", "src_module", "dst_module", "weight", "created_at"],
    },
    "analytics.config_values": {
        "table": "analytics.config_values",
        "columns": ["repo", "commit", "config_path", "format", "key", "reference_paths", "reference_modules", "reference_count"],
    },
    "analytics.data_model_fields": {
        "table": "analytics.data_model_fields",
        "columns": ["repo", "commit", "model_id", "field_name", "field_type", "required", "has_default", "default_expr", "constraints_json", "source", "rel_path", "lineno", "created_at"],
    },
    "analytics.data_model_relationships": {
        "table": "analytics.data_model_relationships",
        "columns": ["repo", "commit", "source_model_id", "target_model_id", "target_module", "target_model_name", "field_name", "relationship_kind", "multiplicity", "via", "evidence_json", "rel_path", "lineno", "created_at"],
    },
    "analytics.data_model_usage": {
        "table": "analytics.data_model_usage",
        "columns": ["repo", "commit", "model_id", "function_goid_h128", "usage_kinds_json", "evidence_json", "context_json", "created_at"],
    },
    "analytics.data_models": {
        "table": "analytics.data_models",
        "columns": ["repo", "commit", "model_id", "goid_h128", "model_name", "module", "rel_path", "model_kind", "base_classes_json", "doc_short", "doc_long", "created_at"],
    },
    "analytics.dfg_block_metrics": {
        "table": "analytics.dfg_block_metrics",
        "columns": ["function_goid_h128", "repo", "commit", "block_idx", "dfg_in_degree", "dfg_out_degree", "dfg_phi_in_degree", "dfg_phi_out_degree", "dfg_bc_betweenness", "dfg_bc_closeness", "dfg_bc_eigenvector", "dfg_in_chain", "dfg_in_scc", "created_at", "metrics_version"],
    },
    "analytics.dfg_function_metrics": {
        "table": "analytics.dfg_function_metrics",
        "columns": ["function_goid_h128", "repo", "commit", "rel_path", "module", "qualname", "dfg_block_count", "dfg_edge_count", "dfg_phi_edge_count", "dfg_symbol_count", "dfg_component_count", "dfg_scc_count", "dfg_has_cycles", "dfg_longest_chain_len", "dfg_avg_shortest_path_len", "dfg_avg_in_degree", "dfg_avg_out_degree", "dfg_max_in_degree", "dfg_max_out_degree", "dfg_branchy_block_fraction", "dfg_bc_betweenness_max", "dfg_bc_betweenness_mean", "dfg_bc_eigenvector_max", "created_at", "metrics_version"],
    },
    "analytics.dfg_function_metrics_ext": {
        "table": "analytics.dfg_function_metrics_ext",
        "columns": ["function_goid_h128", "repo", "commit", "data_flow_edge_count", "intra_block_edge_count", "use_kind_phi_count", "use_kind_data_flow_count", "use_kind_intra_block_count", "use_kind_other_count", "phi_edge_ratio", "entry_exit_simple_paths", "created_at", "metrics_version"],
    },
    "analytics.entrypoint_tests": {
        "table": "analytics.entrypoint_tests",
        "columns": ["repo", "commit", "entrypoint_id", "test_id", "test_goid_h128", "status", "duration_ms", "created_at"],
    },
    "analytics.entrypoints": {
        "table": "analytics.entrypoints",
        "columns": ["repo", "commit", "entrypoint_id", "kind", "framework", "handler_goid_h128", "handler_urn", "handler_rel_path", "handler_module", "handler_qualname", "http_method", "route_path", "status_codes", "auth_required", "command_name", "arguments_schema", "schedule", "trigger", "extra", "subsystem_id", "subsystem_name", "tags", "owners", "tests_touching", "failing_tests", "slow_tests", "flaky_tests", "last_test_status", "created_at"],
    },
    "analytics.external_dependencies": {
        "table": "analytics.external_dependencies",
        "columns": ["repo", "commit", "dep_id", "library", "service_name", "category", "language", "severity", "criticality", "risk_score", "function_count", "callsite_count", "modules_json", "usage_modes", "config_keys", "risk_level", "created_at"],
    },
    "analytics.external_dependency_calls": {
        "table": "analytics.external_dependency_calls",
        "columns": ["repo", "commit", "dep_id", "library", "service_name", "language", "severity", "criticality", "risk_score", "matched_pattern", "function_goid_h128", "function_urn", "rel_path", "module", "qualname", "callsite_count", "modes", "evidence_json", "created_at"],
    },
    "analytics.function_ast_features": {
        "table": "analytics.function_ast_features",
        "columns": ["repo", "commit", "function_goid_h128", "rel_path", "qualname", "is_async", "uses_network", "uses_db", "uses_filesystem", "uses_subprocess", "uses_concurrency_lib", "uses_threading", "uses_asyncio_lib", "http_client_libs", "http_server_libs", "db_libs", "message_libs", "config_read_count", "feature_flag_count", "decorators", "libraries_used", "created_at"],
    },
    "analytics.function_contracts": {
        "table": "analytics.function_contracts",
        "columns": ["repo", "commit", "function_goid_h128", "preconditions_json", "postconditions_json", "raises_json", "param_nullability_json", "return_nullability", "contract_confidence", "created_at"],
    },
    "analytics.function_effects": {
        "table": "analytics.function_effects",
        "columns": ["repo", "commit", "function_goid_h128", "is_pure", "uses_io", "touches_db", "uses_time", "uses_randomness", "modifies_globals", "modifies_closure", "spawns_threads_or_tasks", "has_transitive_effects", "purity_confidence", "effects_json", "created_at"],
    },
    "analytics.function_history": {
        "table": "analytics.function_history",
        "columns": ["repo", "commit", "function_goid_h128", "urn", "rel_path", "module", "qualname", "created_in_commit", "created_at", "last_modified_commit", "last_modified_at", "age_days", "commit_count", "author_count", "lines_added", "lines_deleted", "churn_score", "stability_bucket", "history_window_start", "history_window_end", "created_at_row", "function_goid_h128_1", "created_at_1"],
    },
    "analytics.function_metrics": {
        "table": "analytics.function_metrics",
        "columns": ["function_goid_h128", "urn", "repo", "commit", "rel_path", "language", "kind", "qualname", "start_line", "end_line", "loc", "logical_loc", "param_count", "positional_params", "keyword_only_params", "has_varargs", "has_varkw", "is_async", "is_generator", "return_count", "yield_count", "raise_count", "cyclomatic_complexity", "max_nesting_depth", "stmt_count", "decorator_count", "has_docstring", "complexity_bucket", "created_at"],
    },
    "analytics.function_profile": {
        "table": "analytics.function_profile",
        "columns": ["function_goid_h128", "urn", "repo", "commit", "rel_path", "module", "language", "kind", "qualname", "start_line", "end_line", "loc", "logical_loc", "cyclomatic_complexity", "complexity_bucket", "param_count", "positional_params", "keyword_params", "vararg", "kwarg", "max_nesting_depth", "stmt_count", "decorator_count", "has_docstring", "total_params", "annotated_params", "return_type", "param_types", "fully_typed", "partial_typed", "untyped", "typedness_bucket", "typedness_source", "file_typed_ratio", "static_error_count", "has_static_errors", "executable_lines", "covered_lines", "coverage_ratio", "tested", "untested_reason", "tests_touching", "failing_tests", "slow_tests", "flaky_tests", "last_test_status", "dominant_test_status", "slow_test_threshold_ms", "created_in_commit", "created_at_history", "last_modified_commit", "last_modified_at", "age_days", "commit_count", "author_count", "lines_added", "lines_deleted", "churn_score", "stability_bucket", "call_fan_in", "call_fan_out", "call_edge_in_count", "call_edge_out_count", "call_is_leaf", "call_is_entrypoint", "call_is_public", "risk_score", "risk_level", "risk_component_coverage", "risk_component_complexity", "risk_component_static", "risk_component_hotspot", "is_pure", "uses_io", "touches_db", "uses_time", "uses_randomness", "modifies_globals", "modifies_closure", "spawns_threads_or_tasks", "has_transitive_effects", "purity_confidence", "param_nullability_json", "return_nullability", "has_preconditions", "has_postconditions", "has_raises", "contract_confidence", "role", "framework", "role_confidence", "role_sources_json", "tags", "owners", "doc_short", "doc_long", "doc_params", "doc_returns", "created_at"],
    },
    "analytics.function_types": {
        "table": "analytics.function_types",
        "columns": ["function_goid_h128", "urn", "repo", "commit", "rel_path", "language", "kind", "qualname", "start_line", "end_line", "total_params", "return_type", "type_comment", "param_types", "created_at"],
    },
    "analytics.function_validation": {
        "table": "analytics.function_validation",
        "columns": ["repo", "commit", "function_goid_h128", "rel_path", "qualname", "issue", "detail", "created_at"],
    },
    "analytics.goid_risk_factors": {
        "table": "analytics.goid_risk_factors",
        "columns": ["function_goid_h128", "urn", "repo", "commit", "rel_path", "language", "kind", "qualname", "loc", "logical_loc", "cyclomatic_complexity", "complexity_bucket", "typedness_bucket", "typedness_source", "hotspot_score", "file_typed_ratio", "static_error_count", "has_static_errors", "executable_lines", "covered_lines", "coverage_ratio", "tested", "test_count", "failing_test_count", "last_test_status", "risk_score", "risk_level", "tags", "owners", "created_at"],
    },
    "analytics.graph_metrics_functions": {
        "table": "analytics.graph_metrics_functions",
        "columns": ["repo", "commit", "function_goid_h128", "call_fan_in", "call_fan_out", "call_in_degree", "call_out_degree", "call_pagerank", "call_betweenness", "call_closeness", "call_cycle_member", "call_cycle_id", "call_layer", "created_at"],
    },
    "analytics.graph_metrics_functions_ext": {
        "table": "analytics.graph_metrics_functions_ext",
        "columns": ["repo", "commit", "function_goid_h128", "call_betweenness", "call_closeness", "call_eigenvector", "call_harmonic", "call_core_number", "call_clustering_coeff", "call_triangle_count", "call_is_articulation", "call_articulation_impact", "call_is_bridge_endpoint", "call_component_id", "call_component_size", "call_scc_id", "call_scc_size", "call_ancestor_count", "call_descendant_count", "call_community_id", "created_at"],
    },
    "analytics.graph_metrics_modules": {
        "table": "analytics.graph_metrics_modules",
        "columns": ["repo", "commit", "module", "import_fan_in", "import_fan_out", "import_in_degree", "import_out_degree", "import_pagerank", "import_betweenness", "import_closeness", "import_cycle_member", "import_cycle_id", "import_layer", "symbol_fan_in", "symbol_fan_out", "created_at"],
    },
    "analytics.graph_metrics_modules_ext": {
        "table": "analytics.graph_metrics_modules_ext",
        "columns": ["repo", "commit", "module", "import_betweenness", "import_closeness", "import_eigenvector", "import_harmonic", "import_k_core", "import_constraint", "import_effective_size", "import_rich_club", "import_shell_index", "import_community_id", "import_component_id", "import_component_size", "import_scc_id", "import_scc_size", "created_at"],
    },
    "analytics.graph_stats": {
        "table": "analytics.graph_stats",
        "columns": ["graph_name", "repo", "commit", "node_count", "edge_count", "weak_component_count", "scc_count", "component_layers", "avg_clustering", "diameter_estimate", "avg_shortest_path_estimate", "created_at"],
    },
    "analytics.graph_validation": {
        "table": "analytics.graph_validation",
        "columns": ["repo", "commit", "graph_name", "entity_id", "issue", "severity", "rel_path", "detail", "metadata", "created_at"],
    },
    "analytics.hello_example": {
        "table": "analytics.hello_example",
        "columns": ["message", "value"],
    },
    "analytics.history_timeseries": {
        "table": "analytics.history_timeseries",
        "columns": ["repo", "entity_kind", "entity_stable_id", "function_goid_h128", "module", "rel_path", "language", "qualname", "commit", "commit_ts", "loc", "cyclomatic_complexity", "coverage_ratio", "static_error_count", "typedness_bucket", "risk_score", "risk_level", "bucket_label", "created_at_row", "function_goid_h128_1", "created_at_row_1"],
    },
    "analytics.module_profile": {
        "table": "analytics.module_profile",
        "columns": ["repo", "commit", "module", "path", "language", "file_count", "total_loc", "total_logical_loc", "function_count", "class_count", "avg_file_complexity", "max_file_complexity", "high_risk_function_count", "medium_risk_function_count", "low_risk_function_count", "max_risk_score", "avg_risk_score", "module_coverage_ratio", "tested_function_count", "untested_function_count", "import_fan_in", "import_fan_out", "cycle_group", "in_cycle", "role", "role_confidence", "role_sources_json", "tags", "owners", "created_at"],
    },
    "analytics.semantic_roles_functions": {
        "table": "analytics.semantic_roles_functions",
        "columns": ["repo", "commit", "function_goid_h128", "role", "framework", "role_confidence", "role_sources_json", "created_at"],
    },
    "analytics.semantic_roles_modules": {
        "table": "analytics.semantic_roles_modules",
        "columns": ["repo", "commit", "module", "role", "role_confidence", "role_sources_json", "created_at"],
    },
    "analytics.static_diagnostics": {
        "table": "analytics.static_diagnostics",
        "columns": ["repo", "commit", "rel_path", "pyrefly_errors", "pyright_errors", "ruff_errors", "total_errors", "has_errors"],
    },
    "analytics.subsystem_agreement": {
        "table": "analytics.subsystem_agreement",
        "columns": ["repo", "commit", "module", "subsystem_id", "import_community_id", "agrees", "created_at"],
    },
    "analytics.subsystem_graph_metrics": {
        "table": "analytics.subsystem_graph_metrics",
        "columns": ["repo", "commit", "subsystem_id", "import_in_degree", "import_out_degree", "import_pagerank", "import_betweenness", "import_closeness", "import_layer", "created_at"],
    },
    "analytics.subsystem_modules": {
        "table": "analytics.subsystem_modules",
        "columns": ["repo", "commit", "subsystem_id", "module", "role"],
    },
    "analytics.subsystem_profile_cache": {
        "table": "analytics.subsystem_profile_cache",
        "columns": ["repo", "commit", "subsystem_id", "name", "description", "module_count", "modules_json", "entrypoints_json", "internal_edge_count", "external_edge_count", "fan_in", "fan_out", "function_count", "avg_risk_score", "max_risk_score", "high_risk_function_count", "risk_level", "import_in_degree", "import_out_degree", "import_pagerank", "import_betweenness", "import_closeness", "import_layer", "created_at"],
    },
    "analytics.subsystems": {
        "table": "analytics.subsystems",
        "columns": ["repo", "commit", "subsystem_id", "name", "description", "module_count", "modules_json", "entrypoints_json", "internal_edge_count", "external_edge_count", "fan_in", "fan_out", "function_count", "avg_risk_score", "max_risk_score", "high_risk_function_count", "risk_level", "created_at"],
    },
    "analytics.symbol_graph_metrics_functions": {
        "table": "analytics.symbol_graph_metrics_functions",
        "columns": ["repo", "commit", "function_goid_h128", "symbol_betweenness", "symbol_closeness", "symbol_eigenvector", "symbol_harmonic", "symbol_k_core", "symbol_constraint", "symbol_effective_size", "symbol_community_id", "symbol_component_id", "symbol_component_size", "created_at"],
    },
    "analytics.symbol_graph_metrics_modules": {
        "table": "analytics.symbol_graph_metrics_modules",
        "columns": ["repo", "commit", "module", "symbol_betweenness", "symbol_closeness", "symbol_eigenvector", "symbol_harmonic", "symbol_k_core", "symbol_constraint", "symbol_effective_size", "symbol_community_id", "symbol_component_id", "symbol_component_size", "created_at"],
    },
    "analytics.tags_index": {
        "table": "analytics.tags_index",
        "columns": ["tag", "description", "includes", "excludes", "matches"],
    },
    "analytics.test_catalog": {
        "table": "analytics.test_catalog",
        "columns": ["test_id", "test_goid_h128", "urn", "repo", "commit", "rel_path", "qualname", "kind", "status", "duration_ms", "markers", "parametrized", "flaky", "created_at"],
    },
    "build.asset_aliases": {
        "table": "build.asset_aliases",
        "columns": ["alias", "asset_kind", "asset_key", "version_hash", "set_by_run_id", "set_at", "note"],
    },
    "build.asset_diffs": {
        "table": "build.asset_diffs",
        "columns": ["asset_kind", "asset_key", "from_version_hash", "to_version_hash", "diff_kind", "summary", "computed_at", "computed_by_run_id"],
    },
    "build.asset_lineage": {
        "table": "build.asset_lineage",
        "columns": ["downstream_kind", "downstream_key", "downstream_version", "upstream_kind", "upstream_key", "upstream_version", "edge_kind", "created_at", "meta"],
    },
    "build.asset_version_events": {
        "table": "build.asset_version_events",
        "columns": ["run_id", "repo", "commit", "asset_kind", "asset_key", "version_hash", "target", "impl_kind", "status", "location", "input_hash", "options_hash", "recorded_at", "meta"],
    },
    "build.asset_versions": {
        "table": "build.asset_versions",
        "columns": ["asset_kind", "asset_key", "version_hash", "schema_hash", "row_count", "bytes", "created_at", "meta"],
    },
    "build.output_manifests": {
        "table": "build.output_manifests",
        "columns": ["target", "repo", "commit", "impl_kind", "computed_at", "duration_ms", "input_hash", "output_hash", "row_count", "options_hash", "change_delta"],
    },
    "build.run_asset_versions": {
        "table": "build.run_asset_versions",
        "columns": ["run_id", "repo", "commit", "asset_kind", "asset_key", "version_hash", "target", "resolution_kind", "recorded_at", "meta"],
    },
    "build.run_environments": {
        "table": "build.run_environments",
        "columns": ["run_id", "python_version", "os_name", "os_version", "tool_versions", "config_hash", "git_dirty", "captured_at"],
    },
    "build.run_nodes": {
        "table": "build.run_nodes",
        "columns": ["run_id", "node_name", "target", "node_type", "status", "started_at", "completed_at", "duration_ms", "error", "tags"],
    },
    "build.run_targets": {
        "table": "build.run_targets",
        "columns": ["run_id", "repo", "commit", "target", "impl_kind", "status", "input_hash", "options_hash", "duration_ms", "row_counts", "drift_summaries", "error", "dep_hashes", "recorded_at"],
    },
    "build.runs": {
        "table": "build.runs",
        "columns": ["run_id", "repo", "commit", "requested_targets", "computed_targets", "skipped_targets", "started_at", "completed_at", "status", "error_summary", "duration_ms"],
    },
    "build.scip_runs": {
        "table": "build.scip_runs",
        "columns": ["run_id", "repo", "commit", "mode", "options_hash", "tool_version", "total_modules", "changed_modules", "deleted_modules", "changed_ratio", "batch_size", "batch_count", "decision", "ratio_gate_applied", "ratio_gate_min_modules", "ratio_gate_min_changed", "hash_source", "hash_source_breakdown", "hash_reused", "hash_computed", "plan_ms", "hash_ms", "tool_ms", "parse_ms", "merge_ms", "write_ms", "total_ms", "status", "error_summary", "output_scip", "recorded_at"],
    },
    "ci.plan_entries": {
        "table": "ci.plan_entries",
        "columns": ["run_id", "created_at_utc", "requested_targets", "target", "domain", "action", "cache_hit_ratio", "block_reasons", "miss_nodes", "reads", "writes_tables", "writes_artifacts", "build_fingerprint", "plan_schema_version"],
    },
    "core.ast_metrics": {
        "table": "core.ast_metrics",
        "columns": ["rel_path", "node_count", "function_count", "class_count", "avg_depth", "max_depth", "complexity", "generated_at"],
    },
    "core.ast_nodes": {
        "table": "core.ast_nodes",
        "columns": ["path", "node_type", "name", "qualname", "lineno", "end_lineno", "decorator_start_line", "decorator_end_line", "col_offset", "end_col_offset", "start_byte", "end_byte", "parent_qualname", "decorators", "docstring", "ctx", "type_comment", "type_ignores", "identifier", "attribute", "imported", "asname", "module", "level", "constant_kind", "hash"],
    },
    "core.cst_nodes": {
        "table": "core.cst_nodes",
        "columns": ["path", "node_id", "kind", "span", "text_preview", "parents", "qnames"],
    },
    "core.docstrings": {
        "table": "core.docstrings",
        "columns": ["repo", "commit", "rel_path", "module", "qualname", "kind", "lineno", "end_lineno", "raw_docstring", "style", "short_desc", "long_desc", "params", "returns", "raises", "examples", "created_at"],
    },
    "core.file_line_index": {
        "table": "core.file_line_index",
        "columns": ["repo", "commit", "rel_path", "line", "start_byte", "end_byte", "encoding"],
    },
    "core.file_state": {
        "table": "core.file_state",
        "columns": ["repo", "commit", "rel_path", "language", "size_bytes", "mtime_ns", "content_hash"],
    },
    "core.goid_crosswalk": {
        "table": "core.goid_crosswalk",
        "columns": ["repo", "commit", "goid", "lang", "module_path", "file_path", "start_line", "end_line", "scip_symbol", "ast_qualname", "cst_node_id", "chunk_id", "symbol_id", "updated_at"],
    },
    "core.goids": {
        "table": "core.goids",
        "columns": ["goid_h128", "urn", "repo", "commit", "rel_path", "language", "kind", "qualname", "start_line", "end_line", "created_at"],
    },
    "core.ingest_runs": {
        "table": "core.ingest_runs",
        "columns": ["repo", "commit", "step", "run_id", "mode", "started_at", "finished_at", "duration_s", "rows_inserted", "rows_deleted", "status", "error_kind", "error_message", "datasets", "modules_total", "modules_changed", "modules_deleted", "modules_changed_ratio", "modules_deleted_ratio", "use_full_rebuild"],
    },
    "core.modules": {
        "table": "core.modules",
        "columns": ["module", "path", "repo", "commit", "language", "tags", "owners", "row_hash"],
    },
    "core.parse_manifest": {
        "table": "core.parse_manifest",
        "columns": ["repo", "commit", "rel_path", "producer", "parse_ok", "encoding", "default_indent", "default_newline", "has_trailing_newline", "future_imports", "parser_backend", "libcst_version", "error_kind", "error_message", "error_line", "error_col", "error_snippet"],
    },
    "core.py_bc_blocks": {
        "table": "core.py_bc_blocks",
        "columns": ["repo", "commit", "rel_path", "block_id", "code_unit_id", "start_offset", "end_offset", "start_label", "kind", "anchor_span_start_byte", "anchor_span_end_byte", "first_instr_index", "last_instr_index"],
    },
    "core.py_bc_cfg_edges": {
        "table": "core.py_bc_cfg_edges",
        "columns": ["repo", "commit", "rel_path", "edge_id", "code_unit_id", "src_block_id", "dst_block_id", "kind", "cond_instr_id", "exc_entry_index"],
    },
    "core.py_bc_code_units": {
        "table": "core.py_bc_code_units",
        "columns": ["repo", "commit", "rel_path", "code_unit_id", "parent_code_unit_id", "qualpath", "co_name", "co_qualname", "kind", "co_firstlineno", "span_start_byte", "span_end_byte", "flags", "argcount", "posonlyargcount", "kwonlyargcount", "nlocals", "stacksize", "varnames", "names", "freevars", "cellvars", "bytecode_len", "exceptiontable_len", "python_version", "bytecode_magic", "optimize", "dont_inherit"],
    },
    "core.py_bc_defuse_events": {
        "table": "core.py_bc_defuse_events",
        "columns": ["repo", "commit", "rel_path", "event_id", "code_unit_id", "instr_id", "instr_index", "event_kind", "space", "name", "confidence"],
    },
    "core.py_bc_exception_table": {
        "table": "core.py_bc_exception_table",
        "columns": ["repo", "commit", "rel_path", "code_unit_id", "exc_entry_index", "start_offset", "end_offset", "target_offset", "depth", "lasti", "start_label", "end_label", "target_label"],
    },
    "core.py_bc_instructions": {
        "table": "core.py_bc_instructions",
        "columns": ["repo", "commit", "rel_path", "code_unit_id", "instr_id", "instr_physical_id", "instr_index", "start_offset", "offset", "cache_offset", "end_offset", "ext_arg_len", "op_len", "cache_len", "opcode", "opname", "baseopcode", "baseopname", "arg", "argrepr", "argval_kind", "argval_str", "argval_int", "argval_repr", "is_jump_target", "jump_target_offset", "jump_target_label", "label", "starts_line", "line_number", "pos", "span_start_byte", "span_end_byte", "cache_info", "cache_bytes", "op_bytes"],
    },
    "core.py_inspect_annotations_kv": {
        "table": "core.py_inspect_annotations_kv",
        "columns": ["repo", "commit", "mode", "object_id", "eval_str", "key", "value", "status"],
    },
    "core.py_inspect_class_attrs": {
        "table": "core.py_inspect_class_attrs",
        "columns": ["repo", "commit", "mode", "class_object_id", "attr_name", "attr_kind", "defining_object_id", "value_kind", "value_object_id", "value_ref", "desc_is_data", "desc_is_methoddesc", "desc_is_getset", "desc_is_member", "status"],
    },
    "core.py_inspect_class_mro": {
        "table": "core.py_inspect_class_mro",
        "columns": ["repo", "commit", "mode", "class_object_id", "mro_index", "base_object_id", "base_kind", "status"],
    },
    "core.py_inspect_members_static": {
        "table": "core.py_inspect_members_static",
        "columns": ["repo", "commit", "mode", "owner_object_id", "owner_kind", "attr_name", "value_kind", "value_object_id", "value_ref", "desc_kind", "desc_is_data", "desc_is_methoddesc", "desc_is_getset", "desc_is_member", "status"],
    },
    "core.py_inspect_objects": {
        "table": "core.py_inspect_objects",
        "columns": ["repo", "commit", "mode", "object_id", "object_addr", "kind", "module_name", "qualname", "name", "type_qualname", "is_builtin", "is_callable", "is_descriptor", "has_wrapped", "has_signature_override", "has_annotations", "status"],
    },
    "core.py_inspect_runtime_state": {
        "table": "core.py_inspect_runtime_state",
        "columns": ["repo", "commit", "mode", "object_id", "object_kind", "state_kind", "state", "frame_object_id", "frame_file", "frame_module", "frame_code_qualname", "frame_code_name", "frame_firstlineno", "frame_line", "frame_start_line", "frame_end_line", "frame_start_col", "frame_end_col", "frame_offset", "locals", "status"],
    },
    "core.py_inspect_signature_params": {
        "table": "core.py_inspect_signature_params",
        "columns": ["repo", "commit", "mode", "signature_id", "param_index", "name", "kind", "default_present", "default_value", "annotation_present", "annotation_value", "status"],
    },
    "core.py_inspect_signatures": {
        "table": "core.py_inspect_signatures",
        "columns": ["repo", "commit", "mode", "signature_id", "object_id", "variant", "follow_wrapped", "eval_str", "effective_object_id", "sig_text", "sig_format", "return_annotation", "has_varargs", "has_varkw", "status"],
    },
    "core.py_inspect_source": {
        "table": "core.py_inspect_source",
        "columns": ["repo", "commit", "mode", "object_id", "file_name", "start_line", "line_count", "source_sha256", "source_preview", "status"],
    },
    "core.py_inspect_unwrap_hops": {
        "table": "core.py_inspect_unwrap_hops",
        "columns": ["repo", "commit", "mode", "root_object_id", "hop", "object_id", "has_wrapped", "has_signature_override", "stop_reason", "status"],
    },
    "core.py_sym_bindings": {
        "table": "core.py_sym_bindings",
        "columns": ["repo", "commit", "rel_path", "binding_id", "scope_id", "name", "binding_kind", "declared_here", "referenced_here", "assigned_here", "annotated_here", "scoping_class"],
    },
    "core.py_sym_function_partitions": {
        "table": "core.py_sym_function_partitions",
        "columns": ["repo", "commit", "rel_path", "scope_id", "parameters", "locals", "globals", "nonlocals", "frees"],
    },
    "core.py_sym_namespace_edges": {
        "table": "core.py_sym_namespace_edges",
        "columns": ["repo", "commit", "rel_path", "scope_id", "symbol_row_id", "name", "child_scope_id", "edge_kind", "is_ambiguous"],
    },
    "core.py_sym_resolution_edges": {
        "table": "core.py_sym_resolution_edges",
        "columns": ["repo", "commit", "rel_path", "edge_id", "src_binding_id", "dst_binding_id", "kind", "confidence", "reason"],
    },
    "core.py_sym_scope_edges": {
        "table": "core.py_sym_scope_edges",
        "columns": ["repo", "commit", "rel_path", "parent_scope_id", "child_scope_id", "edge_kind"],
    },
    "core.py_sym_scopes": {
        "table": "core.py_sym_scopes",
        "columns": ["repo", "commit", "rel_path", "scope_id", "scope_local_id", "parent_scope_id", "scope_type", "scope_name", "qualpath", "lineno", "is_nested", "is_optimized", "has_children", "anchor_ast_node_id", "span_start_byte", "span_end_byte", "anchor_confidence", "anchor_reason"],
    },
    "core.py_sym_symbols": {
        "table": "core.py_sym_symbols",
        "columns": ["repo", "commit", "rel_path", "scope_id", "symbol_row_id", "name", "is_referenced", "is_assigned", "is_imported", "is_annotated", "is_parameter", "is_local", "is_global", "is_declared_global", "is_nonlocal", "is_free", "is_namespace", "namespace_count"],
    },
    "core.repo_map": {
        "table": "core.repo_map",
        "columns": ["repo", "commit", "modules", "overlays", "generated_at"],
    },
    "core.schema_inference_errors": {
        "table": "core.schema_inference_errors",
        "columns": ["table_key", "repo", "commit", "error", "occurred_at", "run_id"],
    },
    "core.scip_diagnostics": {
        "table": "core.scip_diagnostics",
        "columns": ["repo", "commit", "rel_path", "start_line", "start_col", "end_line", "end_col", "position_encoding", "text_document_encoding", "severity", "code", "message", "source", "created_at"],
    },
    "core.scip_external_symbols": {
        "table": "core.scip_external_symbols",
        "columns": ["repo", "commit", "symbol", "package_manager", "package_name", "package_version", "created_at"],
    },
    "core.scip_module_state": {
        "table": "core.scip_module_state",
        "columns": ["repo", "commit", "rel_path", "content_hash", "options_hash", "tool_version", "shard_path", "updated_at"],
    },
    "core.scip_occurrence_span_xref": {
        "table": "core.scip_occurrence_span_xref",
        "columns": ["repo", "commit", "rel_path", "scip_symbol", "roles", "is_definition", "is_reference", "is_import", "is_write", "is_read", "enclosing_symbol", "start_line", "start_col", "end_line", "end_col", "position_encoding", "text_document_encoding", "start_byte", "end_byte", "goid_h128", "created_at"],
    },
    "core.scip_occurrence_syntax_xref": {
        "table": "core.scip_occurrence_syntax_xref",
        "columns": ["repo", "commit", "rel_path", "producer", "scip_symbol", "scip_occurrence_id", "occ_start_byte", "occ_end_byte", "occ_start_line", "occ_start_col", "occ_end_line", "occ_end_col", "syntax_node_id", "match_kind", "candidate_count"],
    },
    "core.scip_occurrences": {
        "table": "core.scip_occurrences",
        "columns": ["repo", "commit", "rel_path", "symbol", "start_line", "start_col", "end_line", "end_col", "roles", "position_encoding", "text_document_encoding", "start_byte", "end_byte", "created_at"],
    },
    "core.scip_symbol_goid_xref": {
        "table": "core.scip_symbol_goid_xref",
        "columns": ["repo", "commit", "scip_symbol", "goid_h128", "def_rel_path", "def_start_line", "def_start_col", "def_end_line", "def_end_col", "position_encoding", "text_document_encoding", "created_at"],
    },
    "core.scip_symbol_information": {
        "table": "core.scip_symbol_information",
        "columns": ["repo", "commit", "symbol", "documentation", "kind", "display_name", "signature", "enclosing_symbol", "created_at"],
    },
    "core.scip_symbol_relationships": {
        "table": "core.scip_symbol_relationships",
        "columns": ["repo", "commit", "symbol", "related_symbol", "relationship_kind", "created_at"],
    },
    "core.scip_symbols": {
        "table": "core.scip_symbols",
        "columns": ["repo", "commit", "rel_path", "symbol", "documentation", "created_at"],
    },
    "core.syntax_call_args": {
        "table": "core.syntax_call_args",
        "columns": ["repo", "commit", "rel_path", "producer", "call_id", "arg_ordinal", "arg_kind", "arg_name", "arg_start_line", "arg_start_col", "arg_end_line", "arg_end_col", "arg_start_byte", "arg_end_byte", "arg_span_id", "arg_expr_node_id", "extras_json"],
    },
    "core.syntax_calls": {
        "table": "core.syntax_calls",
        "columns": ["repo", "commit", "rel_path", "producer", "call_id", "call_node_id", "scope_id", "span_id", "callee_span_id", "callee_text", "arg_count", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte", "callee_start_byte", "callee_end_byte", "extras_json"],
    },
    "core.syntax_calls_resolved": {
        "table": "core.syntax_calls_resolved",
        "columns": ["repo", "commit", "rel_path", "producer", "call_id", "call_node_id", "scope_id", "span_id", "callee_span_id", "callee_text", "arg_count", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte", "callee_start_byte", "callee_end_byte", "scip_symbol", "scip_occurrence_id", "scip_roles", "is_definition", "is_reference", "is_import", "is_write", "is_read", "goid_h128", "syntax_node_id", "match_kind", "candidate_count", "extras_json"],
    },
    "core.syntax_defs": {
        "table": "core.syntax_defs",
        "columns": ["repo", "commit", "rel_path", "producer", "def_id", "scope_id", "span_id", "def_kind", "name", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte", "extras_json"],
    },
    "core.syntax_defs_resolved": {
        "table": "core.syntax_defs_resolved",
        "columns": ["repo", "commit", "rel_path", "producer", "def_id", "scope_id", "span_id", "def_kind", "name", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte", "scip_symbol", "scip_occurrence_id", "scip_roles", "is_definition", "is_reference", "is_import", "is_write", "is_read", "goid_h128", "syntax_node_id", "match_kind", "candidate_count", "extras_json"],
    },
    "core.syntax_edges": {
        "table": "core.syntax_edges",
        "columns": ["repo", "commit", "rel_path", "producer", "parent_node_id", "child_node_id", "edge_kind", "field_name", "child_ordinal"],
    },
    "core.syntax_edges_augmented": {
        "table": "core.syntax_edges_augmented",
        "columns": ["repo", "commit", "rel_path", "producer", "parent_node_id", "child_node_id", "edge_kind", "field_name", "child_ordinal"],
    },
    "core.syntax_func_params": {
        "table": "core.syntax_func_params",
        "columns": ["repo", "commit", "rel_path", "producer", "func_def_id", "param_def_id", "param_ordinal", "param_kind", "param_name", "param_start_line", "param_start_col", "param_end_line", "param_end_col", "param_start_byte", "param_end_byte", "param_span_id", "param_node_id", "extras_json"],
    },
    "core.syntax_imports": {
        "table": "core.syntax_imports",
        "columns": ["repo", "commit", "rel_path", "producer", "import_id", "scope_id", "span_id", "import_kind", "module", "name", "alias", "level", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte", "extras_json"],
    },
    "core.syntax_imports_resolved": {
        "table": "core.syntax_imports_resolved",
        "columns": ["repo", "commit", "rel_path", "producer", "import_id", "scope_id", "span_id", "import_kind", "module", "name", "alias", "level", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte", "scip_symbol", "scip_occurrence_id", "scip_roles", "is_definition", "is_reference", "is_import", "is_write", "is_read", "goid_h128", "syntax_node_id", "match_kind", "candidate_count", "extras_json"],
    },
    "core.syntax_nodes": {
        "table": "core.syntax_nodes",
        "columns": ["repo", "commit", "rel_path", "producer", "language", "node_id", "node_kind", "raw_kind", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte", "text_preview", "extras_json"],
    },
    "core.syntax_nodes_augmented": {
        "table": "core.syntax_nodes_augmented",
        "columns": ["repo", "commit", "rel_path", "producer", "language", "node_id", "node_kind", "raw_kind", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte", "text_preview", "extras_json"],
    },
    "core.syntax_refs": {
        "table": "core.syntax_refs",
        "columns": ["repo", "commit", "rel_path", "producer", "ref_id", "scope_id", "span_id", "ref_kind", "name", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte", "extras_json"],
    },
    "core.syntax_refs_resolved": {
        "table": "core.syntax_refs_resolved",
        "columns": ["repo", "commit", "rel_path", "producer", "ref_id", "scope_id", "span_id", "ref_kind", "name", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte", "scip_symbol", "scip_occurrence_id", "scip_roles", "is_definition", "is_reference", "is_import", "is_write", "is_read", "goid_h128", "syntax_node_id", "match_kind", "candidate_count", "extras_json"],
    },
    "core.syntax_scopes": {
        "table": "core.syntax_scopes",
        "columns": ["repo", "commit", "rel_path", "producer", "scope_id", "scope_kind", "start_line", "start_col", "end_line", "end_col", "parent_scope_id"],
    },
    "core.syntax_spans": {
        "table": "core.syntax_spans",
        "columns": ["repo", "commit", "rel_path", "producer", "span_id", "span_kind", "start_line", "start_col", "end_line", "end_col", "start_byte", "end_byte"],
    },
    "core.ts_captures": {
        "table": "core.ts_captures",
        "columns": ["repo", "commit", "rel_path", "language", "query_pack", "capture_name", "start_byte", "end_byte", "start_row", "start_col", "end_row", "end_col", "node_type", "text_preview", "extras"],
    },
    "core.ts_changed_ranges": {
        "table": "core.ts_changed_ranges",
        "columns": ["repo", "commit", "rel_path", "language", "start_byte", "end_byte", "start_row", "start_col", "end_row", "end_col"],
    },
    "core.ts_edges": {
        "table": "core.ts_edges",
        "columns": ["repo", "commit", "rel_path", "language", "parent_node_id", "child_node_id", "field_id", "field_name", "child_ordinal"],
    },
    "core.ts_language_metadata": {
        "table": "core.ts_language_metadata",
        "columns": ["repo", "commit", "language", "abi_version", "semantic_version", "node_kind_count", "field_count", "parse_state_count", "created_at"],
    },
    "core.ts_nodes": {
        "table": "core.ts_nodes",
        "columns": ["repo", "commit", "rel_path", "language", "node_id", "node_type", "grammar_id", "kind_id", "is_named", "is_missing", "is_error", "has_error", "start_byte", "end_byte", "start_row", "start_col", "end_row", "end_col", "parse_state", "next_parse_state", "text_preview", "extras_json"],
    },
    "core.ts_parse_errors": {
        "table": "core.ts_parse_errors",
        "columns": ["repo", "commit", "rel_path", "language", "error_type", "message", "start_byte", "end_byte", "start_row", "start_col", "end_row", "end_col", "text_preview", "extras_json"],
    },
    "core.ts_parse_manifest": {
        "table": "core.ts_parse_manifest",
        "columns": ["repo", "commit", "rel_path", "producer", "parse_ok", "encoding", "default_indent", "default_newline", "has_trailing_newline", "future_imports", "parser_backend", "libcst_version", "error_kind", "error_message", "error_line", "error_col", "error_snippet"],
    },
    "core.ts_syntax_node_xref": {
        "table": "core.ts_syntax_node_xref",
        "columns": ["repo", "commit", "rel_path", "language", "producer", "ts_node_id", "syntax_node_id", "match_kind", "candidate_count"],
    },
    "core.ts_tokens": {
        "table": "core.ts_tokens",
        "columns": ["repo", "commit", "rel_path", "language", "token_id", "token_kind", "node_type", "start_byte", "end_byte", "start_row", "start_col", "end_row", "end_col", "text_preview", "extras_json"],
    },
    "core.ts_trivia": {
        "table": "core.ts_trivia",
        "columns": ["repo", "commit", "rel_path", "language", "trivia_id", "trivia_kind", "node_type", "start_byte", "end_byte", "start_row", "start_col", "end_row", "end_col", "text_preview", "extras_json"],
    },
    "core.ts_weld_coverage": {
        "table": "core.ts_weld_coverage",
        "columns": ["repo", "commit", "rel_path", "language", "ts_node_count", "mapped_count", "coverage_ratio"],
    },
    "docs.v_validation_summary": {
        "table": "docs.v_validation_summary",
        "columns": ["repo", "commit", "validation_type", "issue_count", "affected_files", "affected_functions"],
    },
    "graph.call_graph_edges": {
        "table": "graph.call_graph_edges",
        "columns": ["repo", "commit", "caller_goid_h128", "callee_goid_h128", "callsite_path", "callsite_line", "callsite_col", "language", "kind", "resolved_via", "confidence", "evidence_json"],
    },
    "graph.call_graph_nodes": {
        "table": "graph.call_graph_nodes",
        "columns": ["goid_h128", "language", "kind", "arity", "is_public", "rel_path"],
    },
    "graph.cdg_edges": {
        "table": "graph.cdg_edges",
        "columns": ["function_goid_h128", "src_block_id", "dst_block_id", "via_succ_block_id", "edge_kind", "via_edge_kind"],
    },
    "graph.cfg_blocks": {
        "table": "graph.cfg_blocks",
        "columns": ["function_goid_h128", "block_idx", "block_id", "label", "file_path", "start_line", "end_line", "kind", "stmts_json", "in_degree", "out_degree"],
    },
    "graph.cfg_edges": {
        "table": "graph.cfg_edges",
        "columns": ["function_goid_h128", "src_block_id", "dst_block_id", "edge_kind"],
    },
    "graph.cpg_call_targets": {
        "table": "graph.cpg_call_targets",
        "columns": ["repo", "commit", "rel_path", "call_id", "call_node_id", "callee_symbol", "callee_def_id", "callee_def_node_id", "callee_goid_h128", "callee_entry_block_id", "callee_exit_block_id", "target_role", "binding_kind", "origin", "call_kind", "augop", "resolution_kind", "confidence", "candidate_count", "extras_json"],
    },
    "graph.cpg_edges": {
        "table": "graph.cpg_edges",
        "columns": ["repo", "commit", "src_cpg_node_id", "dst_cpg_node_id", "edge_kind", "edge_layer", "rel_path", "ordinal", "extras_json"],
    },
    "graph.cpg_edges_arg_to_param": {
        "table": "graph.cpg_edges_arg_to_param",
        "columns": ["repo", "commit", "call_id", "src_arg_node_id", "dst_param_node_id", "edge_kind", "arg_ordinal", "param_ordinal", "arg_name", "param_name", "arg_slot", "arg_role", "arg_is_implicit", "call_kind", "augop", "confidence", "extras_json"],
    },
    "graph.cpg_edges_calls": {
        "table": "graph.cpg_edges_calls",
        "columns": ["repo", "commit", "call_id", "call_node_id", "callee_entry_block_id", "edge_kind", "confidence", "extras_json"],
    },
    "graph.cpg_edges_ret_to_call": {
        "table": "graph.cpg_edges_ret_to_call",
        "columns": ["repo", "commit", "call_id", "exit_block_id", "call_node_id", "target_role", "call_kind", "origin", "edge_kind", "confidence", "extras_json"],
    },
    "graph.cpg_nodes": {
        "table": "graph.cpg_nodes",
        "columns": ["repo", "commit", "cpg_node_id", "node_kind", "source_table_key", "source_pk_json", "rel_path", "start_byte", "end_byte", "extras_json"],
    },
    "graph.dfg_edges": {
        "table": "graph.dfg_edges",
        "columns": ["function_goid_h128", "src_block_id", "dst_block_id", "src_var", "dst_var", "edge_kind", "via_phi", "use_kind"],
    },
    "graph.import_graph_edges": {
        "table": "graph.import_graph_edges",
        "columns": ["repo", "commit", "src_module", "dst_module", "src_fan_out", "dst_fan_in", "cycle_group", "module_layer"],
    },
    "graph.import_modules": {
        "table": "graph.import_modules",
        "columns": ["repo", "commit", "module", "scc_id", "component_size", "layer", "cycle_group"],
    },
    "graph.pdg_edges": {
        "table": "graph.pdg_edges",
        "columns": ["function_goid_h128", "src_block_id", "dst_block_id", "edge_kind", "src_var", "dst_var", "via_phi", "use_kind", "via_succ_block_id", "via_edge_kind"],
    },
    "graph.symbol_use_edges": {
        "table": "graph.symbol_use_edges",
        "columns": ["symbol", "def_path", "use_path", "same_file", "same_module", "def_goid_h128", "use_goid_h128"],
    },
}
