from collections.abc import Hashable, Iterable, Iterator, Mapping
from typing import Literal, overload

from networkx import algorithms as algorithms
from networkx import approximation as approximation
from networkx import readwrite as readwrite

Node = Hashable
type NodeData = dict[str, object]
type EdgeData = dict[str, object]
type Edge = tuple[Node, Node]

class _NodeView(Mapping[Node, NodeData]):
    @overload
    def __call__(self, data: Literal[True]) -> Iterable[tuple[Node, NodeData]]: ...
    @overload
    def __call__(self, data: Literal[False] = False) -> Iterable[Node]: ...
    def __iter__(self) -> Iterator[Node]: ...

class _EdgeView(Mapping[Edge, EdgeData]):
    @overload
    def __call__(self, data: Literal[True]) -> Iterable[tuple[Node, Node, EdgeData]]: ...
    @overload
    def __call__(self, data: Literal[False] = False) -> Iterable[Edge]: ...
    def __iter__(self) -> Iterator[Edge]: ...

class Graph:
    nodes: _NodeView
    edges: _EdgeView
    graph: dict[str, object]

    def __init__(self, incoming_graph_data: object | None = None) -> None: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __len__(self) -> int: ...
    def __contains__(self, node: object) -> bool: ...
    def __getitem__(self, node: Node) -> dict[Node, EdgeData]: ...
    def add_node(self, node_for_adding: Node, **attr: object) -> None: ...
    def add_nodes_from(self, nodes_for_adding: Iterable[Node], **attr: object) -> None: ...
    def add_edge(self, u_of_edge: Node, v_of_edge: Node, **attr: object) -> None: ...
    def add_edges_from(
        self,
        ebunch_to_add: Iterable[tuple[Node, Node] | tuple[Node, Node, Mapping[str, object]]],
    ) -> None: ...
    def add_weighted_edges_from(
        self,
        ebunch_to_add: Iterable[tuple[Node, Node, float | int]],
        weight: str = "weight",
    ) -> None: ...
    def remove_edges_from(
        self,
        ebunch: Iterable[Edge] | Iterable[tuple[Node, Node, EdgeData]],
    ) -> None: ...
    def number_of_nodes(self) -> int: ...
    def number_of_edges(self) -> int: ...
    def copy(self) -> Graph: ...
    def has_edge(self, u: Node, v: Node) -> bool: ...
    def has_node(self, n: Node) -> bool: ...
    def get_edge_data(self, u: Node, v: Node) -> EdgeData | None: ...
    def neighbors(self, n: Node) -> Iterable[Node]: ...
    def to_undirected(self, as_view: bool = False) -> Graph: ...
    def subgraph(self, nodes: Iterable[Node]) -> Graph: ...
    @overload
    def degree(
        self, node: None = None, weight: str | None = None
    ) -> Iterable[tuple[Node, int]]: ...
    @overload
    def degree(self, node: Node, weight: str | None = None) -> int: ...

class DiGraph(Graph):
    @overload
    def in_degree(
        self, node: None = None, weight: str | None = None
    ) -> Iterable[tuple[Node, int]]: ...
    @overload
    def in_degree(self, node: Node, weight: str | None = None) -> int: ...
    @overload
    def out_degree(
        self, node: None = None, weight: str | None = None
    ) -> Iterable[tuple[Node, int]]: ...
    @overload
    def out_degree(self, node: Node, weight: str | None = None) -> int: ...
    def predecessors(self, n: Node) -> Iterable[Node]: ...
    def successors(self, n: Node) -> Iterable[Node]: ...
    def reverse(self, copy: bool = True) -> DiGraph: ...

class _Config:
    backend_priority: list[str]
    warnings_to_ignore: set[str]

config: _Config

def is_directed_acyclic_graph(graph: DiGraph) -> bool: ...
def descendants(graph: DiGraph, source: Node) -> set[Node]: ...
def ancestors(graph: DiGraph, source: Node) -> set[Node]: ...
def all_pairs_shortest_path_length(
    graph: Graph | DiGraph,
) -> Iterable[tuple[Node, dict[Node, int]]]: ...
def all_simple_paths(
    graph: DiGraph,
    source: Node,
    target: Node,
    cutoff: int | None = None,
) -> Iterable[list[Node]]: ...
@overload
def subgraph(graph: DiGraph, nodes: Iterable[Node]) -> DiGraph: ...
@overload
def subgraph(graph: Graph, nodes: Iterable[Node]) -> Graph: ...
def bridges(graph: Graph) -> Iterable[Edge]: ...
def articulation_points(graph: Graph) -> Iterable[Node]: ...
def selfloop_edges(
    graph: Graph | DiGraph,
    data: bool = False,
) -> Iterable[Edge] | Iterable[tuple[Node, Node, EdgeData]]: ...
def condensation(
    graph: DiGraph,
    *,
    scc: Iterable[set[Node]] | None = None,
) -> DiGraph: ...
def topological_sort(graph: DiGraph) -> Iterable[Node]: ...
def simple_cycles(graph: DiGraph) -> Iterable[list[Node]]: ...
def connected_components(graph: Graph) -> Iterable[set[Node]]: ...
def weakly_connected_components(graph: DiGraph) -> Iterable[set[Node]]: ...
def strongly_connected_components(graph: DiGraph) -> Iterable[set[Node]]: ...
def number_strongly_connected_components(graph: DiGraph) -> int: ...
def number_weakly_connected_components(graph: DiGraph) -> int: ...
def average_shortest_path_length(graph: Graph | DiGraph) -> float: ...
def density(graph: Graph | DiGraph) -> float: ...
def degree(graph: Graph | DiGraph, weight: str | None = None) -> Iterable[tuple[Node, int]]: ...
def set_edge_attributes(
    graph: Graph | DiGraph,
    values: Mapping[Edge, object],
    name: str | None = None,
) -> None: ...
def get_node_attributes(graph: Graph | DiGraph, name: str) -> dict[Node, object]: ...
@overload
def relabel_nodes(graph: DiGraph, mapping: Mapping[Node, Node], copy: bool = True) -> DiGraph: ...
@overload
def relabel_nodes(graph: Graph, mapping: Mapping[Node, Node], copy: bool = True) -> Graph: ...
@overload
def complete_graph(n: int, create_using: DiGraph) -> DiGraph: ...
@overload
def complete_graph(n: int, create_using: Graph | None = None) -> Graph: ...
def path_graph(n: int) -> Graph: ...
def cycle_graph(n: int) -> Graph: ...
def barbell_graph(m1: int, m2: int) -> Graph: ...
def betweenness_centrality(
    graph: Graph | DiGraph, *args: object, **kwargs: object
) -> dict[Node, float]: ...
def closeness_centrality(
    graph: Graph | DiGraph, *args: object, **kwargs: object
) -> dict[Node, float]: ...
def degree_centrality(
    graph: Graph | DiGraph, *args: object, **kwargs: object
) -> dict[Node, float]: ...
def eigenvector_centrality(
    graph: Graph | DiGraph, *args: object, **kwargs: object
) -> dict[Node, float]: ...
def harmonic_centrality(
    graph: Graph | DiGraph, *args: object, **kwargs: object
) -> dict[Node, float]: ...
def in_degree_centrality(graph: DiGraph, *args: object, **kwargs: object) -> dict[Node, float]: ...
def out_degree_centrality(graph: DiGraph, *args: object, **kwargs: object) -> dict[Node, float]: ...
def pagerank(graph: Graph | DiGraph, *args: object, **kwargs: object) -> dict[Node, float]: ...
def dag_longest_path_length(graph: DiGraph, *args: object, **kwargs: object) -> int: ...
def immediate_dominators(graph: DiGraph, *args: object, **kwargs: object) -> dict[Node, Node]: ...
def dominance_frontiers(
    graph: DiGraph, *args: object, **kwargs: object
) -> dict[Node, set[Node]]: ...
def single_source_shortest_path_length(
    graph: Graph | DiGraph,
    source: Node,
    *args: object,
    **kwargs: object,
) -> dict[Node, int]: ...
def clustering(graph: Graph | DiGraph, *args: object, **kwargs: object) -> dict[Node, float]: ...
def triangles(graph: Graph | DiGraph, *args: object, **kwargs: object) -> dict[Node, int]: ...
def core_number(graph: Graph | DiGraph, *args: object, **kwargs: object) -> dict[Node, int]: ...
def constraint(graph: Graph | DiGraph, *args: object, **kwargs: object) -> dict[Node, float]: ...
def effective_size(
    graph: Graph | DiGraph, *args: object, **kwargs: object
) -> dict[Node, float]: ...
