class NetworkXExceptionError(Exception): ...
class NetworkXError(NetworkXExceptionError): ...
class NetworkXAlgorithmError(NetworkXExceptionError): ...
class NetworkXUnfeasibleError(NetworkXExceptionError): ...
class NetworkXNoPathError(NetworkXExceptionError): ...
class PowerIterationFailedConvergenceError(NetworkXExceptionError): ...

NetworkXException = NetworkXExceptionError
NetworkXUnfeasible = NetworkXUnfeasibleError
NetworkXNoPath = NetworkXNoPathError
PowerIterationFailedConvergence = PowerIterationFailedConvergenceError
